### DISCUSSION TITLE
Disable schema validation

### DISCUSSION THREAD

**Discussion by kishankishore2908** [sqlc-dev/sqlc#1371] [Q&A]
Is there a way I can `sqlc` wherein I do not have to have the `CREATE SCHEMA` statement in my migration ?

**Comment by danthegoodman1** [comment]
You shouldn't need to, works for me without one.

**Reply by kishankishore2908** [reply]
Do you have an example `sqlc.json` ?

**Reply by danthegoodman1** [reply]
```yml
version: 1
packages:
  - path: "crdb"
    name: "crdb"
    engine: "postgresql"
    schema: "schema.sql"
    queries: "./queries/"
    sql_package: "pgx/v4"
```
