### DISCUSSION TITLE
How to use directory and subdirectories to store queries?

### DISCUSSION THREAD

**Discussion by soasada** [sqlc-dev/sqlc#2205] [Q&A]
Hi, I have the following config:

```yaml
version: "2"
sql:
  - schema: "db/migrations"
    queries: "db/queries"
    engine: "postgresql"
    gen:
      go:
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
          - db_type: "uuid"
            go_type: "github.com/google/uuid.NullUUID"
            nullable: true
        emit_json_tags: true
        json_tags_case_style: "camel"
        package: "database"
        out: "internal/database"
```

How can I specify `queries` directory to also hold subdirectories? I tried with `db/queries/**` or `db/queries/*` but is failing. Any ideas?
