### DISCUSSION TITLE
Expanding lint rules to parsed migrations

### DISCUSSION THREAD

**Discussion by mfridman** [sqlc-dev/sqlc#2512] [Feature Requests & Ideas]
The [lint rule functionality](https://docs.sqlc.dev/en/stable/howto/vet.html#linting-queries) recently added is awesome!

Would you consider expanding this beyond `query` and `config` to support something like `migration`?

Since sqlc already parses various migration files one could also use the sqlc lint rules to vet migrations.

```yaml
rules:
  - name: no-drop-table
    message: "never drop tables"
    rule: |
      migration.contains("DROP TABLE")
```

**Comment by andrewmbenton** [comment]
We could expand the scope of the `query` variable to include all the statements in the schema and query config paths. Then your rule would just be

```yaml
rules:
  - name: no-drop-table
    message: "never drop tables"
    rule: |
      query.contains("DROP TABLE")
```

Would you expect to have a way to easily distinguish whether a rule will apply to a "query" (all `sqlc vet` does today) vs a "schema" change though?

**Reply by mfridman** [reply]
I think I'd like to distinguish between `schema.` vs `query.` changes since not all bits of the migration may translate into generated code. 

I could see the argument where folks might want to apply a rule to both, and it'd be "annoying" to have to define duplicate rules for "query" vs "schema". But this might be an edge case.

For some context, I was recently evaluating migration-specific linters like:

- https://github.com/sbdchd/squawk
- atlas (https://atlasgo.io/versioned/lint)
- heck, I even considered adding this as a `goose lint` command to [pressly/goose](https://github.com/pressly/goose)

But given `sqlc` already knows about the schema and has this functionality it seems like a huge win to have these lint rules applied to both the queries and schema changes.

**Reply by andrewmbenton** [reply]
That makes sense. I think it's a good idea and probably not that hard to add. I haven't looked at the way sqlc handles schema migration parsing though.

Even if we provide access via a single variable like `query` or `statement` I think we can provide an easy way to distinguish between queries and schema changes. One thing @kyleconroy suggested was adding a simple filter expression to a rule definition. Something like this:

```yaml
rules:
- name: no-drop-table
  message: "never drop tables"
  rule: |
      statement.contains("DROP TABLE")
  if: !statement.is_query
```

In any case I'll try to find a little time to implement a first version this morning to see what roadblocks I run into.
