### DISCUSSION TITLE
Example using PostGis geometry

### DISCUSSION THREAD

**Discussion by tamis-laan** [sqlc-dev/sqlc#2598] [Q&A]
I just started using sqlc and I need to combine it using PostGis, specifically to encode GPS coordinates.

I have the following database schema:
``` sql
CREATE TABLE IF NOT EXISTS reports (
	description TEXT NOT NULL,
	location geometry(Point, 4326) NOT NULL
);
```
I think I should do the following:
``` sql
-- name: CreateReport :one
INSERT INTO reports 
	( description, location)
VALUES
	($1, $2)
RETURNING description, location;
```
Here is my sqlc.yaml config:
``` yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "./migrations"
    gen:
      go:
        package: "database"
        sql_package: "pgx/v5"
        out: "./src/database"
        emit_json_tags: true
        overrides:
          - db_type: "geometry"
            go_type: "github.com/cridenour/go-postgis.Point"
```
If I execute the following:
``` go
report, err := db.CreateReport(context.Background(), database.CreateReportParams{
	Description: "description",
	Location: postgis.Point{
		X: 2.0,
		Y: 3.0,
	},
})
```
I get back the error: `parse error - invalid geometry (SQLSTATE XX000)`

How would I get this to work properly?
