### DISCUSSION TITLE
Using a function with custom types?

### DISCUSSION THREAD

**Discussion by tamis-laan** [sqlc-dev/sqlc#2603] [Q&A] [answered]
using the following sql:
``` sql
-- name: CreateReport :one
INSERT INTO reports 
	(title, description, location)
VALUES
	($1, $2, ST_GEOMFROMTEXT($3))
RETURNING id, title, description, location;
```
I get the following generated struct:
``` go
type CreateReportParams struct {
	Title          string      `json:"title"`
	Description    string      `json:"description"`
	StGeomfromtext interface{} `json:"st_geomfromtext"`
}
```
As you can see for some reason the ST_GEOMFROMTEXT function is interpreted as a variable. The correct output should be:
``` sql
type CreateReportParams struct {
	Title          string      `json:"title"`
	Description    string      `json:"description"`
	Location types.PostGISPoint `json:"location"`
}
```
Why does this happen? How can I deal with this?

**Comment by orisano** [comment]
According to https://postgis.net/docs/ST_GeomFromText.html, shouldn't $3 be TEXT?

**Reply by tamis-laan** [reply]
I wrote a types.PostGISPoint implements for the Scan and Value functions for supporting the PostGis point type:

``` go 
package types

import (
	"bytes"
	"database/sql/driver"
	"encoding/binary"
	"encoding/hex"
	"fmt"
)

// PostGISPoint is wrapper for PostGIS POINT type.
type PostGISPoint struct {
	Lon, Lat float64
}

// Value implements database/sql/driver Valuer interface.
// It returns point as WKT with SRID 4326 (WGS 84).
func (p PostGISPoint) Value() (driver.Value, error) {
	return []byte(fmt.Sprintf("SRID=4326;POINT(%.8f %.8f)", p.Lon, p.Lat)), nil // <-- TEXT is produced here
}
...
```
sqlc:
``` yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "./migrations"
    gen:
      go:
        package: "database"
        sql_package: "pgx/v5"
        out: "./src/database"
        emit_json_tags: true
        overrides:
          - db_type: "geometry"
            go_type: "example/server/src/types.PostGISPoint"
```
