### DISCUSSION TITLE
docker run ... generate fails with a tls failure per query

### DISCUSSION THREAD

**Discussion by rossbagley** [sqlc-dev/sqlc#3092] [Q&A]
Here's the command I ran:
`> docker run --env SQLC_AUTH_TOKEN=${SQLC_AUTH_TOKEN} --rm -v "${PWD}:/src" -w /src sqlc/sqlc -f .sqlc/sqlc.yaml generate`

.sqlc/sqlc.yaml
```
version: '2'
cloud:
  project: '${SQLC_PROJECT}'
sql:
- schema: "../internal/model/sqlc/schema.sql"
  queries: "../internal/model/sqlc/query.sql"
  engine: postgresql
  database:
    managed: true
  gen:
    go:
      package: "internal/model/sqlc"
      out: "internal/model/sqlc"
      sql_package: "pgx/v5"
```
internal/model/sqlc/schema.sql
```
CREATE TABLE domain (
    r_id      bigint PRIMARY KEY,
    name      text   NOT NULL,
    parent_id bigint REFERENCES domain(r_id),
    domain_pb bytea  NOT NULL
);
```

internal/model/sqlc/query.sql
```
-- name: GetDomain :one
SELECT * FROM domain
    WHERE r_id = $1 LIMIT 1;

-- name: ListDomains :many
SELECT * FROM domain
    ORDER BY name;

-- name: CreateDomain :one
INSERT INTO domain (
    r_id,
    name,
    parent_id,
    domain_pb
) VALUES (
    $1, $2, $3, $4
) RETURNING *;

-- name: DeleteDomain :exec
DELETE FROM domain
    WHERE r_id = $1;
```

The output is:
```
# package internal/model/sqlc
../internal/model/sqlc/query.sql:1:1: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
../internal/model/sqlc/query.sql:6:1: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
../internal/model/sqlc/query.sql:10:1: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
../internal/model/sqlc/query.sql:20:1: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

The line numbers are the first line of each query in query.sql. I would guess that Docker Desktop for Windows is rejecting a self-signed certificate on the connection and my Google-fu has not figured out how to tell Docker it's okay this time.

I'm using the docker command because the windows version of sqlc doesn't do postgresql.
