### DISCUSSION TITLE
Stronger typing for columns/fields in Go

### DISCUSSION THREAD

**Discussion by ptman** [sqlc-dev/sqlc#3174] [Feature Requests & Ideas]
Hi,

Type safety is nice. Having the computer catch more bugs is nice. Is anyone else doing something like this:

```sql
CREATE TABLE users (user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
```

```go
package types

type UserID int64
```

```yaml
version: '2'
sql:
- gen:
    go:
      overrides:
      - column: 'users.user_id'
        go_type:
          import: 'types'
          type: 'UserID'
```

This gives types to e.g. ID columns, so that you don't accidentally assign one bigint/int64 ID column to another, mixing tables/relations.

Is anyone else doing something similar? Can this be made easier? More automated?
