### DISCUSSION TITLE
OVerride type of aggregated JSON with `json_agg`

### DISCUSSION THREAD

**Discussion by svenwltr** [sqlc-dev/sqlc#3275] [Q&A]
Hello!

I have this query:

```sql
-- name: ListSBOMComponents :many
select
    component_name,
    json_agg(version) as versions,
    json_agg(license_ids) as licenses
from sbom_components
group by component_name;
```

Where `component_name`, `version` and `license_ids` are all strings.

The resulting type is this:

```go
type ListSBOMComponentsRow struct {
	ComponentName string `json:"componentName"`
	Versions      []byte `json:"versions"`
	Licenses      []byte `json:"licenses"`
}
```

I am using `pgx` where it is possible to specify which types JSON objects deserialize to. (so [this](https://docs.sqlc.dev/en/stable/reference/datatypes.html#json)), but I don't know what to put into the column field.

What I tried is:

```yaml
          - column: "sbom_components.versions"
            go_type:
              type: "[]string"
```

What I expect is

```go
type ListSBOMComponentsRow struct {
	ComponentName string   `json:"componentName"`
	Versions      []string `json:"versions"`
	Licenses      []string `json:"licenses"`
}
```

But that did not work as expected. Any ideas on this?

**Comment by shagohead** [comment]
It so because of `sbom_components.versions` is not a column. It's an aliased tuple value. In you're case you can use type override for `db_type` not a `column`. You can create that type with `CREATE TYPE` or just `CREATE DOMAIN` for existing `json(b)` type. I'am not sure sqlc will (un)marshall json when dealing with `db_type`, not `column`, but most likely it will.

```sql
CREATE DOMAIN versions AS jsonb;
```

```yaml
          - db_type: "versions"
            go_type:
              type: "[]string"
```

**Reply by shagohead** [reply]
Or you can try:

```yaml
          - db_type: "versions"
            go_type:
              type: "string"
              slice: true
```
