### DISCUSSION TITLE
Control where individual generated files go?

### DISCUSSION THREAD

**Discussion by Nikola-Milovic** [sqlc-dev/sqlc#3384] [Q&A] [answered]
Hello everyone, just wandering if something like this is possible, I have the following

`db/schema/main.sql` <- here are all my tables
and `db/queries/user.sql | payment.sql | document.sql` and so on

I would like to move each of the *.sql file into a specific directory and output package, so the user would go into `user` module under `user/queries/`.

Using golang, is there a way currently to achieve this? 

My current config

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/queries"
    schema:
      - "db/schemas"
    database:
      uri: postgres//postgres:postgres@postgres:5432/seolitic
    gen:
      go:
        package: "db"
        out: "internal/db"
```

**Comment by MWT-proger** [comment, marked as answer]
Hi, try something like this.

```yml
version: "2" 
sql:
    - name: usersql
       engine: "postgresql" 
       queries: "db/queries/user.sql" 
       schema: - "db/schemas" 
       database: uri: postgres//postgres:postgres@postgres:5432/seolitic 
       gen: 
          go: 
              package: "userdb" 
              out: "internal/db/user"

    - name: paymentsql
       engine: "postgresql" 
       queries: "db/queries/payment.sql" 
       schema: - "db/schemas" 
       database: uri: postgres//postgres:postgres@postgres:5432/seolitic 
       gen: 
          go: 
              package: "paymentdb" 
              out: "internal/db/payment
```
