### DISCUSSION TITLE
basic question: supporting to specify DIR at 'sqlc.yaml | json' at 'queries:' key instead of file

### DISCUSSION THREAD

**Discussion by roccho-dev** [sqlc-dev/sqlc#3545] [Q&A]
basic question: supporting to specify DIR at 'sqlc.yaml | json' at 'queries:' key instead of file

```yaml
sql:
  - engine: sqlite
    schema: ./db/schema.sql
    queries: ./db/queries/         // specify dir instead of file like 'query.sql'
    codegen:
      - out: ./src/db
```
