### DISCUSSION TITLE
How do I override the tsvector type?

### DISCUSSION THREAD

**Discussion by Ayo-Awe** [sqlc-dev/sqlc#3678] [Q&A]
I'm trying to override the tsvector type with a string, but it's not working.

Here's what my config looks like
```yaml
version: '2'
sql:
  - engine: 'postgresql'
    queries: './queries'
    schema: './migrations'
    gen:
      go:
        package: 'db'
        out: './'
        sql_package: 'pgx/v5'
        emit_methods_with_db_argument: true
        overrides:
          - db_type: "pg_catalog.tsvector"
            go_type: "string"
```
