### DISCUSSION TITLE
MySql pointers

### DISCUSSION THREAD

**Discussion by astro-cosmo** [sqlc-dev/sqlc#3807] [Q&A]
Is there a specific reason that `emit_pointer_for_null_types` option is not available for MySQL? The sql.nullxxx types are very inconvenient.

Setting manual overrides seems to have no effect:

```
- db_type: "int"
     go_type:
            type: "int"
            pointer: true
```
