### DISCUSSION TITLE
Model structs in models.go vs. MyFooRow

### DISCUSSION THREAD

**Discussion by markschmid** [sqlc-dev/sqlc#667] [Issue Triage] [answered]
Maybe this is a very dumb question, but here's what I don't get:

In ```models.go```, there's a per-table model struct, yet in the ```:one``` and ```:many``` selects, not those models but  ```MyFooRow``` and ```[]MyFooRow``` structs are used.

Can anybody quickly shed some light on this? Am I doing something wrong? Thanks!

**Comment by markschmid** [comment]
My question is basically:
When to use which struct?

**Comment by kyleconroy** [comment]
sqlc will generate per-query structs when they don't match any of the existing tables. Can you provide more information about your setup? What version of sqlc are you using? Can you post your schema, the problematic query, or the sqlc.json file?

**Comment by markschmid** [comment]
I'm using version 1.5 with the dolphin parser.
Here's an example:

schema/persons.sql:
```
CREATE TABLE `persons` (
  `id` int NOT NULL AUTO_INCREMENT,
  `firstname` varchar(255) DEFAULT NULL,
  `lastname` varchar(255) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `shortname` varchar(255) DEFAULT NULL,
  `visitorpass_id` varchar(255) DEFAULT NULL,
  `funktion` varchar(255) DEFAULT NULL,
  `device` int DEFAULT NULL,
  `assignment_active` tinyint(1) DEFAULT '0',
  `deleted` datetime DEFAULT NULL,
  `tenant` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `id_2` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

query/person.sql:
```
/* name: ListPersons :many */
select
  id,
  firstname,
  lastname,
  shortname,
  visitorpass_id,
  funktion,
  device,
  assignment_active
from persons
where deleted is null
and role = ?
and tenant = ?;
```

sqlc.yaml:
```
version: "1"
packages:
  - name: "db"
    path: "db/"
    queries: "./sql/query/"
    schema: "./sql/schema/"
    engine: "mysql:beta"
    emit_json_tags: true
    emit_prepared_queries: true
    emit_interface: false
    emit_exact_table_names: false
```

After ```sqlc generate```, the compiled function for ```ListPersons``` looks like this:
```
func (q *Queries) ListPersons(ctx context.Context, arg ListPersonsParams) ([]ListPersonsRow, error) {
  [...]
}
```

So, it is returning ```[]ListPersonsRow```.
In ```db/models.go```, there is a ```Person``` struct, but none of the generated code is using it. Is this model only for me to use?
