### ISSUE TITLE
Is registering custom datatypes required to use ENUM with pgx?

### ISSUE THREAD

**Issue by rhodee** [sqlc-dev/sqlc#1177]
### Version

1.10.0

### What happened?

Using SQL `1.10.0` and the `pgx` sql_package produces different outcomes than the default configuration. The latter returns `pgx.ScanArgError` and the former returns an `[]uint8` which is also different from previous sqlc versions, which returned `string` values from the SQL (posted below).

When invoking `sqlc generate`  the default sql_package generates:

```go
const lotAltitude = `-- name: LotAltitude :many
SELECT unnest(enum_range(null::lot_altitude_designation))
`

func (q *Queries) LotAltitude(ctx context.Context) ([]interface{}, error) {
	rows, err := q.query(ctx, q.lotAltitudeStmt, lotAltitude)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var unnest interface{}
		if err := rows.Scan(&unnest); err != nil {
			return nil, err
		}
		items = append(items, unnest)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

`pgx` sql_package produces:

```go
const lotAltitude = `-- name: LotAltitude :many
SELECT unnest(enum_range(null::lot_altitude_designation))
`

func (q *Queries) LotAltitude(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, lotAltitude)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var unnest interface{}
		if err := rows.Scan(&unnest); err != nil {
			return nil, err
		}
		items = append(items, unnest)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

### Database schema

```sql
CREATE TYPE lot_altitude_designation AS ENUM ('strict_soft_bean', 'strict_hard_bean', 'unknown');
```

### SQL queries

```sql
-- name: LotAltitude :many
SELECT unnest(enum_range(null::lot_altitude_designation))
```

### Configuration

```yaml
version: 1
packages:
- name: "store"
  path: "store"
  engine: "postgresql"
  queries: "./sql/queries"
  schema: "./sql/migrations"
  sql_package: "pgx/v4"
  emit_prepared_queries: true
  emit_interface: false
  emit_exact_table_names: false
  emit_empty_slices: false
  emit_json_tags: true
  json_tags_case_style: "camel"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
