### ISSUE TITLE
SELECT WITH query with multiple table aliases in FROM get ignored, only last one considered

### ISSUE THREAD

**Issue by gsora** [sqlc-dev/sqlc#1237]
### Version

1.10.0

### What happened?

When selecting with `SELECT WITH` with multiple table aliases in the FROM statement, only the last one on the statements list gets considered.

Given the query, we're expecting to select everything from both c1 and c2, but the generated query only selects from c2:

```sql
WITH
	q
		AS (
			SELECT
				authors.name, authors.bio
			FROM
				authors
				LEFT JOIN fake ON authors.name = fake.name
		)
SELECT
	c2.name, c2.bio, c2.name, c2.bio
FROM
	q AS c1,
	q as c2
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);

CREATE TABLE fake (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: BadQuery :exec
WITH
	q
		AS (
			SELECT
				authors.name, authors.bio
			FROM
				authors
				LEFT JOIN fake ON authors.name = fake.name
		)
SELECT
	*
FROM
	q AS c1,
	q as c2;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/79910ee88639b38cdbcbbefeccb1e1a55b8492776ed7fd0a4bbb617217411d46

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
