### ISSUE TITLE
Join on stmt do not check column names

### ISSUE THREAD

**Issue by krhubert** [sqlc-dev/sqlc#1239]
### Version

1.10.0

### What happened?

sqlc does not validate if column name exists when exec join stmt.

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE books (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  author_id BIGSERIAL REFERENCES authors(id)
);
```

### SQL queries

```sql
-- name: ListAuthors :many
SELECT * FROM authors JOIN books ON authors.id = book.author_id1;
```

### Configuration

```yaml
version: "1"
packages:
  - name: "sqlc"
    path: "./sqlc"
    queries: "./queries"
    schema: "./schema.sql"
    engine: "postgresql"
    sql_package: "pgx/v4"
    emit_json_tags: true
```

### Playground URL

https://play.sqlc.dev/p/74c44149c6dc3aa96c44766c15b40d66e713045ea2cb97e1c8dbd5d8870b099b

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
