### ISSUE TITLE
`CREATE OR REPLACE TRIGGER` is valid as of PostgreSQL 14

### ISSUE THREAD

**Issue by wilsonehusin** [sqlc-dev/sqlc#1246]
### Version

1.10.0

### What happened?

To be fair, this is less of a bug but more about "follow upstream"  report 😄 

[PostgreSQL 14 considers `CREATE OR REPLACE TRIGGER`](https://www.postgresql.org/docs/current/sql-createtrigger.html) a valid syntax. `sqlc` at the moment considers it as invalid syntax.

### Relevant log output

```shell
❯ sqlc generate
# package db
sql/schema/foo.sql:1:1: syntax error at or near "TRIGGER"
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    path: "internal/db"
    queries: "./sql/query/"
    schema: "./sql/schema/"
    engine: "postgresql"
    sql_package: "pgx/v4"
    emit_prepared_queries: true
    emit_interface: false
    emit_exact_table_names: false
    emit_empty_slices: false
    emit_json_tags: true
    json_tags_case_style: "camel"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
