### ISSUE TITLE
Structs names no have non-camel case attribute names

### ISSUE THREAD

**Issue by kyleconroy** [sqlc-dev/sqlc#1319]
### Version

1.11.0

### What happened?

I'm not sure what happened, maybe because of the update to v1.11 but previously my sqlc generated structs used to have camel case attribute names like:

```
type SomeStruct struct {
    ThisShouldBeCamelCase string
}
```

but now, whenever I do sqlc generate, it generates the struct name in a non-camel case fashion

```
type SomeStruct struct {
    Thisshouldbecamelcase string
}
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  nameForBook text      NOT NULL
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/ab9bd10aca020c2bbac0312a833d2e80d660f541f64fff706ca0a6720d5cac91

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
