### ISSUE TITLE
Unintuitive error message for missing semicolon

### ISSUE THREAD

**Issue by impzero** [sqlc-dev/sqlc#1323]
### Version

1.10.0

### What happened?

I find it quite unintuitive to get this type of output for missing semicolons (;)

For example this input
```sql
-- name: GetUserAndPostExample :many
SELECT u.user_id,
       p.post_id
FROM posts as p
         JOIN users as u ON p.post_author_id = u.user_id
WHERE p.post_author_id = ANY (
    SELECT user_id
    FROM users
    ORDER BY users.user_created_at
    LIMIT 1
)
```

Would be parsed by ```sqlc``` and the error I would receive was:
```bash
$ db/queries/posts.sql:1:1: syntax error at or near "SELECT"
```

Given the example above, you can image that in some cases when you have huge queries and a file full of queries, it gets super hard to find the exact causation

### Relevant log output

```shell
$ db/queries/posts.sql:1:1: syntax error at or near "SELECT"
```

### Database schema

```sql
--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    post_id uuid NOT NULL,
    post_description character varying(2000) DEFAULT ''::character varying NOT NULL,
    post_title character varying(50) NOT NULL,
    post_price integer NOT NULL,
    post_quantity integer NOT NULL,
    post_targeted_for public.targeted_for NOT NULL,
    post_brand_id uuid NOT NULL,
    post_subcategory_id uuid NOT NULL,
    post_author_id uuid NOT NULL,
    post_created_at timestamp without time zone DEFAULT now() NOT NULL
);
```

### SQL queries

```sql
-- name: GetUserAndPostExample :many
SELECT u.user_id,
       p.post_id
FROM posts as p
         JOIN users as u ON p.post_author_id = u.user_id
WHERE p.post_author_id = ANY (
    SELECT user_id
    FROM users
    ORDER BY users.user_created_at
    LIMIT 1
)
```

### Configuration

```yaml
version: "1"
packages:
  - name: "postgres"
    path: "postgres"
    engine: "postgresql"
    emit_json_tags: false
    emit_exact_table_names: true
    schema: "db/migrations"
    queries: "db/queries"
overrides:
  - go_type: "github.com/gofrs/uuid.UUID"
    db_type: "uuid"
  - go_type: "github.com/gofrs/uuid.NullUUID"
    db_type: "uuid"
    nullable: true
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
