### ISSUE TITLE
column reference is ambiguous on insert select with single table

### ISSUE THREAD

**Issue by danilobuerger** [sqlc-dev/sqlc#1328]
### Version

1.11.0

### What happened?

When using INSERT ... SELECT with a single table, sqlc is not able to compile.

### Relevant log output

```shell
column reference "name" is ambiguous
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
INSERT INTO authors (id, name, bio) 
SELECT $1, name, bio
FROM authors
WHERE name = $2;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/3b568d39761e26955617d4db2b555fd6017b0fdcd6245147a73b57d5d48566cb

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
