### ISSUE TITLE
Preparing queries not generate correctly for MySQL

### ISSUE THREAD

**Issue by liemle3893** [sqlc-dev/sqlc#1379]
### Version

1.11.0

### What happened?

Preparing queries not generate correctly for MySQL

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  id   INT PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $1 LIMIT 1;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/455cfa178586c85e52d2206830417b513979577060857fb92fdf3fe6c725db2a

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
