### ISSUE TITLE
ORDER BY does not enforce column to exist

### ISSUE THREAD

**Issue by theFong** [sqlc-dev/sqlc#1411]
### Version

1.11.0

### What happened?

When creating a query that orders by a non-existent column, sqlc **does not** emit a `query.sql:x:y: column "adfadsf" does not exist` error.

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY adfadsf;
```

### Configuration

```yaml
version: 1
packages:
  - path: "sqlc"
    name: "sqlc"
    engine: "mysql"
    schema: "schema.sql"
    queries: "query.sql"
```

### Playground URL

https://play.sqlc.dev/p/9b40e9e704f08dc389049f02786f9d072d0c51839a432ff196dadcdfa6b19900

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
