### ISSUE TITLE
IF clause causes syntax error

### ISSUE THREAD

**Issue by akhilmhdh** [sqlc-dev/sqlc#1537]
### Version

1.12.0

### What happened?

First of all awesome library.

So I was playing around with sqlc and everything was going smooth. Then I tried to do an upsert by using `IF EXIST ELSE THEN`  query. But it keep saying syntax error.

Is `IF` clause not yet supported in sqlc. i went through old issues but couldn't find any information. 

Here is my trial query

```sql
-- name: UpsertUser :one

IF EXISTS (SELECT * FROM users WHERE email ='xxxxxxxx') 
BEGIN
   SELECT 1 FROM users
END
ELSE
BEGIN
    SELECT 2 FROM users;
END;
```

### Relevant log output

```shell
syntax error at or near "IF"
```

### Database schema

```sql
CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	name varchar(50),
	email varchar(50) NOT NULL UNIQUE,
	password text,
	is_disabled BOOLEAN DEFAULT false,
        is_confirmed Boolean,
);
```

### SQL queries

```sql
IF EXISTS (SELECT * FROM users WHERE email ='xxxxxxxx') 
BEGIN
   SELECT 1 FROM users
END
ELSE
BEGIN
    SELECT 2 FROM users;
END;
```

### Configuration

```yaml
version: 1
packages:
  - name: "db"
    path: "internal/auth/db"
    engine: "postgresql"
    schema: "internal/auth/db/schema.sql"
    queries: "internal/auth/db/query.sql"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
