### ISSUE TITLE
Getting "create table node cannot have both a ReferTable and Cols" error with legit schema

### ISSUE THREAD

**Issue by esenmx** [sqlc-dev/sqlc#1539]
### Version

1.12.0

### What happened?

I'm using `table inheritance` with `like` statement for of copying the all indexes, relations etc. 

This:
```sql
create table b
(
    like a including all
);
```
works fine(as obviously understood from error message).
But, since the postgres itself accepts the `like` statement with extra fields, I think sqlc should be able to generate the related code.

Not sure this is a bug or enhancement.

### Relevant log output

```shell
schema/schema.sql:1:1: create table node cannot have both a ReferTable and Cols
```

### Database schema

```sql
create table a
(
    foo int primary key
);

create table b
(
    bar int,
    like a including indexes
);
```

### SQL queries

```sql
-- name: CreateB :exec
insert into b(foo, bar)
values ($1, $2);
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    path: "./db/"
    queries: "./query/"
    schema: "./schema/"
    engine: "postgresql"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
