### ISSUE TITLE
UNION creates duplicate fields

### ISSUE THREAD

**Issue by esenmx** [sqlc-dev/sqlc#1546]
### Version

1.12.0

### What happened?

Generated code:
```go
type CreateACRow struct {
	Foo   int32
	Foo_2 int32
	Bar   sql.NullInt32
}
```

Similar to https://github.com/kyleconroy/sqlc/issues/568. It always creates duplicate fields with `_2` suffix. Using `DISTINCT` also does not work, checked the https://github.com/kyleconroy/sqlc/pull/896, it's not supported anyway.

### Database schema

```sql
create table a
(
    foo int primary key
);

create table c
(
    bar int
);
```

### SQL queries

```sql
-- Simple Example
select * from ((select * from a limit 1) union (select * from c limit 1)) as ac;

-- My Case
with x as (insert into a (foo) values ($1) returning *),
     y as (insert into c (bar) values ($2) returning *)
select *
from ((select * from x) union (select * from y)) as ac;
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    path: "./db/"
    queries: "./query/"
    schema: "./schema/"
    engine: "postgresql"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
