### ISSUE TITLE
Inserting values for case-sensitive columns and raises insertion error.

### ISSUE THREAD

**Issue by rickgrammer** [sqlc-dev/sqlc#1577]
### Version

1.12.0

### What happened?

When we use "RETURNING *" for case-sensitive column names, the generated query does not preserve column name's case-sensitivity.

In the log you can see that the return object is returning lastLogin which should actually be "lastLogin" (with quotes)

### Relevant log output

```shell
const createAuthor = `-- name: CreateAuthor :one
INSERT INTO author (
  id, email, password, updated, "lastLogin"
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, email, password, updated, lastLogin
`
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS author (
    id uuid primary key,
    email varchar(30) unique,
    password varchar(30) not null,
    created timestamptz(3) DEFAULT CURRENT_TIMESTAMP,
    updated timestamptz(3) not null,
    "lastLogin" timestamptz
);
```

### SQL queries

```sql
-- name: CreateAuthor :one
INSERT INTO author (
  id, email, password, updated, "lastLogin"
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING *;
```

### Configuration

```yaml
version: 1
packages:
  - path: "tutorial"
    name: "tutorial"
    engine: "postgresql"
    schema: "./migrations"
    queries: "query.sql"
    sql_package: "pgx/v4"
rename:
  id: "Id"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
