### ISSUE TITLE
Go: Initialism / acronym config

### ISSUE THREAD

**Issue by gnuletik** [sqlc-dev/sqlc#1586]
### What do you want to change?

# Context

In Go, we want to use capital letters for acronyms.
e.g.
```go
type MyModel struct {
  Smtp string
  Ip       string
}
```
should be 
```go
type MyModel struct {
  SMTP string
  IP       string
}
```

see https://github.com/golang/go/wiki/CodeReviewComments#initialisms

This is not supported  in the current version of sqlc: https://play.sqlc.dev/p/4110e992d522282f98265ab0afd17f21ebeab86e68cb92db7f18bca7e377fc1e

# Implementation

We could have a configuration in sqlc.yaml which provide a default `initialism` option, like :
- staticcheck does: https://staticcheck.io/docs/configuration/options/#initialisms
- revive: https://github.com/mgechev/revive/pull/61
- protobuf reference issue: https://github.com/golang/protobuf/issues/156

So, e.g.
```yaml
version: "1"
packages:
  - name: "db"
    path: "internal/db"
    queries: "./sql/query/"
    schema: "./sql/schema/"
    engine: "postgresql"
    go_initialisms: ["SMTP", "IP"]
```

It seems that it new config can be used here: https://github.com/kyleconroy/sqlc/blob/b648a7984880a16425ac05881f12e1869e1ac063/internal/codegen/golang/struct.go#L17-L30

Also, the `go_initialisms` option may be used for the json tags generation of `camelGo`, see https://github.com/kyleconroy/sqlc/issues/1585.

What do you think?

Thanks!

### What programming language backends need to be changed?

Go
