### ISSUE TITLE
config overrides - support additional imports for go generics 

### ISSUE THREAD

**Issue by krhubert** [sqlc-dev/sqlc#1662]
### What do you want to change?

Hi,

it would be great to allow add more imports when overriding db types. Let's say we have a `Null` package like below.

```go
package null

type Null[T any] struct {
  V     T
  Valid bool
}
```

Now I want to set a custom nullable ts type in config as follows:

```yaml
  - db_type: "pg_catalog.timestamp"
    nullable: true
    go_type:
      import: "github.com/myproject/null"
      type: "Null[time.Time]"
```

But this won't import `"time"` pkg.

### Solution

Allow to specify `imports` instead of `import`. With this change config will look like:

```yaml
  - db_type: "pg_catalog.timestamp"
    nullable: true
    go_type:
      imports:
      - "time" 
      - "github.com/myproject/null"
      type: "null.Null[time.Time]"

```

### What database engines need to be changed?

N/A

### What programming language backends need to be changed?

Go

**Comment by kyleconroy** [comment]
I think this is a great idea. When the 1.18 beta was released, I [asked for ideas](https://github.com/kyleconroy/sqlc/discussions/1342) on how sqlc should use them. Allowing people to experiment with nullable wrappers seems like a good first step.

I'm not sold on the config syntax, but I think it's a good starting point.

**Comment by krhubert** [comment]
```yaml
  - db_type: "pg_catalog.timestamp"
    nullable: true
    go_type:
      import: "time"\n"github.com/myproject/null"
      type: "null.Null[time.Time]"
```

There's a great workaround, that worked for me. I only hope it will work in the next versions.

**Comment by kyleconroy** [comment]
@krhubert Wow, that's one... inventive workaround. It's like SQL injection but for Go code generation.

As I said in June, I want to support this. Just need to figure out the proper design. I like `imports` vs `import`, but need to make sure the code generated constructs the generic type correctly. It sounds like that may already be the case.

**Comment by sourcec0de** [comment]
I am currently getting around this by running `goimports` after `sqlc`. :rofl: 
Having an `imports` keys would be awesome though.
I mentioned a possible API [here](https://github.com/kyleconroy/sqlc/discussions/1342#discussioncomment-3728759).
```yaml
go_type:
  imports: 
    - package: "utils"
      alias: "utils1"
    - package: "data"
      alias: "data1"
  type: "utils1.JSONB[data2.Type]"
```
