### ISSUE TITLE
rename for uuid to UUID not working

### ISSUE THREAD

**Issue by pushkar-anand** [sqlc-dev/sqlc#1716]
### Version

1.14.0

### What happened?

I have a column name `uuid` in my tables with `UUID` type. By default `sqlc` generates the struct field name as `Uuid`.

I have added a rename as follows:
```
        rename:
          # Override the field name for column "uuid". By default, sqlc is generating it as "Uuid".
          uuid: "UUID"
``` 

**Expected:**
The struct field name should be `UUID`.
**Actual:**
The struct field name should is `Uuid`.

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  uuid UUID NOT NULL,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $1 LIMIT 1;

-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;

-- name: CreateAuthor :one
INSERT INTO authors (
  name, bio
) VALUES (
  $1, $2
)
RETURNING *;

-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1;
```

### Configuration

```yaml
{
  "version": 2,
  "sql": [
    {
      "schema": "query.sql",
      "queries": "query.sql",
      "engine": "postgresql",
      "gen": {
        "go": {
          "package": "models",
          "out": "./models",
          "output_db_file_name": "db_gen.go",
          "output_files_suffix": "_gen",
          "sql_package": "pgx/v4",
          "emit_db_tags": true,
          "emit_prepared_queries": true,
          "emit_interface": true,
          "emit_empty_slices": false,
          "emit_json_tags": true,
          "json_tags_case_style": "snake",
          "emit_result_struct_pointers": true,
          "emit_enum_valid_method": true,
          "emit_all_enum_values": true,
          "rename": {
            "uuid": "UUID"
          },
          "overrides": [
            {
              "db_type": "uuid",
              "go_type": "string"
            }
          ]
        }
      }
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/f61aa5a0842d25dbb45cac7aea3926561172dc282c8d61fc487d3d7611b924cd

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
