### ISSUE TITLE
SQLite generation fails when using Quoted Identifiers

### ISSUE THREAD

**Issue by caleblloyd** [sqlc-dev/sqlc#1817]
### Version

1.15.0

### What happened?

Failure when SQLite identifiers are [quoted with double quotes](https://www.sqlite.org/lang_keywords.html), for example quoting a table name as `"test"` or a column name as `"id"`

### Relevant log output

```shell
sqlc generate failed.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	
	
	
	
	
)






type "Test" struct {
  "Id" string 
}
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE "test"
(
    "id" TEXT NOT NULL
);
```

### SQL queries

```sql
-- name: TestList :many
SELECT * FROM "test";
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "sqlite",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/1f469b2debde2c474439045390885b2bc9e9c9bcba0f9f2ecb78a8515b7afe07

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
