### ISSUE TITLE
SQLite column explicit NULL creates Unknown Type Error

### ISSUE THREAD

**Issue by caleblloyd** [sqlc-dev/sqlc#1818]
### Version

1.15.0

### What happened?

In SQLite, when a column is designated with an explicit NULL modifier, such as `id INTEGER NULL` or `id TEXT NULL` then an error occurs, such as `unknown SQLite type: integernull` or `unknown SQLite type: textnull`

### Relevant log output

```shell
sqlc generate failed.

2022/08/23 14:29:37 unknown SQLite type: integernull
2022/08/23 14:29:37 unknown SQLite type: integernull
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE test
(
    id INTEGER NULL
);
```

### SQL queries

```sql
-- name: TestList :many
SELECT * FROM test;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "sqlite",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/01df25ecce97214ab8073d8e4ac7c2487d9d11ed995c682b32913b1e09a8855f

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
