### ISSUE TITLE
Inserts are not typechecked at all

### ISSUE THREAD

**Issue by alarbada** [sqlc-dev/sqlc#1820]
### Version

1.15.0

### What happened?

The following example produces a query that will always fail, so IMHO it should result into a compilation error.

### Database schema

```sql
create table test (
	a character varying not null,
	b character varying not null
);
```

### SQL queries

```sql
-- name: Test :exec
insert into test (a)
values ($1);
```

### Configuration

```yaml
version: '2'
sql:
    - schema: 'pg/schema.sql'
      queries:
          - 'pg/queries.sql'
          - 'pg/alerts.sql'
      engine: 'postgresql'
      gen:
          go:
              sql_package: 'pgx/v4'
              package: 'pg'
              out: 'pg'
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
