### ISSUE TITLE
sqlite: `WHERE ... IN (?)` generates query with no parameters

### ISSUE THREAD

**Issue by trevorstarick** [sqlc-dev/sqlc#1829]
### Version

1.15.0

### What happened?

When generating a query using a `WHERE ... IN (?)` statement, I expected to get a function out that looked similar to  `func (q *Queries) Foo(ctx context.Context, in []interface{}) ([]string, error)` but the `in []interface{}` parameter isn't included.

Current workaround is to export the query and then have sqlx handle it via it's support for [in queries](https://jmoiron.github.io/sqlx/#inQueries).

### Database schema

```sql
CREATE TABLE foo (
	hash TEXT NOT NULL PRIMARY KEY
)
```

### SQL queries

```sql
-- name: Foo :many
SELECT * FROM foo WHERE hash IN (?) LIMIT 50;
```

### Configuration

```yaml
version: 2
sql:
    - engine: "sqlite"
      schema: "schema.sql"
      queries: "queries.sql"
      gen:
        go:
            package: "example"
            out: "example"
            emit_db_tags: true
            emit_prepared_queries: true
            emit_exact_table_names: true
            emit_empty_slices: true
            emit_exported_queries: true
            emit_json_tags: true
```

### Playground URL

https://play.sqlc.dev/p/91e8edaab2a3e8f4c48e79732e5243f827fd23a9d137ebff6d7fd12429b5d1d8

### What operating system are you using?

Linux, macOS

### What type of code are you generating?

Go
