### ISSUE TITLE
Can't use SQL keywords as parameter name

### ISSUE THREAD

**Issue by romuloab** [sqlc-dev/sqlc#1861]
### Version

1.15.0

### What happened?

Using sql keywords (`select`, `from`, `limit` etc) as arg names, either syntax, will throw an error.

https://play.sqlc.dev/p/87e70a86967219a955694db7e2ee707b55784759f5e1fbc3539952e25d0431e4

Renaming them to anything else, positional (`$1`), or `@limit1` solves the issue.

At the very least I'd expect the error to say I can't use keywords as named parameters, although I don't see why that could be an issue with the generated code.

### Relevant log output

```shell
# package db
query.sql:1:1: syntax error at or near "limit"
```
```


### Database schema

```sql
create table foo (id int);
```

### SQL queries

```sql
-- name: bogus :one
select id from foo limit @limit;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/87e70a86967219a955694db7e2ee707b55784759f5e1fbc3539952e25d0431e4

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
