### ISSUE TITLE
char type return whole length  include padding whitespace

### ISSUE THREAD

**Issue by Blankll** [sqlc-dev/sqlc#1888]
### Version

1.15.0

### What happened?

Hi, I just find when inserting a string to the Postgres column `char` type, the response & subsequent query for it returns the whole char's length including padding whitespace, I am not sure if this is designed in purpose, or if there is any config to return only insert content without padding whitespace? I haven't seen this in another orm
<img width="1333" alt="Screen Shot 2022-10-06 at 18 50 42" src="https://user-images.githubusercontent.com/28639911/194715187-2fb25014-cf49-4b00-a505-b9e6833e4ca3.png">

### Database schema

```sql
CREATE TABLE public."accounts"(
    "id" bigserial PRIMARY KEY,
    "username" CHAR(60) NOT NULL,
    "password" CHAR(120) NOT NULL,
    "gender" GENDER NOT NULL,
    "birth" DATE,
    "created" TIMESTAMPTZ DEFAULT NOW(),
    "modified" TIMESTAMPTZ DEFAULT NULL
);
```

### SQL queries

```sql
-- name: GetAccounts :many
SELECT * FROM accounts ORDER BY username LIMIT $1 OFFSET $2;
```

### Configuration

```yaml
version: "1"
project:
    id: ""
packages:
  - name: "sqlc"
    engine: "postgresql"
    ...
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: false
    emit_exact_table_names: false
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
