### ISSUE TITLE
MySQL @arg

### ISSUE THREAD

**Issue by mdigger** [sqlc-dev/sqlc#1955]
### Version

1.15.0

### What happened?

The `@` symbol does not work for MySQL to specify a parameter name in a query.

### Relevant log output

```shell
const insertTestError = `-- name: InsertTestError :exec
insert into test (id, title) values (?, trim(@title))
`

func (q *Queries) InsertTestError(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, insertTestError, id)
	return err
}
```

### Database schema

```sql
create table if not exists test (
  id varchar(64) not null primary key default (uuid()),
  title varchar(128) not null unique
);
```

### SQL queries

```sql
-- name: InsertTestError :exec
insert into test (id, title) values (?, trim(@title));

-- name: InsertTestOK :exec
insert into test (id, title) values (?, trim(sqlc.arg(title)));
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/a6348f88b56ca2a16d0f64c28ae79502916984896ce621f3bede088ef914bfe7

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
