### ISSUE TITLE
Unable to generate code when using SQLite with LEFT JOIN

### ISSUE THREAD

**Issue by zasdaym** [sqlc-dev/sqlc#1994]
### Version

Other

### What happened?

`sqlc generate` failed when using the described schema and query. The version used is v1.16.0.

### Relevant log output

```shell
column reference "id" not found
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS links (
    id TEXT PRIMARY KEY,
    destination TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS visits (
    id TEXT PRIMARY KEY,
    link_id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (link_id) REFERENCES links(id)
);
```

### SQL queries

```sql
-- name: GetLinks :many
SELECT
    links.id,
    links.destination,
    links.created_at,
    links.updated_at,
    COUNT(visits.id) AS visits
FROM links LEFT JOIN visits ON links.id = visits.link_id
GROUP BY links.id;
```

### Configuration

```yaml
version: 2
sql:
  - engine: sqlite
    schema: internal/sqlite/schema.sql
    queries: internal/sqlite/queries.sql
    gen:
      go:
        package: sqlite
        out: internal/sqlite
```

### Playground URL

https://play.sqlc.dev/p/c8d3c10a1bb40e4c91484e3334f3ae33e7764a7f5e4ba6742c6842c4c13c5933

### What operating system are you using?

macOS

### What type of code are you generating?

Go
