### ISSUE TITLE
Column with alias "does not exist"

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [sqlc-dev/sqlc#2025]
### Version

1.16.0

### What happened?

When compiling a query with a column alias, sqlc complains that the column "does not exist"

### Relevant log output

```shell
docker run --rm --volume `pwd`:/src --workdir /src kjconroy/sqlc:1.16.0 compile
# package generated
internal/database/postgres/queries/webhooks/get_many.sql:16:2: column "filtered_count" does not exist
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS webhooks (
    "id" CHAR(27) NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "method" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL DEFAULT extract(epoch FROM NOW()),
    "last_updated_at" BIGINT DEFAULT NULL,
    "archived_at" BIGINT DEFAULT NULL,
    "belongs_to_household" CHAR(27) NOT NULL REFERENCES households("id") ON DELETE CASCADE
);

CREATE TYPE webhook_event AS ENUM (
    'webhook_created',
    'webhook_updated',
    'webhook_archived'
);

CREATE TABLE IF NOT EXISTS webhook_trigger_events (
    "id" CHAR(27) NOT NULL PRIMARY KEY,
    "trigger_event" webhook_event NOT NULL,
    "belongs_to_webhook" CHAR(27) NOT NULL REFERENCES webhooks("id") ON DELETE CASCADE,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "archived_at" TIMESTAMP WITH TIME ZONE,
    UNIQUE("trigger_event", "belongs_to_webhook")
);
```

### SQL queries

```sql
SELECT
	webhooks.id,
	webhooks.name,
	webhooks.content_type,
	webhooks.url,
	webhooks.method,
	webhook_trigger_events.id,
	webhook_trigger_events.trigger_event,
	webhook_trigger_events.belongs_to_webhook,
	webhook_trigger_events.created_at,
	webhook_trigger_events.archived_at,
	webhooks.created_at,
	webhooks.last_updated_at,
	webhooks.archived_at,
	webhooks.belongs_to_household,
	(
	    SELECT
	        COUNT(webhooks.id)
	    FROM
	        webhooks
	    WHERE
	        webhooks.archived_at IS NULL
	      AND webhooks.created_at > COALESCE($2, (SELECT NOW() - interval '999 years'))
	      AND webhooks.created_at < COALESCE($3, (SELECT NOW() + interval '999 years'))
	      AND (
	            webhooks.last_updated_at IS NULL
	            OR webhooks.last_updated_at > COALESCE($4, (SELECT NOW() - interval '999 years'))
	        )
	      AND (
	            webhooks.last_updated_at IS NULL
	            OR webhooks.last_updated_at < COALESCE($5, (SELECT NOW() + interval '999 years'))
	        )
	    OFFSET COALESCE($6, 0)
	) as filtered_count,
	(
	    SELECT
	        COUNT(webhooks.id)
	    FROM
	        webhooks
	    WHERE
	        webhooks.archived_at IS NULL
	) as total_count
FROM
	webhook_trigger_events
	    JOIN webhooks ON webhook_trigger_events.belongs_to_webhook = webhooks.id
WHERE
	webhooks.archived_at IS NULL
	AND webhook_trigger_events.archived_at IS NULL
	AND webhooks.created_at > COALESCE($2, (SELECT NOW() - interval '999 years'))
	AND webhooks.created_at < COALESCE($3, (SELECT NOW() + interval '999 years'))
	AND (
	    webhooks.last_updated_at IS NULL
	    OR webhooks.last_updated_at > COALESCE($4, (SELECT NOW() - interval '999 years'))
	)
	AND (
	    webhooks.last_updated_at IS NULL
	    OR webhooks.last_updated_at < COALESCE($5, (SELECT NOW() + interval '999 years'))
	)
	AND webhooks.belongs_to_household = $1
	OFFSET COALESCE($6, 0);
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "internal/database/postgres/migrations"
    queries:
      - "internal/database/postgres/queries/webhooks"
    engine: "postgresql"
    # strict_function_checks: true
    gen:
      go:
        package: "generated"
        sql_package: "database/sql"
        out: "internal/database/postgres/generated"
        output_files_suffix: "_generated"
        emit_db_tags: true
        emit_prepared_queries: false
        emit_interface: true
        emit_exact_table_names: true
        emit_empty_slices: true
        emit_exported_queries: true
        emit_json_tags: false
        emit_result_struct_pointers: true
        emit_params_struct_pointers: true
        emit_methods_with_db_argument: true
        emit_enum_valid_method: true
        emit_all_enum_values: false
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
