### ISSUE TITLE
Can't construct query to add item to postgres enum

### ISSUE THREAD

**Issue by coolaj86** [sqlc-dev/sqlc#2059]
### Version

1.16.0

### What happened?

I tried to construct a query to add an enum to the database, and it failed.

### Relevant log output

```shell
sql/queries/record_types.sql:1:1: syntax error at or near "$1"
```

### Database schema

```sql
`migrations/20220422151655_-0600_recordtype.up.sql`:

CREATE TYPE record_type AS ENUM (
       'record'
);
```

### SQL queries

```sql
`sql/queries/record_types.sql`:

-- name: AddRecordType :exec
-- See <https://www.postgresql.org/docs/current/sql-altertype.html>.
ALTER TYPE record_type ADD VALUE IF NOT EXISTS $1
```

### Configuration

```yaml
`build.go`:

//go:generate go run -mod=vendor github.com/kyleconroy/sqlc/cmd/sqlc generate


```yaml
version: 1
packages:
  - path: "reportsv2"
    name: "reportsv2"
    engine: "postgresql"
    sql_package: "pgx/v4"
    schema: "./migrations/"
    queries: "./sql/queries/"
    emit_json_tags: true
    json_tags_case_style: "snake"
```
```


### Playground URL

_No response_

### What operating system are you using?

_No response_

### What database engines are you using?

_No response_

### What type of code are you generating?

_No response_
