### ISSUE TITLE
Column does not exist with sqlite engine

### ISSUE THREAD

**Issue by mgholam** [sqlc-dev/sqlc#2120]
### Version

Other

### What happened?

generate gives the following error on `v1.17.2`:
```
$ tools/sqlc generate
# package db
src/query.sql:20:1: column "CustomerName" does not exist
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS contacts (
	pid	TEXT PRIMARY KEY,
	CustomerName	TEXT,
	CustomerGuid	TEXT,
	ProjectName	TEXT,
	ProjectGuid	TEXT,
	FirstName	TEXT,
	LastName	TEXT,
	Position	TEXT,
	Mobile	TEXT,
	Mobile2	TEXT,
	Phone	TEXT,
	Email	TEXT,
	Fax	TEXT,
	Comment	TEXT,
	isDeleted	INTEGER DEFAULT 0
);
```

### SQL queries

```sql
-- name: InsertContact :one
INSERT INTO contacts (
pid,
CustomerName,
CustomerGuid,
ProjectName,
ProjectGuid,
FirstName,
LastName,
Position,
Mobile,
Mobile2,
Phone,
Email,
Fax,
Comment
)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
RETURNING *;


-- name: GetContacts :many
select * from contacts
```

### Configuration

```yaml
{
    "version": "1",
    "packages": [
      {
        "path": "db",
        "engine": "sqlite",
        "schema": "src/query.sql",
        "queries": "src/query.sql"
      }
    ]
  }
```

### Playground URL

https://play.sqlc.dev/p/1f226b2bec6aa236e58bd8acd704e3fb73f32da225f9fa1e677faf760f80030f

### What operating system are you using?

Linux

### What type of code are you generating?

Go
