### ISSUE TITLE
Struct representing return type of a select query not generated

### ISSUE THREAD

**Issue by Archisman-Mridha** [sqlc-dev/sqlc#2127]
### Version

1.16.0

### What happened?

I have this postgresql query -
```sql
SELECT (email, username) FROM users
    WHERE users.email= @email OR users.username= @username
        LIMIT 1;
```
and I am trying to generate GoLang code.

sqlc doesn't generate a struct representing `(email, username)`. Instead, it just creates `interface{ }`.

### Database schema

```sql
CREATE TABLE users (
    id SERIAL PRIMARY KEY,

    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL
);
```

### SQL queries

```sql
SELECT (email, username) FROM users
    WHERE users.email= @email OR users.username= @username
        LIMIT 1;
```

### Configuration

```yaml
version: "2"

sql:
    - engine: postgresql
      queries: ./sql/queries.sql
      schema: ./sql/schema.sql
      gen:
        go:
            package: sqlc
            out: ./generated/sqlc
            emit_interface: true
```

### Playground URL

https://play.sqlc.dev/p/0210bd42a17a0804f628d75bd58e69757e9be888a4f9ed713f8acaaa1cbd49d3

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
