### ISSUE TITLE
Overrides per-column are not respected when using the sqlite driver

### ISSUE THREAD

**Issue by ajp2455** [sqlc-dev/sqlc#2128]
### Version

1.17.2

### What happened?

When using `sqlc` to generate code, I listed an override for a column in my database. This override wasn't respected when using the sqlite driver. Using the `postgresql` driver, the override was respected. Additionally, overrides based on the DB type worked with the sqlite driver. It is just per-column overrides, when using the sqlite driver, that don't work.

It looks like sqlite support is in beta, and this isn't a huge deal, but figured I'd file a bug regardless.

Thank you!

### Database schema

```sql
CREATE TABLE IF NOT EXISTS examples (
  id TEXT PRIMARY KEY
);
```

### SQL queries

```sql
-- name: CreateExample :one
INSERT INTO examples (
  id
) VALUES (
  ?
)
RETURNING *;
```

### Configuration

```yaml
version: 2
sql:
  - engine: "sqlite"
    schema: "db/schema.sql"
    queries: "db/query.sql"
    gen:
      go:
        package: "db"
        out: "db"
        overrides:
          - column: "examples.id"
            go_type: "github.com/google/uuid.UUID"
```

### Playground URL

https://play.sqlc.dev/p/7820b713a02c0a9c83b4b2e7bd42039a84ef1ce1fd6903a5e53a65c3fe0acc79

### What operating system are you using?

Linux

### What database engines are you using?

sqlite

### What type of code are you generating?

Go
