### ISSUE TITLE
Enum renaming

### ISSUE THREAD

**Issue by marlongerson** [sqlc-dev/sqlc#2129]
### What do you want to change?

Can we add support for renaming generated name of enum values (similar to struct renames)? For example, add a setting in the config:

```
...
  rename_enum:
    spotify_url: "SpotifyURL"
    youtube_url: "YouTubeURL"
```

```sql
CREATE TYPE url AS ENUM(
    'spotify_url',
    'youtube_url'
    ...
);
```

With the above config this feature will generate the following:

```
const (
    SpotifyURL Url = "spotify_url"
    YouTubeURL Url = "youtube_url"
    ...
)
```
