### ISSUE TITLE
sqlc generated enum type not support in pgx query

### ISSUE THREAD

**Issue by fantacymaker** [sqlc-dev/sqlc#2144]
### Version

1.17.2

### What happened?

enum type should `RegisterType` before `Query` in pgx, but generated func not.  see [this issue](https://github.com/jackc/pgx/issues/1549)

### Database schema

```sql
CREATE TYPE level AS ENUM (
    'low',
    'middle',
    'high'
    );

CREATE TABLE authors
(
    id    BIGSERIAL PRIMARY KEY,
    name  text    NOT NULL,
    bio   text,
    level level   not null default 'low',
    age   integer not null default 18
);
```

### SQL queries

```sql
-- name: ListAuthors :many
SELECT *
FROM authors
WHERE name like @name
  and level = ANY (@level::level[])
ORDER BY id LIMIT $1
OFFSET $2;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "repository"
        out: "../"
        sql_package: "pgx/v5"
        emit_json_tags: true
```

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
