### ISSUE TITLE
Column does not exist when using query alias inside subquery

### ISSUE THREAD

**Issue by jamesleeht** [sqlc-dev/sqlc#2167]
### Version

1.17.2

### What happened?

It seems like sqlc is unable to generate the code for the query below even though it runs fine on Postgres. Might be a parsing issue.

### Relevant log output

```shell
query.sql:7:37: column "height" does not exist
```

### Database schema

```sql
CREATE TABLE public."user" (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    bio text
);

CREATE TABLE public.user_measurements (
    user_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    height real,
    ptp real,
    waist real,
    hip real,
    usual_uk_size smallint
);
```

### SQL queries

```sql
SELECT u.id, u.username, u.email, u.bio,
(SELECT row_to_json(r) FROM (SELECT m.height, m.ptp, m.waist, m.hip, m.usual_uk_size WHERE m.user_id=u.id) AS r) AS measurements
FROM "user" AS u
LEFT JOIN user_measurements AS m ON m.user_id=u.id
GROUP BY u.id, m.user_id;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        sql_package: "pgx/v5"
        package: "sqlc"
        out: "../../db/sqlc"
        emit_pointers_for_null_types: true
```

### Playground URL

https://play.sqlc.dev/p/9379c132cfe6b9cecdc75cd72b2078ca562e3fd880c2e9e3a7c3530afb1dc855

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
