### ISSUE TITLE
the PostgreSQL engine requires cgo. Please set CGO_ENABLED=1.

### ISSUE THREAD

**Issue by arlanram** [sqlc-dev/sqlc#2213]
### Version

1.17.2

### What happened?

when trying to use sqlc with pgx v5 and Fiber:

```
go 1.20

require (
	github.com/gofiber/fiber/v2 v2.43.0
	github.com/jackc/pgx/v5 v5.3.1
)
```

then running in terminal:

`sqlc generate --experimental`

### Relevant log output

```shell
the PostgreSQL engine requires cgo. Please set CGO_ENABLED=1.
```

### Database schema

```sql
no schema
```

### SQL queries

```sql
CREATE TABLE authors (
                         id   BIGSERIAL PRIMARY KEY,
                         name text      NOT NULL,
                         bio  text
);

-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $1 LIMIT 1;

-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;

-- name: CreateAuthor :one
INSERT INTO authors (
    name, bio
) VALUES (
             $1, $2
         )
RETURNING *;

-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "query.sql"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v5"
        out: "db"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
