### ISSUE TITLE
Python Plugin

### ISSUE THREAD

**Issue by trevatk** [sqlc-dev/sqlc#2248]
### Version

Other

### What happened?
```bash
# package py
error generating code: loadModule: define wasi: failed to parse WebAssembly module

Caused by:
    Invalid input WebAssembly code at offset 0: magic header not detected: bad magic number

```

### Configuration

```yaml
version: '2'
plugins:
  - name: py
    wasm:
      url: https://github.com/tabbed/sqlc-gen-python/releases/download/v0.16.0-alpha/sqlc-gen-python.wasm
      sha256: 
sql:
  - schema: "sqlc/schema/schema.sql"
    queries: "sqlc/queries"
    engine: "postgresql"
    codegen:
      - out: src/communities
        plugin: py
        options:
          package: communities
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Python
