### ISSUE TITLE
sqlite: Quoted tables generate invalid code

### ISSUE THREAD

**Issue by kyleconroy** [sqlc-dev/sqlc#2311]
### Version

v1.18.0

### What happened?

Queries on tables with dashes (and other characters that require quotes) generates invalid Go code.

### Relevant log output

```shell
sqlc generate failed.

# package db
error generating code: source error: 20:6: expected 'IDENT', found "Foo-Bar"
```

### Database schema

```sql
CREATE TABLE "foo-bar" (
  name text      NOT NULL
);
```

### SQL queries

```sql
-- name: ListFooBar :many
SELECT * FROM "foo-bar";
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "sqlite",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/d99fe3b457f038006ef8c8c29b22c60edab178dc9e83e5cddac4408c9cbe696c

### What operating system are you using?

macOS

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
