### ISSUE TITLE
sqlc.narg is not being added to parms

### ISSUE THREAD

**Issue by k1ng440** [sqlc-dev/sqlc#2324]
### Version

1.18.0

### What happened?

A field should be added to params but it does not

### Relevant log output

```shell
const productListByOwner = `-- name: ProductListByOwner :many
SELECT id, owner_id, created_by, name, slug, category_id, vendor_id, tags, created_at, updated_at, published_at, deleted_at
FROM products
WHERE owner_id = $1
AND (deleted_at IS NOT NULL OR $4 IS NULL)
ORDER BY id ASC
LIMIT $2 OFFSET $3
`

type ProductListByOwnerParams struct {
	OwnerID int32
	Limit   int32
	Offset  int32
}

func (q *Queries) ProductListByOwner(ctx context.Context, arg *ProductListByOwnerParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, productListByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

### Database schema

```sql
CREATE TABLE products
(
    id           SERIAL PRIMARY KEY,
    owner_id     INT NOT NULL,
    created_by   INT  NOT NULL,
    name         VARCHAR(100)               NOT NULL,
    slug         VARCHAR(255)               NOT NULL,
    created_at   TIMESTAMP                  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP                  NOT NULL DEFAULT NOW(),
    published_at TIMESTAMP,
    deleted_at   TIMESTAMP
);
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "internal/db/query.sql"
    schema: "internal/db/schema.sql"
    gen:
      go:
        package: "db"
        out: "internal/db"
        emit_params_struct_pointers: true
```

### Playground URL

https://play.sqlc.dev/p/f2ae3b0558f20a7040d2aeb039f30d7c797b51fe6b2c67fcdc3522d838024a24

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
