### ISSUE TITLE
Generated `copyfrom.go` file doesn't include the `output_files_suffix`.

### ISSUE THREAD

**Issue by optimality** [sqlc-dev/sqlc#2337]
### Version

1.18.0

### What happened?

I have `sql.gen.go.output_files_suffix` set to `.gen` in my `sqlc.yaml` file, but the generated `copyfrom.go` doesn't include the suffix.  This makes it appear as if it's a human-created file.

### Configuration

```yaml
version: 2
sql:
  - schema: migrations
    queries: queries
    engine: postgresql
    gen:
      go:
        out: queries
        emit_interface: true
        output_files_suffix: .gen
        output_db_file_name: db.gen.go
        output_models_file_name: models.gen.go
        output_querier_file_name: querier.gen.go
        sql_package: pgx/v4
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
