### ISSUE TITLE
Repository pattern and SQLC

### ISSUE THREAD

**Issue by ak-karimzai** [sqlc-dev/sqlc#2469]
### What do you want to change?

its possible to use repository pattern and generate golang code for each entity independently? i mean that i don't want to be all my entity function will be in one interface 

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by abh** [comment]
In 1.19 you can use `omit_unused_structs` in the configuration file and then generate different packages for each subset of queries you are doing.

```
    gen:
      go:
        omit_unused_structs: true
```

**Comment by ak-karimzai** [comment]
i added this configs in .yaml file and regenerated code is same as previous

**Comment by ak-karimzai** [comment]
installed sqlc version in my machine is 1.19.1

**Comment by fnsne** [comment]
I use different sql statement in sqlc.yaml that target to different queries and out.
for example
```
version: "2"
sql:
  - engine: "postgresql"
    queries: "src/services/author/query.sql"
    schema: "tables"
    gen:
      go:
        sql_package: "pgx/v5" 
        out: "src/services/author"
  - engine: "postgresql"
    queries: "src/services/book/query.sql"
    schema: "tables"
    gen:
      go:
        sql_package: "pgx/v5" 
        out: "src/services/book"
```
By doing that, I can seperate `author` and `book` access entry to the Queries of different package.

Maybe there will be problem when there are more than one repo in same package.
