### ISSUE TITLE
SQLite: column alias not recognized without AS

### ISSUE THREAD

**Issue by orisano** [sqlc-dev/sqlc#2559]
### Version

1.20.0

### What happened?

Column alias is not recognized in SQLite if AS is not specified.

```sql
-- name: Value :one
SELECT 1 x, 2 y;
```

expected:
```go
type ValueRow struct {
	X int64
	Y int64
}
```

actual:
```go
type ValueRow struct {
	Column1 int64
	Column2 int64
}
```

It works well with the following.
```sql
-- name: Value :one
SELECT 1 AS x, 2 AS y;
```

### SQL queries

```sql
SELECT 1 x, 2 y;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "sqlite",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/7230cad224088b2a31b97ef4e18fb5dfd470a234376892879d46b5d19fd4d098

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
