### ISSUE TITLE
`select *` from a subquery selects all columns for all tables in the subquery

### ISSUE THREAD

**Issue by JakeCapra** [sqlc-dev/sqlc#2569]
### Version

1.20.0

### What happened?

When selecting `*` from a subquery, the generated query selects all columns from all tables referenced in the subquery, not all fields selected by the subquery. 

With the example provided below, the following query is generated:
```sql
SELECT t.id, authors.id, name, bio FROM (select id from authors) t
```

The generated query should be:
```sql
SELECT t.id FROM (select id from authors) t
```

If you modify the query to be:
```sql
SELECT t.* FROM (select id from authors) t;
```
then the generated query is correct.

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
SELECT * FROM (select id from authors) t;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/40aa4c5ab1bd5efb90024e9b35a08cdc83d28237ba2bfdc2f3ecf4ec47da4c68

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
