### ISSUE TITLE
Column expansion for quoted non-keyword identifier table does not work well

### ISSUE THREAD

**Issue by orisano** [sqlc-dev/sqlc#2575]
### Version

1.20.0

### What happened?

Column expansion for quoted non-keyword identifier table does not work well.

input:
```sql
SELECT "t".* FROM foo "t";
```
output:
```sql
SELECT t.c.* FROM t "t";
```

expected:
```sql
SELECT t.c FROM t "t";
```
or
```sql
SELECT "t".c FROM t "t";
```

### Database schema

```sql
CREATE TABLE t (
  c BIGSERIAL PRIMARY KEY
);
```

### SQL queries

```sql
-- name: Get :one
SELECT "t".* FROM t "t";
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/5532492abf710a8a93ef6fcd72236d0166347c85315ef11da8fcd3a12d67c7f9
