### ISSUE TITLE
There is no response after starting the program.

### ISSUE THREAD

**Issue by renjunok** [sqlc-dev/sqlc#2577]
### Version

1.20.0

### What happened?

Nothing happens after starting the program, and the program cannot enter the working state.

### Relevant log output

```shell
no response
```

### Database schema

```sql
create table test
(
    code        varchar(5)             not null,
    status      smallint     default 0 not null
);

create unique index test_code_uindex
    on test (code);
```

### SQL queries

```sql
-- name: CreateTest :exec
INSERT INTO test (code, status)
VALUES ($1, $2);
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "db/schema.sql"
    queries: "db/query.sql"
    engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "db/sqlc"
        emit_json_tags: true
        emit_prepared_queries: true
        emit_interface: false
        emit_exact_table_names: false
```

### Playground URL

https://play.sqlc.dev/p/6ec49fdf5e5d081bc622550d9cb1a8f94792c1773e58421c73d6e344389a1d7f

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
