### ISSUE TITLE
query names and parameter names can collide

### ISSUE THREAD

**Issue by andrewmbenton** [sqlc-dev/sqlc#2585]
### Version

1.20.0

### What happened?

From this Discord conversation: https://discord.com/channels/946447283321438248/1138152594947199067

`sqlc` will generate a string constant for each query, and the name of the constant is based on the configured query name. This name can collide with the names `sqlc` chooses for query parameters in some circumstances, causing compilation and runtime errors.

### SQL queries

```sql
-- name: ABS :one
SELECT abs($1);
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/4803994315dd127f8cfd2024235a0de1da95f344f0b3f2d3bb612fe4031c1bff

### What operating system are you using?

Linux

### What type of code are you generating?

Go
