### ISSUE TITLE
emit_pointers_for_null_types does not work on default 'database/sql' go package

### ISSUE THREAD

**Issue by loicbefve** [sqlc-dev/sqlc#2589]
### Version

1.20.0

### What happened?

While generating the go queries using the `emit_pointers_for_null_types` flag in a configuration file v2 nothing append and database/sql nullable types are used instead.
I think I've found where in the code that might happen and will propose a fix alongside this issue.
Thanks for reading me.

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "../database/schema/1.2.9.sql"
    gen:
      go:
        emit_interface: true
        emit_enum_valid_method: true
        emit_all_enum_values: true
        emit_pointers_for_null_types: true
        package: "database_sqlc"
        out: "."
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
