### ISSUE TITLE
Nullable numeric columns turned into sql.NullString

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [sqlc-dev/sqlc#2637]
### Version

1.20.0

### What happened?

I have a table with a column that is of type `NUMERIC(14,2)` and allowed to be `NULL`. Ideally, this would result in sqlc generating query params/results that use `sql.NullFloat64`, but it almost always results in a `sql.NullString`, which is kind of useless for my particular use case. I can get it to be a plain `float64` if I cast the columns to `::float`, but then I get errors about loading null values into non-pointered floats when I make queries.

### Relevant log output

```shell
n/a
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS valid_ingredients (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    minimum_ideal_storage_temperature_in_celsius NUMERIC(14,2),
    maximum_ideal_storage_temperature_in_celsius NUMERIC(14,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    last_updated_at TIMESTAMP WITH TIME ZONE,
    archived_at TIMESTAMP WITH TIME ZONE
);
```

### SQL queries

```sql
CREATE TABLE IF NOT EXISTS valid_ingredients (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    minimum_ideal_storage_temperature_in_celsius NUMERIC(14,2),
    maximum_ideal_storage_temperature_in_celsius NUMERIC(14,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    last_updated_at TIMESTAMP WITH TIME ZONE,
    archived_at TIMESTAMP WITH TIME ZONE
);
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    strict_function_checks: true
    gen:
      go:
        package: "generated"
        out: "internal/database/postgres/generated"
        sql_package: "pgx/v5/stdlib"
        emit_db_tags: false
        emit_prepared_queries: false
        emit_interface: true
        emit_exact_table_names: true
        emit_empty_slices: true
        emit_exported_queries: false
        emit_json_tags: false
        emit_params_struct_pointers: true
        emit_result_struct_pointers: true
        emit_methods_with_db_argument: true
        emit_enum_valid_method: true
        emit_all_enum_values: true
        json_tags_id_uppercase: true
        json_tags_case_style: "camel"
        omit_unused_structs: true
        output_batch_file_name: "batch.go"
        output_db_file_name: "db.go"
        output_models_file_name: "models.go"
        output_querier_file_name: "querier.go"
        output_files_suffix: "_generated"
        query_parameter_limit: 1
        rename:
          url: "URL"
        overrides:
          - db_type: "valid_ingredients.minimum_ideal_storage_temperature_in_celsius"
            go_type: "database/sql.NullFloat64"
            nullable: true
          - db_type: "valid_ingredients.maximum_ideal_storage_temperature_in_celsius"
            go_type: "database/sql.NullFloat64"
            nullable: true
```

### Playground URL

https://play.sqlc.dev/p/18fb569c5fc5a4b0d9d26f78835b14486c6bda18530ad12cca051a4e3a4e346f

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
