### ISSUE TITLE
Name in sqlc.embed() is not following the right pattern

### ISSUE THREAD

**Issue by KevenGoncalves** [sqlc-dev/sqlc#2645]
### Version

1.20.0

### What happened?

I have a query with sqlc.embed(role) to generate an embed struct inside another bug the name is not following the camelcase pattern:

the name expected would be driveLicense not drivelicense

```go
type GetEmployeeRow struct {
	ID           uuid.UUID    `json:"id"`
	FirstName    string       `json:"firstName"`
	LastName     string       `json:"lastName"`
	Birthdate    time.Time    `json:"birthdate"`
	Email        *string      `json:"email"`
	PhoneNumber  string       `json:"phoneNumber"`
	ImageUrl     *string      `json:"imageUrl"`
	State        bool         `json:"state"`
	Role         Role         `json:"role"`
	DriveLicense DriveLicense `json:"drivelicense"`
}
```

### SQL queries

```sql
-- name: GetEmployee :one
SELECT
  employee.id,
  employee.first_name,
  employee.last_name,
  employee.birthdate,
  employee.email,
  employee.phone_number,
  employee.image_url,
  employee.state,
  sqlc.embed(role),
  sqlc.embed(drive_license)
FROM employee 
LEFT JOIN role ON employee.role_id = role.id
LEFT JOIN drive_license ON employee.drive_license_id = drive_license.id
WHERE employee.id = $1 AND employee.deleted_at IS NULL LIMIT 1;
```

### Configuration

```yaml
---
version: "2"
sql:
  - engine: "postgresql"
    queries: "internal/databases/postgres/queries"
    schema: "internal/databases/postgres/migrations"
    gen:
      go:
        out: "internal/databases/postgres/sqlc"
        emit_json_tags: true
        json_tags_case_style: "camel"
        overrides:
          - db_type: "pg_catalog.varchar"
            go_type:
              type: "string"
              pointer: true
            nullable: true
          - db_type: "pg_catalog.text"
            go_type:
              type: "string"
              pointer: true
            nullable: true
          - column: "*.created_at"
            go_struct_tag: json:"-"
          - column: "*.updated_at"
            go_struct_tag: json:"-"
          - column: "*.deleted_at"
            go_struct_tag: json:"-"

```

### What operating system are you using?

MacOS 13.4 Ventura

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
