### ISSUE TITLE
Wierd field name when using function.

### ISSUE THREAD

**Issue by aca** [sqlc-dev/sqlc#2647]
### Version

1.20.0

### What happened?

Generated query. GetAuthorParams should have field `Name` not `Rpad`.

```
const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors WHERE name = RPAD($1,32) and bio = $2 LIMIT 1`

type GetAuthorParams struct {
	Rpad string
	Bio  sql.NullString
}
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors WHERE name = RPAD($1,32) and bio = $2 LIMIT 1;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/0ae261035f076a2afc9f7cb89cdacad020b8c6cb3a408963b9d579475a03cb82

### What operating system are you using?

Linux, Windows, macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
