### ISSUE TITLE
Support YAML anchors in sqlc.yaml

### ISSUE THREAD

**Issue by kevinvalk** [sqlc-dev/sqlc#2653]
### What do you want to change?

Currently I am working on a microservices project using SQLC. All is fine, but I find myself repeating the same configuration options for each codegen section. Using [YAML anchors](https://yaml.org/spec/1.2.2/#3222-anchors-and-aliases) this would be trivial and very nice, but this is currently not supported.

Then I could do something like the following.
```yaml
sql:
  - schema: database
    queries: services/a
    engine: postgresql
    codegen:
      - out: gateway/src/gateway/services/organization
        plugin: py
        options: &base-options
          query_parameter_limit: 1
          package: gateway
          output_models_file_name: null
          emit_module: true
          emit_generators: false
          emit_async: true

  - schema: database
    queries: services/b
    engine: postgresql
    codegen:
      - out: gateway/src/gateway/services/project
        plugin: py
        options: *base-options

```

https://play.sqlc.dev/p/32c6b52785ce13ddfeb2311a2a835800d2578b56bf1addd95887e3fe45d2ace0

**Comment by kyleconroy** [comment]
We parse YAML using https://github.com/go-yaml/yaml which has support for anchors. You can see a working example [here](https://play.sqlc.dev/p/2caa6715bf6c76ad30759263e4069f754ef3ec7a292d5404ef17b8c3aa5c5149).

```yaml
version: "2"
sql:
- schema: "query.sql"
  queries: "query.sql"
  engine: "postgresql"
  gen:
    go: 
      package: "authors"
      out: "postgresql"
  database:
    uri: "postgresql://postgres:postgres@localhost:5432/postgres"
  rules: &base-rules
    - sqlc/db-prepare
- schema: "query.sql"
  queries: "query.sql"
  engine: "postgresql"
  gen:
    go:
      package: "authors"
      out: "mysql"
  rules: *base-rules
```

The bug you're seeing is due to how the plugin system serializes options. I've updated this issue to be a bug report.
