### ISSUE TITLE
Generating field that does not implements Value/Scan

### ISSUE THREAD

**Issue by souzajunior** [sqlc-dev/sqlc#2654]
### Version

1.20.0

### What happened?

sqlc is generating Go type `netip.Addr` for database type `INET` (_postgres_), which `netip.Addr` doesn't implements `Value/Scan`. I'm using **pgx/v5**. 

I think the correct type for `INET` using **pgx/v5** is `pgtype.InetCodec`, maybe?

### Database schema

```sql
CREATE TABLE public.t_foo
(
   field_issue INET NOT NULL
);
```

### Configuration

```yaml
version: "2"
sql:
- schema: "../schema.sql"
  queries: "queries.sql"
  engine: "postgresql"
  gen:
    go:
      # Cfg
      out: ".."
      package: "issue"
      sql_package: "pgx/v5"

      # Emit
      emit_interface: true

      # Output
      output_files_suffix: _gen
      output_db_file_name: db_gen.go
      output_models_file_name: models_gen.go
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
