### ISSUE TITLE
Schema:  NUMERIC NOT NULL DEFAULT 1   is converted to string not number

### ISSUE THREAD

**Issue by youngjun827** [sqlc-dev/sqlc#2656]
### Version

Other

### What happened?

When I write a schema with " NUMERIC NOT NULL DEFAULT 1 " This returns a Golang file with a structure that has a type string. Why is this happening and how can I fix this issue?

### Relevant log output

```shell
type CreateHotdogsParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       string `json:"price"`
	Image       []byte `json:"image"`
}
```

### Database schema

```sql
CREATE TABLE "hotdogs" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" VARCHAR(21) NOT NULL,
  "description" TEXT NOT NULL,
  "price" NUMERIC NOT NULL DEFAULT 1,
  "image" BYTEA NOT NULL
);
```

### SQL queries

```sql
-- name: CreateHotdogs :one
INSERT INTO hotdogs (
    name, 
    description, 
    price, 
    image
) VALUES (
    $1, 
    $2, 
    $3, 
    $4
)
RETURNING *;


-- name: ListHotdogs :many
SELECT * FROM hotdogs
ORDER BY id;


-- name: DeleteHotdogs :exec
DELETE FROM hotdogs
WHERE id = $1;
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    path: "./db/sqlc"
    queries: "./db/query"
    schema: "./db/migration"
    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: false
    emit_exact_table_names: true
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
