### ISSUE TITLE
SQLC Generated Go Code Throws Scan Error for Non-Existent user_id

### ISSUE THREAD

**Issue by qcrao** [sqlc-dev/sqlc#2677]
### Version

1.20.0

### What happened?

I am using SQLC to generate Go code for my SQL queries. I have defined the following SQL statement:

```sql
-- name: GetUserDepositCountBetween :one
SELECT user_id, COUNT(*) AS deposit_count FROM transaction WHERE user_id = ? and type = 'deposit' and created_at >= sqlc.arg(start) AND created_at < sqlc.arg(end);
```

When executing the generated Go code, I encounter an error if the `user_id` is not found in the database. The error message is:

```
"error":"sql: Scan error on column index 0, name \"user_id\": converting NULL to int64 is unsupported"
```

This makes it difficult for me to distinguish between a timeout error and a "record not found" error.

### Relevant log output

```shell
error message: "error":"sql: Scan error on column index 0, name \"user_id\": converting NULL to int64 is unsupported"
```

### SQL queries

```sql
-- name: GetUserDepositCountBetween :one
SELECT user_id, COUNT(*) AS deposit_count FROM transaction WHERE user_id = ? and type = 'deposit' and created_at >= sqlc.arg(start) AND created_at < sqlc.arg(end);
```

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
We're going to need a bit more information to reproduce this. Can you please share the definition for the transaction table and your sqlc configuration file?

**Comment by qcrao** [comment]
@kyleconroy Certainly, here are the details you requested:

definition(simplified):
```sql
CREATE TABLE IF NOT EXISTS `transaction`
(
    `id`          BIGINT      NOT NULL AUTO_INCREMENT COMMENT 'id',
    `type`        VARCHAR(50) NOT NULL DEFAULT 'deposit' COMMENT '交易类型',
    `user_id`     BIGINT      NOT NULL DEFAULT 0 COMMENT '用户ID',
    `created_at`  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    KEY `type_idx` (`type`),
    KEY `user_id_idx` (`user_id`),
    KEY `created_at_idx` (`created_at`)
)
ENGINE = InnoDB
CHARSET = utf8mb4 COMMENT ='交易流水表';
```

sqlc configuration file:

```yaml
version: 1
packages:
  - path: "."
    name: "mysql"
    engine: "mysql"
    schema: "sql/schema/"
    queries: "sql"
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: false
    emit_exact_table_names: false
    emit_empty_slices: true
    overrides:
      - db_type: "decimal"
        go_type: "github.com/shopspring/decimal.Decimal"
```

generated code:
```go
const getUserDepositCountBetween = `-- name: GetUserDepositCountBetween :one
SELECT user_id, COUNT(*) AS deposit_count FROM transaction WHERE user_id = ? and type = 'deposit' and created_at >= ? AND created_at < ?
`

type GetUserDepositCountBetweenParams struct {
	UserID int64     `json:"user_id"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type GetUserDepositCountBetweenRow struct {
	UserID       int64 `json:"user_id"`
	DepositCount int64 `json:"deposit_count"`
}

func (q *Queries) GetUserDepositCountBetween(ctx context.Context, arg GetUserDepositCountBetweenParams) (GetUserDepositCountBetweenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserDepositCountBetween, arg.UserID, arg.Start, arg.End)
	var i GetUserDepositCountBetweenRow
	err := row.Scan(&i.UserID, &i.DepositCount)
	return i, err
}
```
