### ISSUE TITLE
Unused imports generated in querier interfaces.

### ISSUE THREAD

**Issue by coady** [sqlc-dev/sqlc#2707]
### Version

1.21.0

### What happened?

As of 1.21, querier interfaces are being generated with unused imports, breaking compilation. The configuration uses multiple packages, and of course `emit_interface`.

### Relevant log output

```shell
// Code generated by sqlc. DO NOT EDIT.
 // versions:
-//   sqlc v1.20.0
+//   sqlc v1.21.0
 
 package testutilsql
 
 import (
 	"context"
+	"database/sql"
+	"time"
 
 	"github.com/google/uuid"
 )
```

### Configuration

```yaml
- schema: "migrations"
  queries: "queries/testutil"
  engine: "postgresql"
  gen:
    go:
      out: "generated/testutilsql"
      emit_interface: true
```

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
