### ISSUE TITLE
Unable to use set returning functions in from clause with ordinality

### ISSUE THREAD

**Issue by Lay523** [sqlc-dev/sqlc#2731]
### Version

1.21.0

### What happened?

column  does not exist

### Relevant log output

```shell
column "item_object" does not exist
```

### SQL queries

```sql
SELECT code,arr.item_object->> 'code'  as resource_code
FROM sys_actions,
    jsonb_array_elements(resources) with ordinality arr(item_object, resource)
    WHERE item_object->>'resource' = sqlc.arg('resource')
    LIMIT 1;
```

### Configuration

```yaml
sql:
  - schema: "./sql/schema/"
    queries: "./sql/query/"
    engine: "postgresql"
    gen:
      go:
        package: "queries"
        out: "internal/data/queries"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_empty_slices: false
        emit_result_struct_pointers: true
        emit_exported_queries: true
        emit_methods_with_db_argument: false
        emit_pointers_for_null_types: true
```

### Playground URL

https://play.sqlc.dev/p/4b891b0542344db335f87e02995f28a3d2d98a0b6821747938ceecf73fc38a46
