### ISSUE TITLE
Invalid UUID type is generated when db column is declared with REFERENCES

### ISSUE THREAD

**Issue by dandee** [sqlc-dev/sqlc#2738]
### Version

1.21.0

### What happened?

sqlc with pgx/v5 and uuid type overriden by github.com/gofrs/uuid.UUID:

Structures and functions are generated with incorrect pgtype.UUID type for uuid columns annotated with REFERENCES keyword.

I expect the type to be uuid.UUID as requested:

```go
func (q *Queries) GetDistributor(ctx context.Context, userID uuid.UUID, iD uuid.UUID) (Distributor, error) {}
```

### Relevant log output

```go
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Distributor struct {
	ID        uuid.UUID          `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deletedAt"`
	UserID    pgtype.UUID        `json:"-"`
}

type User struct {
	ID uuid.UUID `json:"-"`
}
```

```go
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: query.sql

package db

import (
	"context"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDistributor = `-- name: GetDistributor :one
SELECT id, user_id
FROM distributors d
WHERE d.user_id = $1 AND id = $2 AND d.deleted_at IS NULL
`

func (q *Queries) GetDistributor(ctx context.Context, userID pgtype.UUID, iD uuid.UUID) (Distributor, error) {
	row := q.db.QueryRow(ctx, getDistributor, userID, iD)
	var i Distributor
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
```

### Database schema

```sql
CREATE TABLE users (
  id uuid PRIMARY KEY
);

CREATE TABLE distributors (
  id uuid PRIMARY KEY,
  deleted_at timestamp with time zone,
  user_id uuid REFERENCES users
);
```

### SQL queries

```sql
-- Example queries for sqlc
CREATE TABLE users (
  id uuid PRIMARY KEY
);

CREATE TABLE distributors (
  id uuid PRIMARY KEY,
  deleted_at timestamp with time zone,
  user_id uuid REFERENCES users
);

-- name: GetDistributor :one
SELECT *
FROM distributors d
WHERE d.user_id = $1 AND id = $2 AND d.deleted_at IS NULL;
```

### Configuration

```yaml
version: "2"
sql:
- engine: "postgresql"
  schema: "/"
  queries: "/"
  gen:
    go:
      sql_package: "pgx/v5"
      package: "db"
      out: "./"
      emit_json_tags: true
      emit_pointers_for_null_types: true
      json_tags_case_style: camel
      query_parameter_limit: 5
      overrides:
      - db_type: "uuid"
        go_type: "github.com/gofrs/uuid.UUID"
```

### Playground URL

https://play.sqlc.dev/p/9e6006530d91b4c02abb280f1683215ee1927049124a21e616399489f4353d98

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by andrewmbenton** [comment]
The issue here is not related to the `REFERENCES` constraint, but rather that `sqlc` treats nullable fields differently from not-nullable fields when considering overrides. You can either mark the `user_id` field as `NOT NULL` or you can add an additional override for the nullable type:

```yaml
version: "2"
sql:
- engine: "postgresql"
  schema: "/"
  queries: "/"
  gen:
    go:
      sql_package: "pgx/v5"
      package: "db"
      out: "./"
      emit_json_tags: true
      emit_pointers_for_null_types: true
      json_tags_case_style: camel
      query_parameter_limit: 5
      overrides:
      - db_type: "uuid"
        go_type: "github.com/gofrs/uuid.UUID"
      - db_type: "uuid"
        go_type: "github.com/gofrs/uuid.UUID"
        nullable: true
```

We should document this better in https://docs.sqlc.dev/en/stable/reference/config.html#type-overriding
