### ISSUE TITLE
bug: imports time in querier.go when inserting TIMESTAMP column

### ISSUE THREAD

**Issue by marmiha** [sqlc-dev/sqlc#2739]
### Version

1.21.0

### What happened?

Generating code with the given database schema the corresponding querier is generated as such:
``` go

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package repository

import (
	"context"
	"time"
)

type Querier interface {
	CreateTemporaryDoorLink(ctx context.Context, arg CreateTemporaryDoorLinkParams) (*TemporaryDoorLink, error)
}

var _ Querier = (*Queries)(nil)

```

where the `import time` is not used, resulting in unrunable code. I also use `golang-migrate`.

### Database schema

```sql
CREATE TABLE IF NOT EXISTS temporary_door_links (
    id SERIAL PRIMARY KEY,
    token VARCHAR(256) NOT NULL,
    expires_at TIMESTAMP NOT NULL DEFAULT 'now'::timestamp + '14 day'::interval, 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
```

### SQL queries

```sql
-- name: CreateTemporaryDoorLink :one
INSERT INTO temporary_door_links (
    token, max_uses, expires_at
) VALUES (
    $1, $2, $3
) RETURNING *;
```

### Configuration

```yaml
version: "2"
sql:
  - schema: ../../db/migrations
    queries: sqlc.queries.sql
    engine: postgresql
    database:
      uri: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/{DB_NAME}
    gen:
      go:
        package: repository
        out: .
        emit_db_tags: true
        emit_interface: true
        emit_json_tags: true
        emit_result_struct_pointers: true
        rename:
          id: "Id"
          account_id: "AccountId"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
