### ISSUE TITLE
Missing arguments in UPDATE

### ISSUE THREAD

**Issue by dmlambea** [sqlc-dev/sqlc#2754]
### Version

1.21.0

### What happened?

When writing an UPDATE query like:

```
UPDATE mytable SET
  name = slqc.arg('name')
WHERE code = sqlc.arg('code');
```
The only recognized parameter is the one in the WHERE clause.

### Relevant log output

```shell
Nothing relevant. Generation runs without errors.
```

### Database schema

```sql
create table mytable (
	code	       varchar(250) primary key,
	name	       varchar(250) not null,
    notes	       varchar(250) not null
);
```

### SQL queries

```sql
UPDATE mytable SET
  name = slqc.arg('name'),
  notes = slqc.arg('notes')
WHERE code = sqlc.arg('code');
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "query.sql"
    gen:
      go:
        package: "query"
        sql_package: "pgx/v5"
        out: "."
        emit_interface: true
        emit_pointers_for_null_types: true
```

### Playground URL

https://play.sqlc.dev/p/796e32f4c69f7b9d174731eb41f9de6e3e5151adf1c4b867698d75a90484e30e

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
