### ISSUE TITLE
Generate code with pgxV5 inet field type

### ISSUE THREAD

**Issue by mayken** [sqlc-dev/sqlc#2766]
### Version

1.21.0

### What happened?

A bug happened!

### Relevant log output

```shell
../../pkg/db/sqlc/querier.go:9:2: "net/netip" imported and not used
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS refresh_tokens (
    user_id bigint REFERENCES users(id) ON DELETE CASCADE,
    ip inet NOT NULL,
);
```

### Configuration

```yaml
version: "2"
sql:
- engine: "postgresql"
  queries: "./pkg/db/query"
  schema: "./pkg/db/migration"
  database:
    uri: "postgres://...."
  gen:
    go:
      package: "db"
      sql_package: "pgx/v5"
      out: "./pkg/db/sqlc"
      emit_json_tags: true
      emit_interface: true
      emit_empty_slices: true
      overrides:
        - db_type: "timestamptz"
          go_type: "time.Time"
        - db_type: "uuid"
          go_type: "github.com/google/uuid.UUID"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
