### ISSUE TITLE
MySQL 8.0.19+ ... AS alias ... ON DUPLICATE KEY syntax parsing problem

### ISSUE THREAD

**Issue by jessepeterson** [sqlc-dev/sqlc#2789]
### Version

1.22.0

### What happened?

MySQL 8.0.19 deprecated the former ON DUPLICATE KEY syntax [for the newer column reference style](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html) but `sqlc` doesn't seem to like it.

### Relevant log output

```shell
$ sqlc generate
# package sqlc
query.sql:20:24: syntax error near "as new"
```

### Database schema

```sql
CREATE TABLE dep_names (
  mykey VARCHAR(255) NOT NULL,
  a VARCHAR(255) NULL,
  b VARCHAR(255) NULL,
  c VARCHAR(255) NULL,
  d VARCHAR(255) NULL,
  e VARCHAR(255) NULL,
  PRIMARY KEY (mykey)
);
```

### SQL queries

```sql
-- name: TestInsert :exec
INSERT INTO dep_names 
  (mykey, a, b, c, d, e)
VALUES 
  (?, ?, ?, ?, ?, ?) as new
ON DUPLICATE KEY UPDATE 
  a = new.a,
  b = new.b,
  c = new.c,
  d = new.d,
  e = new.e;
```

### Configuration

```yaml
version: 2
sql:
  - engine: "mysql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "sqlc"
        out: "sqlc"
```

### Playground URL

https://play.sqlc.dev/p/99bd4e6529ffaae574dacb08c653ada803cc5c95a4a42e795e4a39cb039a4a47

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
