### ISSUE TITLE
Unexpected struct name when a table name ends with 'data'

### ISSUE THREAD

**Issue by MathisRose** [sqlc-dev/sqlc#2820]
### Version

1.21.0

### What happened?

I created a table "userdata" in my sql script.

I expected a struct with the name "Userdata" in my generated models.go file. Instead I got a struct named "Userdatum".

This behaviour happens with any table that has a name ending in "data". 
The issue was solved by naming the table "userdata_" instead, as shown in the playground example.

### Relevant log output

```shell
No log output.
```

### Database schema

```sql
CREATE TABLE userdata
(
    external_id      text,
    PRIMARY KEY (external_id)
);
```

### SQL queries

```sql
No issues here.
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "sql/"
    schema: "sql/"
    gen:
      go:
        package: "gen"
        out: "gen"
```

### Playground URL

https://play.sqlc.dev/p/6e2bf09dceb25b5cc9f808e08b90aaf8ad896ce84b118f54b5ca01670a292c43

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
