### ISSUE TITLE
Invalid argument to sqlc.arg() when the argument is `user`

### ISSUE THREAD

**Issue by sgtsquiggs** [sqlc-dev/sqlc#2832]
### Version

1.21.0

### What happened?

Given:

schema.sql
```sql
create table "user_data" (
	"id" varchar not null,
	"user" varchar not null,
	primary key ("id")
);
```

queries.sql
```sql
-- name: StageUserData: copyfrom
insert into "user_data" ("id", "user")
values (sqlc.arg(id), sqlc.arg(user));

```

sqlc.yaml
```yaml
version: "2"
sql:
  - engine: "postgresql"
    schema: "schema.sql"
    queries: "queries.sql"
    gen:
      go:
        package: "models"
        sql_package: "pgx/v5"
        out: "models"
```

Execute:
```
❯ sqlc generate
# package models
queries.sql:1:1: Invalid argument to sqlc.arg()
```

### Relevant log output

```shell
# package models
queries.sql:1:1: Invalid argument to sqlc.arg()
```

### Database schema

```sql
create table "user_data" (
	"id" varchar not null,
	"user" varchar not null,
	primary key ("id")
);
```

### SQL queries

```sql
-- name: StageUserData: copyfrom
insert into "user_data" ("id", "user")
values (sqlc.arg(id), sqlc.arg(user));
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    schema: "schema.sql"
    queries: "queries.sql"
    gen:
      go:
        package: "models"
        sql_package: "pgx/v5"
        out: "models"
```

### Playground URL

https://play.sqlc.dev/p/0dc89e4177151eca415a86676469f9cef991c373455641ddbacef05abab3f265

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
