### ISSUE TITLE
Early access: managed databases and project uploads

### ISSUE THREAD

**Issue by kyleconroy** [sqlc-dev/sqlc#2842]
### Managed databases

We announced private access to [managed databases](https://sqlc.dev/posts/2023/09/25/v1.22.0-managed-databases/) a few weeks ago. Today we've opened them up for early access. Any one can [sign up](https://dashboard.sqlc.dev), create an access token, and start using managed databases in `sqlc vet`.

```yaml
version: '2'
cloud:
  project: '<PROJECT_ID>'
sql:
- schema: schema.sql
  queries: query.sql
  engine: postgresql
  database:
    managed: true
  rules:
  - sqlc/db-prepare
```

Read more in the [documentation](https://docs.sqlc.dev/en/latest/howto/managed-databases.html) or jump straight to signing up for [sqlc Cloud](https://dashboard.sqlc.dev).

### Project uploads

[Uploading an archive](https://docs.sqlc.dev/en/latest/howto/upload.html) of your project helps us catch issues early in the release process. Similar to Rust’s [crater](https://github.com/rust-lang/crater) project, uploaded archives are tested against development releases of sqlc to verify correctness.

By uploading your project, you’re making sqlc more stable and reliable. Thanks!

We've written a [guide](https://docs.sqlc.dev/en/latest/howto/ci-cd.html#upload) for uploading your project as part of your CI / CD workflow.
