### ISSUE TITLE
No parameter gets generated for CASE ? WHEN...

### ISSUE THREAD

**Issue by chowey** [sqlc-dev/sqlc#2847]
### Version

1.22.0

### What happened?

I use a CASE statement of the form `CASE ? WHEN true THEN '1' WHEN false THEN '0' ELSE NULL END`.

The generated Go function has no parameters for the `?`.

### Database schema

```sql
CREATE TABLE testing (
  id    int PRIMARY KEY,
  value text
);
```

### SQL queries

```sql
UPDATE testing
SET value = CASE ? WHEN true THEN 'Hello' WHEN false THEN 'Goodbye' ELSE value END;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/c6a70bea34b4e836d2cc998f885ae6c51d2234632ebe9de53865c23a68588dc6

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
