### ISSUE TITLE
Generate code with pgxV5 timestamp,time,date,timetz,timestamptx field type 

### ISSUE THREAD

**Issue by piyongcai** [sqlc-dev/sqlc#2848]
### Version

1.22.0

### What happened?

A bug happened!

### Relevant log output

```shell
type Author struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	B         bool             `json:"b"`
	Nb        *bool            `json:"nb"`
	Bio       *string          `json:"bio"`
	Sallary   decimal.Decimal  `json:"sallary"`
	Nsallary  *decimal.Decimal `json:"nsallary"`
	Num       decimal.Decimal  `json:"num"`
	Nnum      *decimal.Decimal `json:"nnum"`
	Dec       decimal.Decimal  `json:"dec"`
	Ndec      *decimal.Decimal `json:"ndec"`
	Status    NullStatus       `json:"status"`    // HERE, i need generage "*Status", how can id do?
	Nstatus   Status           `json:"nstatus"`
	Uu        uuid.UUID        `json:"uu"`
	Uun       *uuid.UUID       `json:"uun"`
	Ba        []byte           `json:"ba"`
	Nba       []byte           `json:"nba"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt **time.Time      `json:"updated_at"` // HERE got  `**time.Time`, need "*time.Time"
	T         time.Time        `json:"t"`
	Nt        **time.Time      `json:"nt"`        // HERE got  `**time.Time`, need "*time.Time"
	D         time.Time        `json:"d"`
	Nd        **time.Time      `json:"nd"`        // HERE got  `**time.Time`, need "*time.Time"
	Dt        time.Time        `json:"dt"`
	Ndt       **time.Time      `json:"ndt"`       // HERE got  `**time.Time`, need "*time.Time"
	Dtz       time.Time        `json:"dtz"`
	Ndtz      **time.Time      `json:"ndtz"`      // HERE got  `**time.Time`, need "*time.Time"
	Dtsz      time.Time        `json:"dtsz"`
	Ndtsz     **time.Time      `json:"ndtsz"`     // HERE got  `**time.Time`, need "*time.Time"
}
```

### Database schema

```sql

CREATE TYPE status AS ENUM (
    'open',
    'closed'
);

CREATE TABLE authors (
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    b bool NOT NULL,
    nb bool,
    bio  VARCHAR,
    sallary money NOT NULL,
    nsallary money,
    num numeric(10,2) NOT NULL,
    nnum numeric(10,2),
    dec decimal NOT NULL,
    ndec decimal,
    status status,
    nstatus status NOT NULL,
    uu uuid not null,
    uun uuid,
    ba bytea not null,
    nba bytea,
    data jsonb,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp,
    t time not null,
    nt time,
    nd date,
    dt timestamp not null,
    ndt timestamp,
    dtz timetz not null,
    ndtz timetz,
    dtsz timestamptz not null,
    ndtsz timestamptz
);
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    #schema: "db/migrations"
    gen:
      go:
        package: "tutorial"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        emit_result_struct_pointers: true
        emit_pointers_for_null_types: true
        emit_params_struct_pointers: true
        emit_enum_valid_method: true
        emit_all_enum_values: true
        #emit_methods_with_db_argument: true
        #emit_db_tags: true
        out: "tutorial"
        overrides:
          - db_type: "pg_catalog.numeric"
            go_type: "github.com/shopspring/decimal.Decimal"
          - db_type: "pg_catalog.numeric"
            go_type: "*github.com/shopspring/decimal.Decimal"
            nullable: true
          - db_type: "money"
            go_type: "github.com/shopspring/decimal.Decimal"
          - db_type: "money"
            go_type: "*github.com/shopspring/decimal.Decimal"
            nullable: true
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
          - db_type: "uuid"
            go_type: "*github.com/google/uuid.UUID"
            nullable: true
          - column: "authors.data"
          - db_type: "pg_catalog.time"
            go_type: "time.Time"
          - db_type: "pg_catalog.time"
            go_type: "*time.Time"
            nullable: true
          - db_type: "date"
            go_type: "time.Time"
          - db_type: "date"
            go_type: "*time.Time"
            nullable: true
          - db_type: "pg_catalog.timestamp"
            go_type: "time.Time"
          - db_type: "pg_catalog.timestamp"
            go_type: "*time.Time"
            nullable: true
          - db_type: "timetz"
            go_type: "time.Time"
          - db_type: "timetz"
            go_type: "*time.Time"
            nullable: true
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "timestamptz"
            go_type: "*time.Time"
            nullable: true
```

**Comment by andrewmbenton** [comment]
You can massage your sqlc config to give you the types you want for your model structs, but your program won't actually work without some effort. This is because `*time.Time` won't scan a `NULL` value into a `nil` pointer.

See the comments on [this pgx issue](https://github.com/jackc/pgx/issues/1242) for a possible workaround using the [pgx `zeronull` package](https://github.com/jackc/pgx/tree/master/pgtype/zeronull).

For all the `time.Time` pointers, you can get the types you want by using the expanded version of the override's `go_type` property. Note that I haven't tested that the generated code actually works, only that the types you want are generated. Here's a partial config just for `pg_catalog.time` but all the overrides would look the same:

```yaml
          - db_type: "pg_catalog.time"
            go_type: "time.Time"
          - db_type: "pg_catalog.time"
            nullable: true
            go_type:
              import: "time"
              type: "Time"
              pointer: true
```

See the section beginning with "For more complicated import paths..." in the [Overriding types documentation](https://docs.sqlc.dev/en/stable/howto/overrides.html). (Also, yaml anchors and aliases are a good way to reduce bloat in the overrides section.)

The `Status` enum also doesn't implement scanning `NULL`s into `nil` pointers, although that's arguably a feature we could add behind a config option.
