### ISSUE TITLE
Configuration: allow more global settings

### ISSUE THREAD

**Issue by hectorj-thetreep** [sqlc-dev/sqlc#2878]
### What do you want to change?

Hi and thank you for `sqlc`, I love it!

I'd like to be able to do something like this:

```
version: "2"
gen:
  go:
    omit_unused_structs: true
    sql_package: "pgx/v5"
sql: [...]
```

and have the root `gen` options be the default for each `sql` item so I do not have to repeat them.

Use case: I'm generating one sub-package for each of my packages, and right now my `sqlc.yaml` is extremely redundant.

I also wouldn't mind Free unicorns!

Thank you.
