### ISSUE TITLE
copyfrom doesn't support non-parameter values

### ISSUE THREAD

**Issue by MuhammedOzdogan** [sqlc-dev/sqlc#2884]
### Version

1.22.0

### What happened?

I have a column which has [tsvector](https://www.postgresql.org/docs/current/datatype-textsearch.html#DATATYPE-TSVECTOR) data type.
I need to insert more than 40 records in a single database call so I tried to use [:copyFrom](https://docs.sqlc.dev/en/stable/howto/insert.html#using-copyfrom)
`sqlc generate` fails to compile.

### Relevant log output

```shell
sqlc generate
# package sqlc
db/queries/page.sql:1:1: :copyfrom doesn't support non-parameter values
make: *** [sqlc] Error 1
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS page (
	id SERIAL PRIMARY KEY,
	content VARCHAR(4095) NOT NULL,
    	content_vector tsvector
	);

-- Create a GIN index on the content_vector column for optimized full-text search
CREATE INDEX page_content_vector_idx
ON page
USING GIN (content_vector);
```

### SQL queries

```sql
-- name: CreatePages :copyfrom
INSERT INTO page (
		content,
		content_vector)
VALUES(
		sqlc.arg('content')::text,
		to_tsvector('simple', sqlc.arg('content')::text)
	);
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/queries/"
    schema: "db/migrations/"
    gen:
      go:
        package: "sqlc"
        sql_package: "pgx/v5"
        out: "db/sqlc/"
        emit_interface: true
        emit_json_tags: true
```

### Playground URL

https://play.sqlc.dev/p/ba8acb18626c8e8038ae60686edf737f514dc76c92d96bb1d7d761062829511b

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
