### ISSUE TITLE
`timestamp with time zone` not recognized as `timestamptz` when overridden with `time.Time`

### ISSUE THREAD

**Issue by dandee** [sqlc-dev/sqlc#2914]
### Version

1.23.0

### What happened?

A SQL type `timestamp with time zone` is not recognized as `timestamptz` when overridden with `time.Time`.

as mentioned by @andrewmbenton here: https://github.com/sqlc-dev/sqlc/issues/2630#issuecomment-1729891052

### Relevant log output

```shell
models.go

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID         int32
	FirstLogin pgtype.Timestamptz // BUG: not recognized so not overridden as *time.Time
	LastLogin  *time.Time
}
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS users
(
    id SERIAL PRIMARY KEY,
    first_login timestamp with time zone,
    last_login timestamptz
);
```

### SQL queries

```sql
-- name: UpdateLoginTime :one
UPDATE users
  SET first_login = CASE WHEN first_login IS NULL THEN $2 END,
  last_login = $2
WHERE id = $1
RETURNING *;
```

### Configuration

```yaml
version: "2"
sql:
- engine: "postgresql"
  queries: "."
  schema: "."
  gen:
    go:
      sql_package: "pgx/v5"
      package: "db"
      out: "db"
      emit_pointers_for_null_types: true
      overrides:
      - db_type: "timestamptz"
        go_type:
          import: "time"
          type: "Time"
          pointer: true
        nullable: true
      # Test...
      - db_type: "timestamp with time zone"
        go_type:
          import: "time"
          type: "Time"
          pointer: true
        nullable: true
```

### Playground URL

https://play.sqlc.dev/p/a68b40b430ec7d02ded1a8688a4b55850ea36e3c242de289f61e4750f12f3c9f

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
