### ISSUE TITLE
Star example failed for query

### ISSUE THREAD

**Issue by kyleconroy** [sqlc-dev/sqlc#2915]
### Version

1.23.0

### What happened?

Generating code for a query with star expansion didn't work.

### Relevant log output

```shell
# package db
query.sql:1:1: star expansion failed for query
```

### SQL queries

```sql
WITH total AS (
    WITH a AS (
    	SELECT 1 AS col1, 2 AS col2
    ),
    b AS (
    	SELECT 1 AS col1, 3 AS col3
    )
    SELECT *
    FROM a
    FULL JOIN b USING (col1)
)
SELECT * FROM total;
```

### Configuration

```yaml
version: "2"
cloud:
  project: "<PROJECT_ID>"
sql:
- schema: "schema.sql"
  queries: "query.sql"
  engine: "postgresql"
  database:
    managed: true
  gen:
    go:
      out: db
      sql_package: "pgx/v5"
```

### Playground URL

https://play.sqlc.dev/p/4f4fbdba61dc9fc8a64a5c57f71e814e56183baf46966d254864f5dc3b0d2c4c

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
