### ISSUE TITLE
Add an override using pgtype causes duplicate imports

### ISSUE THREAD

**Issue by kyleconroy** [sqlc-dev/sqlc#2928]
### Version

1.23.0

### What happened?

When overriding a column to use a type from [pgtype](https://pkg.go.dev/github.com/jackc/pgx/v5@v5.4.3/pgtype), two imports get generated that conflict with each other.

### Database schema

```sql
CREATE TABLE overrides (
    one     text NOT NULL,
    two     bigint NOT NULL,
    three   text[] NOT NULL,
    four    bytea NOT NULL,
    five    text[]
);
```

### SQL queries

```sql
SELECT 1;
```

### Configuration

```yaml
version: "2"
overrides:
  go:
    rename:
      one: "ONE"
    overrides:
      - db_type: "text"
        go_type: "github.com/sqlc-dev/pqtype.NullRawMessage"
      - column: "overrides.three"
        go_type:
          import: "github.com/jackc/pgx/v5/pgtype"
          type: "Text"
sql:
- schema: "schema.sql"
  queries: "query.sql"
  engine: "postgresql"
  gen:
    go: 
      out: "db"
```

### Playground URL

https://play.sqlc.dev/p/dd3248d0c68f75027892ebaf192a6c24bae80e953788e8236f3a9d658f8abb19

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
