### ISSUE TITLE
Type overriding does not work if **database: uri** option is specified

### ISSUE THREAD

**Issue by newRational** [sqlc-dev/sqlc#2968]
### Version

1.23.0

### What happened?

A bug happened!

**Comment by dennisgsmith** [comment]
I'm surprised this issue hasn't gotten more attention. After some testing I found that **the returned types appear to use the correct overrides and only generated "\*Params" structs are sometimes affected by this (not always the case, see example below)**. As a workaround, you can manually coerce the types in the sqlc queries (i.e. `sqlc.arg(created_at)::timestmptz`) but I would expect the behavior to be consistent across code generated with or without the database uri parameter supplied.

**EDIT**: A better workaround I've found is to isolate sqlc vet and generate commands.

`sqlc vet -f sqlc.vet.yaml && sqlc generate -f sqlc.generate.yaml`

**_sqlc.vet.yaml_**
```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "queries.sql"
    schema:
      - "schema.sql"
    database:
      uri: "postgresql://postgres:postgres@db:5432/postgres"
    rules:
      - sqlc/db-prepare
```

**_sqlc.generate.yaml_**
```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "queries.sql"
    schema:
      - "schema.sql"
    gen:
      go:
        package: db
        out: api/internal/db
        sql_package: pgx/v5
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
        emit_exact_table_names: true
        emit_pointers_for_null_types: true
        
        overrides:
          - db_type: timestamptz
            go_type: time.Time
          - db_type: timestamptz
            nullable: true
            go_type:
              type: time.Time
              pointer: true
```

# example of issue and alternative workaround using type coersion

## configuration and schema
_**sqlc.yaml**_
```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "queries.sql"
    schema:
      - "schema.sql"
    database:
      uri: "postgresql://postgres:postgres@db:5432/postgres"
    rules:
      - sqlc/db-prepare
    gen:
      go:
        package: "db"
        out: "db"
        sql_package: "pgx/v5"
        output_files_suffix: "_gen"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
        emit_exact_table_names: true
        emit_pointers_for_null_types: true

        overrides:
          # this seems to always work, generated params use github.com/google/uuid.UUID
          - db_type: uuid
            go_type: github.com/google/uuid.UUID
          - db_type: uuid
            nullable: true
            go_type:
              type: uuid.UUID
              pointer: true

          # this does not always work, sometimes generated params use github.com/jackc/pgx/v5/pgtype.Timestamptz
          - db_type: timestamptz
            go_type: time.Time
          - db_type: timestamptz
            nullable: true
            go_type:
              type: time.Time
              pointer: true
```

_**schema.sql**_
```sql
create table foo (
  id uuid primary key,
  created_at timestamptz
);
```

## problematic query

_**queries.sql**_
```sql
-- name: FooCreate :exec
insert into foo (id, created_at)
values ($1, $2);
```

generates:
_**db/queries_gen.go**_
```go
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const fooCreate = `-- name: FooCreate :exec
insert into foo (id, created_at)
values ($1, $2)
`

type FooCreateParams struct {
	ID uuid.UUID `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FooCreate(ctx context.Context, arg FooCreateParams) error {
	_, err := q.db.Exec(ctx, fooCreate, arg.ID, arg.CreatedAt)
	return err
}
```

## workaround

_**queries.sql**_
```sql
-- name: FooCreate :exec
insert into foo (id, created_at)
values (sqlc.arg(id), sqlc.arg(created_at)::timestamptz);
```

generates:
_**db/queries_gen.go**_
```go
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const fooCreate = `-- name: FooCreate :exec
insert into foo (id, created_at)
values ($1, $2::timestamptz)
`

type FooCreateParams struct {
	ID uuid.UUID `json:"id"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) FooCreate(ctx context.Context, arg FooCreateParams) error {
	_, err := q.db.Exec(ctx, fooCreate, arg.ID, arg.CreatedAt)
	return err
}
```
