### ISSUE TITLE
postgresql: Numeric field Sum(xx), result need decimal, but got int64

### ISSUE THREAD

**Issue by piyongcai** [sqlc-dev/sqlc#2973]
### Version

1.23.0

### What happened?

A bug happened!

### Relevant log output

```shell
type SumTradeRow struct {
  Name  string  `json:"name"`
  Total int64   `json:"total"`  // HERE <- need decimal.Decimal, but got int64
}
```

### Database schema

```sql
CREATE TABLE vip(
  id SERIAL PRIMARY KEY,
  name VARCHAR,
);

CREATE TABLE trade(
  id SERIAL PRIMARY KEY,
  vip_id INT,
  fee numeric(12,2)
);
```

### SQL queries

```sql
-- name: SumTrade :many
SELECT a.name,
       sum(b.fee) total
  FROM vip   a LEFT JOIN
       trade b ON a.id = b.vip_id
```

### Configuration

```yaml
version: "2"
# global overrides
overrides:
  go:
    overrides:
      # numeric
      - db_type: "pg_catalog.numeric"
        go_type:
          import: "github.com/shopspring/decimal"
          type: "Decimal"
      # numeric nullable
      - db_type: "pg_catalog.numeric"
        nullable: true
        go_type:
          import: "github.com/shopspring/decimal"
          type: "Decimal"
          pointer: true
sql:
  - queries: "sql"
    engine: "postgresql"
    schema: "sql/schema"
    gen:
      go:
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        emit_result_struct_pointers: true
        emit_pointers_for_null_types: true
        emit_params_struct_pointers: true
        emit_enum_valid_method: true
        emit_all_enum_values: true
        package: "crud"
        out: "crud"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
