### ISSUE TITLE
Named string parameter `sqlc.arg` parsed as `sql.NullString`

### ISSUE THREAD

**Issue by taleeus** [sqlc-dev/sqlc#2988]
### Version

1.23.0

### What happened?

The SQLC generated code parsed the `storeCode` arg as `sql.NullString`, even if specified as `sqlc.arg`, and not as `sqlc.narg`.

My guess is that it's giving priority to the database schema, since `storeCode` is a nullable string.

### Database schema

```sql
-- Foreign keys omitted

CREATE TABLE `OtoKioskInstallation` (
  `code` VARCHAR(191) NOT NULL,
  `status` ENUM('ACTIVE', 'DISMISSED') NOT NULL DEFAULT 'ACTIVE',
  `otokioskSerialNumber` VARCHAR(191) NOT NULL,
  `storeCode` VARCHAR(191) NULL,
  `installedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `OtoKioskInstallation_status_idx`(`status`),
  PRIMARY KEY (`code`)
);
```

### SQL queries

```sql
-- name: CreateOtokioskInstallation :exec
INSERT INTO OtoKioskInstallation (
    code,
    otokioskSerialNumber,
    storeCode,
    updatedAt
) VALUES (
    sqlc.arg(code),
    sqlc.arg(otokioskSerialNumber),
    sqlc.arg(storeCode),
    NOW()
);
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "mysql"
    queries: "queries"
    schema: "schema.sql"
    gen:
      go:
        package: "dbout"
        out: "../../../app/dbout"
        emit_empty_slices: true
    database:
      uri: "${DATABASE_URL}"
    rules:
      - sqlc/db-prepare
```

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
