### ISSUE TITLE
Version 2 Configuration - json_tags_id_uppercase fails

### ISSUE THREAD

**Issue by Jakoo13** [sqlc-dev/sqlc#2991]
### Version

1.23.0

### What happened?

When trying to add the json_tags_id_uppercase tag into the sqlc.yaml file and running sqlc generate it returns error that that identifier is not found. 

### Relevant log output

```shell
error parsing sqlc.yaml: yaml: unmarshal errors:
  line 14: field json_tags_id_uppercase not found in type config.SQLGo
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "./db/query/"
    schema: "./db/migration/"
    gen:
      go:
        package: "db"
        out: "./db/sqlc"
        emit_json_tags: true
        sql_package: "database/sql"
        emit_interface: true
        json_tags_case_style: "camel"
        json_tags_id_uppercase: true
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
