### ISSUE TITLE
sql codgen for RETURNING in keyword not generating return values

### ISSUE THREAD

**Issue by Shubham-Rasal** [sqlc-dev/sqlc#2992]
### Version

1.23.0

### What happened?

Here's my update query for postgres (version 14):

```sql
-- name: UpdateEmail :exec
UPDATE users SET email = $1
WHERE id = $2
RETURNING id;

```
After running sqlc generate, it generates the following code:

```go

const updateEmail = `-- name: UpdateEmail :exec
UPDATE users SET email = $1
WHERE id = $2
RETURNING id
`

type UpdateEmailParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.exec(ctx, q.updateEmailStmt, updateEmail, arg.Email, arg.ID)
	return err
}

```

As you can see the `updateEmail func` only returns the error.

This behaviour is consistent across updates, deletes. For inserts, everything works fine.

### Database schema

```sql
CREATE TABLE "follows" (
  "following_user_id" integer,
  "followed_user_id" integer,
  "created_at" timestamp
);

CREATE TABLE "users" (
  "id" bigserial NOT NULL UNIQUE,
  "username" varchar PRIMARY KEY,
  "password" varchar NOT NULL,
  "email" varchar NOT NULL
);

CREATE TABLE "accounts" (
  "id" bigserial PRIMARY KEY,
  "user_id" integer,
  "username" varchar,
  "role" varchar,
  "reputation" integer,
  "created_at" timestamp
);

CREATE TABLE "posts" (
  "id" integer PRIMARY KEY,
  "title" varchar,
  "body" text,
  "user_id" integer,
  "status" varchar,
  "created_at" timestamp
);

COMMENT ON COLUMN "posts"."body" IS 'Content of the post';

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "accounts" ("user_id");

ALTER TABLE "follows" ADD FOREIGN KEY ("following_user_id") REFERENCES "accounts" ("user_id");

ALTER TABLE "follows" ADD FOREIGN KEY ("followed_user_id") REFERENCES "accounts" ("user_id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "accounts" ("user_id");
```

### SQL queries

```sql
-- name: UpdateEmail :exec
UPDATE users SET email = $1
WHERE id = $2
RETURNING id;

-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1 RETURNING id;
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    path: "./db/sqlc"
    queries: "./db/query/"
    schema: "./db/migration/"
    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: true
    emit_interface: true
    emit_exact_table_names: false
    emit_empty_slices: true
```

### Playground URL

https://play.sqlc.dev/p/3cc713d2b4673acd115b5494d5dcdb4554f45d81f85f745c15958f6b3ea1e77c

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
