### ISSUE TITLE
Wrong output of override

### ISSUE THREAD

**Issue by juliusmh** [sqlc-dev/sqlc#3005]
### Version

1.24.0

### What happened?

Override doesn't seem to work properly for foreign fields. I expected the `profile_id` column to translate to `uuid.UUID`.

### Relevant log output

```shell
type CreateQueryParams struct {
    ID           uuid.UUID
    ProfileID    pgtype.UUID
}
// and
type Query struct {
    ID           uuid.UUID
    ProfileID    pgtype.UUID
```

### Database schema

```sql
CREATE TABLE query
(
    id           uuid PRIMARY KEY,
    profile_id   uuid REFERENCES profile (id) ON DELETE CASCADE
)
```

### SQL queries

```sql
-- name: CreateQuery :one
INSERT INTO query(id,profile_id) VALUES ($1, $2) RETURNING *;
```

### Configuration

```yaml
overrides:
  - db_type: "uuid"
    go_type:
      import: "github.com/google/uuid"
      type: "UUID"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by shkvoretz** [comment]
yeah, same issue here. This is somewhat critical.

**Comment by shkvoretz** [comment]
ok, I have figured out what's wrong with it in my case. I was overriding numeric like this 

```
  - db_type: "pg_catalog.numeric"
    nullable: false                          
    go_type:
      import: "yapi/types"
      type: "Decimal"
  - db_type: "pg_catalog.numeric"
    nullable: true                          
    go_type:
      import: "yapi/types"
      type: "Decimal"        
```


this was generating model ok, but not the queries. I fixed it by duplicating the above for numeric type but without the schema 

```
  - db_type: "numeric"
    nullable: false                          
    go_type:
      import: "yapi/types"
      type: "Decimal"
  - db_type: "numeric"
    nullable: true                          
    go_type:
      import: "yapi/types"
      type: "Decimal"   
```

The issue appears in gen.go file here 
```
structs := buildStructs(req, options)
queries, err := buildQueries(req, options, structs)
```

buildStructs works off schema.Tables, while buildQueries off req.Queries.Params

These functions need to be aligned to use schema data from the same source.

I'll just stick with my workaround for now, as I don't have time to fix this - it appears some significant changes may be required here. 

This misalignment is likely to cause other issues, I'm sure.
