### ISSUE TITLE
"Error parsing sqlc.yaml" when generating files

### ISSUE THREAD

**Issue by andrwkoval** [sqlc-dev/sqlc#3007]
### Version

1.24.0

### What happened?

Can't generate the files, because it seems it can't unmarshal the `sqlc.yaml` file.

### Relevant log output

```shell
go run -mod=mod github.com/sqlc-dev/sqlc/cmd/sqlc generate
go: finding module for package github.com/sqlc-dev/sqlc/cmd/sqlc
error parsing sqlc.yaml: yaml: unmarshal errors:
  line 15: field output_querier_file_name not found in type opts.Options
exit status 1
```

### Database schema

```sql
Not relevant.
```

### SQL queries

```sql
Not relevant.
```

### Configuration

```yaml
Not a full configuration, just the problematic part

sql:
  - gen:
      go:
        output_db_file_name: "db.gen.go"
        output_models_file_name: "models.gen.go"
        output_querier_file_name: "querier.gen.go"
        output_files_suffix: ".gen.go"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
