### ISSUE TITLE
Using emit_pointers_for_null_types doesn't work for nullable time.Time

### ISSUE THREAD

**Issue by abramowitzK** [sqlc-dev/sqlc#3012]
### Version

1.24.0

### What happened?

In my yaml file i have this override
```
      - db_type:  pg_catalog.timestamptz
        go_type:  time.Time
        nullable: true
```

This generates values of `time.Time` instead of `*time.Time`.  There's nothing in the docs for the option that says it doesn't work for structs so I tried adding the `*` to the override in the yaml which works if you put the type in quotes.

This generated `**time.Time` which was very confusing to me given that the non-pointer version generated just a plain struct. 

If this is intended behavior I think a note about this in the docs would be helpful because it seems like at least time.Time isn't affected by the  `emit_pointers_for_null_types` option but a pointer to it is which is not intuitive

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by andrewmbenton** [comment]
Agreed this is not intuitive. The solution (I think) is to use an override with the more detailed `go_type` including the `pointer: true` property, like this:

```yaml
      - db_type: pg_catalog.timestamptz
        go_type:
          import: time
          type: Time
          pointer: true
        nullable: true
```
