### ISSUE TITLE
Edge case in model name of generated code

### ISSUE THREAD

**Issue by SebastienMelki** [sqlc-dev/sqlc#3029]
### Version

1.24.0

### What happened?

I have a table called 'raw_bonus' but the generate struct has the name 'RawBonu'. I've attached a screenshot of my sqlc config.

![image](https://github.com/sqlc-dev/sqlc/assets/5787993/be3099dc-b719-4a22-ae02-7f133aff7b99)

![image](https://github.com/sqlc-dev/sqlc/assets/5787993/df117e4a-ff62-42ac-87cf-2c4cf895c895)

<img width="352" alt="image" src="https://github.com/sqlc-dev/sqlc/assets/5787993/e26fa3f5-50df-4500-bb93-eae9bf5f1651">

### Database schema

```sql
CREATE TABLE raw_bonus
(
    `raw_bonus_id`       int(11)     NOT NULL AUTO_INCREMENT,
    `file_id`            int(11)     NOT NULL,
    `start_date_time`    datetime    NOT NULL,
    `end_date_time`      datetime    NOT NULL,
    `uri_id`             varchar(20) NOT NULL,
    `source_url`         varchar(255)         DEFAULT NULL,
    `content_check_sum`  varchar(255)         DEFAULT NULL,
    `is_copy_protection` tinyint(1)  NOT NULL DEFAULT '0',
    `bonus_category`     varchar(255)         DEFAULT NULL,
    `bonus_material`     tinyint(1)  NOT NULL DEFAULT '0',
    `bonus_scope`        varchar(255)         DEFAULT NULL,
    `created_on`         timestamp   NULL     DEFAULT CURRENT_TIMESTAMP,
    `updated_on`         timestamp   NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`raw_bonus_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
```

### Configuration

```yaml
- path: "db/dbmodels/osn_ingest"
    name: "osn_ingestdb"
    engine: "mysql"
    schema: "db/dbschemas/osn_ingest"
    queries: "db/queries/osn_ingest"
    emit_db_tags: true
    emit_exported_queries: true
```

### What operating system are you using?

Linux

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
