### ISSUE TITLE
Support zeronull.Text in addition to pgtype.Text in pgx mode

### ISSUE THREAD

**Issue by op** [sqlc-dev/sqlc#3054]
### What do you want to change?

When using `pgx/v5` for the `sql_package`, to create a null string you need to construct a `pgtype.Text{Valid: false}`. The `zeronull` package exists to make it easier to handle zero values and to represent them as nulls.

Both `zeronull.Text` and `pgtype.Text` share the same interface, `database/sql/driver.Valuer`, but sqlc uses pgtype.Text explicitly. It is possible to override the type to use this interface. This allow a user to supply either `zeronull.Text` or `pgtype.Text`, making it a bit easier to handle optional NULLs.

sqlc.yaml:
```yaml
[..]
        sql_package: "pgx/v5"
        overrides:
          - db_type: "text"
            nullable: true
            go_type:
              import: "database/sql/driver"
              # (database/sql/driver is aready imported, this is a trick to allow us to import it again)
              package: duplicate_driver
              type: "Valuer"
```

This allow you to use do something along these lines:
```go
	somepkg.New(db).Insert(ctx, somepkg.InsertParams{
		NullableField: zeronull.Text(""),
		Field: pgtype.Text{Valid: true, String: "value"),
	})
```

All of this works fine so I'm just asking why this is not the default behaviour? :) Changing the default to be `driver.Valuer` should also be a backwards compatible change.

Implemented in the playground:
https://play.sqlc.dev/p/ec8426251a7a77a415ecd6a4d3e1c8970c5dd36c09530ffbddd4f30c85147b86

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go
