### ISSUE TITLE
Query and column overrides use different types for the same underlying database type

### ISSUE THREAD

**Issue by kyleconroy** [sqlc-dev/sqlc#3063]
ok, I have figured out what's wrong with it in my case. I was overriding numeric like this 

```
  - db_type: "pg_catalog.numeric"
    nullable: false                          
    go_type:
      import: "yapi/types"
      type: "Decimal"
  - db_type: "pg_catalog.numeric"
    nullable: true                          
    go_type:
      import: "yapi/types"
      type: "Decimal"        
```

this was generating model ok, but not the queries. I fixed it by duplicating the above for numeric type but without the schema 

```
  - db_type: "numeric"
    nullable: false                          
    go_type:
      import: "yapi/types"
      type: "Decimal"
  - db_type: "numeric"
    nullable: true                          
    go_type:
      import: "yapi/types"
      type: "Decimal"   
```

The issue appears in gen.go file here 
```
structs := buildStructs(req, options)
queries, err := buildQueries(req, options, structs)
```

buildStructs works off schema.Tables, while buildQueries off req.Queries.Params

These functions need to be aligned to use schema data from the same source.

I'll just stick with my workaround for now, as I don't have time to fix this - it appears some significant changes may be required here. 

This misalignment is likely to cause other issues, I'm sure.

_Originally posted by @shkvoretz in https://github.com/sqlc-dev/sqlc/issues/3005#issuecomment-1850261768_
