### ISSUE TITLE
MySQL `JSON_TABLE` not supported

### ISSUE THREAD

**Issue by sgielen** [sqlc-dev/sqlc#3129]
### Version

1.25.0

### What happened?

A migrations file using the MySQL `JSON_TABLE` function cannot be parsed by sqlc.

### Relevant log output

```shell
# package 
migrations/2.sql:8:19: syntax error near "(p.emails, '$[*]' COLUMNS(email TEXT PATH '$')) AS pe;"
```

### Database schema

```sql
-- migrations/1.sql
CREATE TABLE person (
  emails TEXT NOT NULL
);

-- migrations/2.sql
CREATE TABLE person_email (
  email TEXT NOT NULL
);

INSERT INTO person_email (`email`)
  SELECT pe.email
  FROM person AS p
  JOIN JSON_TABLE(p.emails, '$[*]' COLUMNS(email TEXT PATH '$')) AS pe;
```

### SQL queries

```sql
-- name: GetEmails :many
SELECT email FROM person_email;
```

### Configuration

```yaml
version: "2"
sql:
- engine: "mysql"
  queries: "queries.sql"
  schema: "migrations"
  gen:
    go:
      out: "gendb"
```

### Playground URL

https://play.sqlc.dev/p/0bed956ccb54908516d6a6f70813e4cf1182bb978b548689034de7813eb7efce

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
