### ISSUE TITLE
custom struct tags are not emmited

### ISSUE THREAD

**Issue by bluebrown** [sqlc-dev/sqlc#3143]
### Version

1.25.0

### What happened?

I am trying to set a custom struct tag but its not generated with the model.

### Relevant log output

```shell
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package store

import (
	"database/sql"
)

type Test struct {
	Nullstring sql.NullString
}
```

### Database schema

```sql
create table test (
  nullstring text
)
```

### SQL queries

```sql
-- name: read :one
select * from test where nullstring = ?;
```

### Configuration

```yaml
version: "2"
sql:
- engine: sqlite
  queries: ./query.sql
  schema: ./schema.sql
  gen:
    go:
      package: store
      out: ./store/
      overrides:
      - db_type: text
        nullable: true
        go_struct_tag: a:"b"
```

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
