### ISSUE TITLE
CTE inside subquery not working

### ISSUE THREAD

**Issue by ross96D** [sqlc-dev/sqlc#3156]
### Version

1.25.0

### What happened?

It seems that the parser cannot identify the relation created from the cte when the cte is inside a subquery

### Relevant log output

```shell
query.sql:1:1: relation "cte_authors" does not exist
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: test :many
SELECT * FROM (
  WITH cte_authors AS (
    SELECT * FROM authors
  )
  SELECT * FROM authors JOIN cte_authors ON autors.id = cte_autors.et_id
) AS sub WHERE true;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/ee35e71a5d2a5322c92655a2cfe5269302155113824459cc9c7f1fb74afd771f

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
