### ISSUE TITLE
Can't override 'bigint' to be uint32

### ISSUE THREAD

**Issue by EasyEesteren** [sqlc-dev/sqlc#3184]
### Version

Other

### What happened?

I am writing a service which can receive uint32 values that it has to persist in a postgres database. I am using sqlc to generate the go code to interact with the database. My database design uses 'bigint' for these id columns. By default the generated code expects the type int64 for the bigint id fields but I want to override this to be uint32 as that is more inline with reality. However, adjusting my sqlc.yaml file to include this override does not have the desired effect as the generated code still expects int64

### Configuration

```yaml
version: '2'
sql:
  - schema: './../../../../cmd/postgres/migrations'
    queries: './queries'
    engine: 'postgresql'
    strict_order_by: false
    gen:
      go:
        package: 'generated'
        out: 'PGgenerated'
        emit_json_tags: true
        json_tags_case_style: 'snake'
        overrides:
          - db_type: pg_catalog.bigint
            go_type: uint32
```
```


### Playground URL

_No response_

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by jakoguta** [comment]
@EasyEesteren I believe implementing such an override may be risky. Others may choose to use `uint64` and this may cause out of range errors in PostgreSQL as it does not natively support unsigned integers at the moment.

**Comment by alarbada** [comment]
> @EasyEesteren I believe implementing such an override may be risky. Others may choose to use `uint64` and this may cause out of range errors in PostgreSQL as it does not natively support unsigned integers at the moment.

It might be risky, but what sqlc 1.25 is doing now is really confusing. If the override is not going to be applied a warning would be very helpful at the very least.

I have a similar problem as @EasyEesteren with this configuration:

```yaml
version: "2"
sql:
  - schema: "server/db/schema.sql"
    queries: "server/db/queries.sql"
    engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "server/db"
        overrides:
          - db_type: "bigint"
            go_type: "int"
```

This is generating bigints as int64 in my models.go, but technically speaking this should be valid right?
