### ISSUE TITLE
SQlite errors when setting `BOOLEAN`

### ISSUE THREAD

**Issue by sjunepark** [sqlc-dev/sqlc#3196]
### Version

1.25.0

### What happened?

Hi,

If I type a field as `BOOLEAN`, `sqlc` creates a struct with type `bool`.

```sql
CREATE TABLE IF NOT EXISTS locations
(
    ValidPosition      BOOLEAN NOT NULL CHECK (ValidPosition = 0 OR ValidPosition = 1),
)
```

```go
type Location struct {
	Validposition      bool
}
```

Which results to a `INSERT` error below

```shell
unsupported type bool
```

As a current work around, I'm just defining related field as `INTEGER`s, which probably won't be different internally.

### Configuration

```yaml
version: "2"
sql:
  - engine: "sqlite"
    queries: "./db/sqlc/query.sql"
    schema: "./db/sqlc/schema.sql"
    gen:
      go:
        package: "sqlc"
        out: "internal/sqlc"
```

### What operating system are you using?

macOS

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
