### ISSUE TITLE
Generation of required params struct is missing for CopyFrom query when using query_parameter_limit

### ISSUE THREAD

**Issue by renier** [sqlc-dev/sqlc#3197]
### Version

1.25.0

### What happened?

sqlc is not generating the params struct necessary for a copy-from query when your configuration specifies `query_parameter_limit`.  This is on version 1.25.0. Works fine if you remove `query_parameter_limit` from the configuration.

### Database schema

```sql
CREATE TABLE IF NOT EXISTS alert_triage_status (
  id varchar(512) primary key,
  assignee varchar(512)
);
```

### SQL queries

```sql
-- name: AddAssigneeToAlertTriageStatuses :copyfrom
INSERT INTO alert_triage_status (id, assignee) VALUES ($1, $2);

-- name: RemoveAssigneeFromAlertsTriageStatuses :exec
DELETE FROM alert_triage_status WHERE assignee = $1 AND id = ANY($2::varchar[]);
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [
    {
      "engine": "postgresql",
      "queries": "query.sql",
      "schema": "schema.sql",
      "gen": {
        "go": {
          "package": "db",
          "out": ".",
          "sql_package": "pgx/v5",
          "query_parameter_limit": 100
        }
      }
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/90e29f89bd6b6be43c83c31794eb5d80fb753a3c26250f077353c081ad3433ea

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
