### ISSUE TITLE
struct overrides do not work for sql queries with schema

### ISSUE THREAD

**Issue by stephensanwo** [sqlc-dev/sqlc#3217]
### Version

1.25.0

### What happened?

When I try to run migrations with `sqlc generate` with the sample code below

```sql
CREATE SCHEMA core;

CREATE TABLE core.users (
  "id" bigserial PRIMARY KEY,
  "email" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
);
```
I expect to have a struct generated like this

```go
type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
```

As I have defined overrides in `sqlc.yaml`

```yml
overrides:
  go:
    rename:
      "core.users": User
```

Instead, the output struct is 
```go
type CoreUser struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
```

### Database schema

```sql
CREATE SCHEMA core;

CREATE TABLE core.users (
  "id" bigserial PRIMARY KEY,
  "email" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
);
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "internal/db/migration"
    queries: "internal/db/query"
    engine: "postgresql"
    gen:
      go: 
        package: "db"
        out: "internal/db/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
overrides:
  go:
    rename:
      "core.users": User
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by stephensanwo** [comment]
Closing this, got the rename mapping wrong.
The correct mapping should be:
```yaml
version: "2"
sql:
  - schema: "internal/db/migration"
    queries: "internal/db/query"
    engine: "postgresql"
    gen:
      go: 
        package: "db"
        out: "internal/db/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
overrides:
  go:
    rename:
      core_user: User
```
