### ISSUE TITLE
Bug while generate go code with pgx/v5

### ISSUE THREAD

**Issue by defany** [sqlc-dev/sqlc#3218]
### Version

1.25.0

### What happened?

I tried to write this config.yaml file with preoared queries, because I don't see any methods for this in my code like in docs

### Relevant log output

```shell
error parsing sqlc.yaml: yaml: unmarshal errors:
  line 6: field emit_prepared_queries not found in type config.SQL
```

### Database schema

```sql
-- +goose Up
-- +goose StatementBegin
create table if not exists chats(
    id bigserial primary key,
    title text not null
);

create table if not exists users_chats(
    chat_id bigserial references chats(id),
    user_id numeric(12, 0) constraint positive_users_chats_user_id check ( user_id > 0 ),

    primary key (chat_id, user_id)
);

create table if not exists chats_messages(
    id bigserial primary key,
    chat_id bigserial references chats(id),
    user_id numeric(12, 0) constraint positive_users_chats_user_id check ( user_id > 0 ),
    text text not null,
    timestamp timestamp not null
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table if exists chats_messages;
drop table if exists users_chats;
drop table if exists chats;
-- +goose StatementEnd
```

### SQL queries

```sql
-- name: AddChatMessage :exec
insert into chats_messages
    (chat_id, user_id, text, timestamp)
values ($1, $2, $3, $4);

-- name: AddUsersInChat :copyfrom
insert into users_chats
    (chat_id, user_id)
values ($1, $2);
```

### Configuration

```yaml
version: '2'
sql:
  - engine: postgresql
    schema: "./migrations"
    queries: "app/internal/repository/chat/query"
    emit_prepared_queries: true # this brokes generating
    gen:
      go:
        package: "chatrepo"
        out: "app/internal/repository/chat/gen"
        sql_package: "pgx/v5"
```

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
