### ISSUE TITLE
Resolving reference to CTE column fails

### ISSUE THREAD

**Issue by simonklee** [sqlc-dev/sqlc#3219]
### Version

1.25.0

### What happened?

Resolving references to multiple CTE's with arguments fails.

### Relevant log output

```shell
sqlc generate failed.
# package 
query.sql:5:28: table alias "t1_ids" does not exist
```

### Database schema

```sql
CREATE TABLE t1
(
    id SERIAL NOT NULL PRIMARY KEY
);
```

### SQL queries

```sql
-- name: CTERef :one
WITH t1_ids AS (
    SELECT id FROM t1
)
SELECT * FROM t1_ids WHERE t1_ids.id = sqlc.arg('id');
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/9048b486f822c300301650867612e42bef8f8d512dfd12d84ad3a4cd210f4ef7

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
