### ISSUE TITLE
Column reference is ambiguous

### ISSUE THREAD

**Issue by vunhatchuong** [sqlc-dev/sqlc#3234]
### Version

1.25.0

### What happened?

When I generate the code, it returns an "ambiguous column" error, I tested this in MySQL directly and it works.

### Relevant log output

```shell
# package db
db/queries/query.sql:48:10: column reference "person_id" is ambiguous
```

### Database schema

```sql
CREATE TABLE snapshot_log (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    person_id VARCHAR(255) NOT NULL;
);
```

### SQL queries

```sql
-- name: SearchSnapshotLogPrev :many
SELECT * FROM (
    SELECT * FROM snapshot_log
    WHERE 1=1
    AND (person_id = sqlc.narg('person_id') OR sqlc.narg('person_id') IS NULL)
	GROUP BY id
    HAVING
    CASE WHEN COALESCE(sqlc.narg('last_value'), 0) = (SELECT MAX(id) FROM snapshot_log) THEN id > 0
         ELSE id > sqlc.narg('last_value') END
    ORDER BY id ASC
) AS subquery
ORDER BY id DESC
LIMIT ?;
```

### Configuration

```yaml
version: '2'
sql:
  - engine: mysql
    schema: db/migrations
    queries: db/queries
    gen:
      go:
        package: db
        out: db
        emit_db_tags: true
        overrides:
          - db_type: "datetime"
            go_type:
              import: face-recog-log/dto/mqtt-response/customtypes
              type: CreateTime
```

### What operating system are you using?

Linux

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
