### ISSUE TITLE
SQLite generating code error

### ISSUE THREAD

**Issue by leandergangso** [sqlc-dev/sqlc#3256]
### Version

1.25.0

### What happened?

Trying to `sqlc generate`. I get a long ouput of code which I assume is the generated code, but before finish, the error bellow shows up.

The problem seem to be with `?` in where clause and only for when it's only a single condition.

See #bad and #good examples in sql queries file bellow.

### Relevant log output

```shell
error generating code: source error: 72:49: expected ')', found `name`
```

### Database schema

```sql
create table if not exists `user` (
    `id` integer primary key,
    `name` text not null,
    `age` integer not null
);
```

### SQL queries

```sql
-- name: CreateUser :execresult
insert into `user` (`name`, `age`) values (?, ?);

-- name: GetUser :one
select * from `user` where `name` = ?; # bad
select * from `user` where `name` = $1; # bad
select * from `user` where `name` = :name; # good
select * from `user` where `name` = ? and `age` = ?; # good, more than 1 condition
```

### Configuration

```yaml
version: "2"

sql:
  - engine: "sqlite"
    schema: "repo/migrations"
    queries: "repo/queries"
    gen:
      go:
        out: "repo/dbstore"
        package: "dbstore"
```

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
