### ISSUE TITLE
UUID is not correctly overridden

### ISSUE THREAD

**Issue by alimoli** [sqlc-dev/sqlc#3272]
### Version

1.25.0

### What happened?

`uuid` is only overridden for the primary keys, but not for the foreign keys.

### Relevant log output

```shell
type Event struct {
	ID          uuid.UUID
	OrganizerID pgtype.UUID
	Name        string
	Description string
	Status      string
	ImgUrl      string
	Url         string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Organizer struct {
	ID        uuid.UUID
	Name      string
	ImgUrl    string
	Url       string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
```

### Database schema

```sql
CREATE TABLE organizer
(
    id         uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    name       VARCHAR(100)                           NOT NULL,
    img_url    TEXT                                   NOT NULL,
    url        TEXT                                   NOT NULL,
    created_at TIMESTAMP with time zone DEFAULT now() NOT NULL,
    updated_at TIMESTAMP with time zone DEFAULT now() NOT NULL
);

CREATE TABLE event
(
    id           uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    organizer_id uuid REFERENCES organizer (id),
    name         VARCHAR(100)                           NOT NULL,
    description  TEXT                                   NOT NULL,
    status       VARCHAR(100)                           NOT NULL,
    img_url      TEXT                                   NOT NULL,
    url          TEXT                                   NOT NULL,
    created_at   TIMESTAMP with time zone DEFAULT now() NOT NULL,
    updated_at   TIMESTAMP with time zone DEFAULT now() NOT NULL
);
```

### SQL queries

```sql
-- name: GetEventById :one
SELECT * FROM event WHERE id = $1;

-- name: GetOrganizerById :many
SELECT * FROM organizer WHERE id = $1;

-- name: ListEventsByOrganizer :many
SELECT * FROM event WHERE organizer_id = $1;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/queries.sql"
    schema: "db/schema.sql"
    gen:
      go:
        package: "repository"
        out: "internal/repository"
        sql_package: "pgx/v5"
        # https://github.com/sqlc-dev/sqlc/issues/3005
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
