### ISSUE TITLE
config "output_querier_file_name" does not work properly

### ISSUE THREAD

**Issue by VictorAlmeidaFonseca** [sqlc-dev/sqlc#3285]
### Version

1.25.0

### What happened?

Option "output_querier_file_name" does not change the default value
![sample](https://github.com/sqlc-dev/sqlc/assets/36797751/57a33808-d9a4-4e88-ad68-8fa78bff2d9d)

### Relevant log output

```shell
N/A
```

### Database schema

```sql
N/A
```

### SQL queries

```sql
N/A
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "sqlite"
    queries: "internal/infra/db/sql/assignment/query.sql"
    schema: "internal/infra/db/sql/assignment/schema.sql"
    gen:
      go:
        package: "repository"
        emit_json_tags: true
        emit_result_struct_pointers: true
        output_models_file_name: "assignment_models.go"
        output_querier_file_name: "assignment_querier.go"
        output_db_file_name: 'repo.go'
        json_tags_case_style: "camel"
        out: "internal/infra/db/repository"

  - engine: "sqlite"
    queries: "internal/infra/db/sql/person/query.sql"
    schema: "internal/infra/db/sql/person/schema.sql"
    gen:
      go:
        package: "repository"
        emit_json_tags: true
        emit_result_struct_pointers: true
        output_models_file_name: "person_models.go"
        output_querier_file_name: "person_querier.go"
        output_db_file_name: 'repo.go'
        json_tags_case_style: "camel"
        out: "internal/infra/db/repository"

  - engine: "sqlite"
    queries: "internal/infra/db/sql/person_role/query.sql"
    schema: "internal/infra/db/sql/person_role/schema.sql"
    gen:
      go:
        package: "repository"
        emit_json_tags: true
        emit_result_struct_pointers: true
        output_models_file_name: "person_role_models.go"
        output_querier_file_name: "person_role_querier.go"
        output_db_file_name: 'repo.go'
        json_tags_case_style: "camel"
        out: "internal/infra/db/repository"
        

  - engine: "sqlite"
    queries: "internal/infra/db/sql/role/query.sql"
    schema: "internal/infra/db/sql/role/schema.sql"
    gen:
      go:
        package: "repository"
        emit_json_tags: true
        emit_result_struct_pointers: true
        output_models_file_name: "role_models.go"
        output_querier_file_name: "role_querier.go"
        output_db_file_name: 'repo.go'
        json_tags_case_style: "camel"
        out: "internal/infra/db/repository"
```

### What operating system are you using?

Windows

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
