### ISSUE TITLE
mysql: default expressions causes syntax error

### ISSUE THREAD

**Issue by horriblename** [sqlc-dev/sqlc#3296]
**workaround**: use `DEFAULT (JSON_ARRAY())` instead of `DEFAULT ('[]')`

### Version

1.25.0

### What happened?

sqlc can't parse this database schema:

```sql
create table user (
	id INT AUTO_INCREMENT PRIMARY KEY,
        -- parenthesis is required! 
	data JSON NOT NULL DEFAULT ('[]')
)
```

note that the parenthesis is required for MySQL to work properly:

> The BLOB, TEXT, GEOMETRY, and JSON data types can be assigned a default value only if the value is written as an expression, even if the expression value is a literal.
> from https://stackoverflow.com/questions/61169030/mysql-set-default-value-to-a-json-type-column

this schema causes this error:

```
migrations/1_table.sql:3:34: syntax error near "'[]')"
```

One workaround is to simply remove the parenthesis when we need to regenerate with sqlc, then re-adding it afterwards.

### Relevant log output

```shell
migrations/1_table.sql:3:34: syntax error near "'[]')"
```

### Database schema

```sql
create table user (
	id INT AUTO_INCREMENT PRIMARY KEY,
        -- parenthesis is required! 
	data JSON NOT NULL DEFAULT ('[]')
)
```

### SQL queries

```sql
-- (not important)
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "schema.sql"
    queries: "query.sql"
    engine: "mysql"
    gen:
      go:
        out: "gen/queries"
overrides:
  go: null
plugins: []
rules: []
options: {}
```

### Playground URL

https://play.sqlc.dev/p/a0d57f359abea6143899fddc5844ce44a93a0d15a9171d558b5cdb2bba66cbbc

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
