### ISSUE TITLE
The input for the comparison to the sum of length should be of type int.

### ISSUE THREAD

**Issue by mondy** [sqlc-dev/sqlc#3332]
### Version

1.26.0

### What happened?

Input:
```sql
-- name: GetAuthor :one
SELECT 1 WHERE (SELECT sum(length(data)) FROM authors ) < ?;
```

Output:
```go
func (q *Queries) GetAuthor(ctx context.Context, data []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, data)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
```

The type of the data in the argument is []byte, but it should be int.

### Database schema

```sql
CREATE TABLE authors (
  data BLOB NOT NULL
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT 1 WHERE (SELECT sum(length(data)) FROM authors ) < ?;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "sqlite",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/7ef7f0176111eac4db0a7ad80028c75b4c030ce9cd6a1113ee4b9c29b35051f8

### What operating system are you using?

Windows

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
