### ISSUE TITLE
Not recognizing sqlc.arg after ON CONFLICT.

### ISSUE THREAD

**Issue by mondy** [sqlc-dev/sqlc#3334]
### Version

1.26.0

### What happened?

Input:
```sql
-- name: Insert :exec
INSERT INTO authors (name)
VALUES (sqlc.arg(name))
ON CONFLICT (name) DO UPDATE SET data = sqlc.arg(data);
```

Output:
```go
const insert = `-- name: Insert :exec
INSERT INTO authors (name)
VALUES (?1)
ON CONFLICT (name) DO UPDATE SET data = sqlc.arg(data)
`
```

sqlc.arg(name) is recognized, but sqlc.arg(data) is not recognized.

### Database schema

```sql
CREATE TABLE authors (
  name TEXT NOT NULL UNIQUE,
  data BLOB NOT NULL
);
```

### SQL queries

```sql
-- name: Insert :exec
INSERT INTO authors (name)
VALUES (sqlc.arg(name))
ON CONFLICT (name) DO UPDATE SET data = sqlc.arg(data);
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "sqlite",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/499d67e9cbdb4e01b7b2be3310bdc5d48e1e2154afc581eb48018e001f05beaf

### What operating system are you using?

Windows

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
