### ISSUE TITLE
query execlastid for pgx/v5 is silently ignored

### ISSUE THREAD

**Issue by mishak87** [sqlc-dev/sqlc#3338]
### Version

1.26.0

### What happened?

I was expecting an error or warning when I used query type unsupported by a database.
`sqlc generate` outputs query string and struct but not the function. All other functions are generated.
But playground returns 500 maybe cli is hiding some errors?
1.25.0 playground behaves as 1.26.0 cli (not returning 500 and not generating function)

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: InsertAuthor :execlastid
INSERT INTO authors (name, bio) VALUES (@name, @bio);
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
      	"sql_package": "pgx/v5",
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/fa302952484e0740e4bb2cc57c92950ad07e5c94e373391eff5e58e769116444

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
