### ISSUE TITLE
Cannot use option "initialisms" from the documentation

### ISSUE THREAD

**Issue by Egor-Koldasov** [sqlc-dev/sqlc#3339]
### Version

1.26.0

### What happened?

I cannot use the option "initialisms" from the documentation with both json and yaml configs

### Relevant log output

```shell
`~/go/bin/sqlc version`
> v1.26.0
`~/go/bin/sqlc generate`
> error parsing sqlc.yaml: yaml: unmarshal errors:
line 10: field initialisms not found in type opts.Options
```

### Database schema

```sql
Not relevant
```

### SQL queries

```sql
Not relevant
```

### Configuration
JSON
```json
{
  "version": "2",
  "sql": [
    {
      "engine": "postgresql",
      "queries": "./sql",
      "schema": "../migrations",
      "gen": {
        "go": {
          "package": "dbquery",
          "out": "pkg/sqlgen",
          "initialisms": []
        }
      }
    }
  ]
}
```
Yaml
```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "./sql"
    schema: "../migrations"
    gen:
      go:
        package: "dbquery"
        out: "pkg/sqlgen"
        initialisms:
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
