### ISSUE TITLE
Generate fails for UPDATE ... FROM (...) with subquery

### ISSUE THREAD

**Issue by AntonOcean** [sqlc-dev/sqlc#3341]
### Version

1.25.0

### What happened?

UPDATE statement with FROM subquery does not generate!

### Relevant log output

```shell
sqlc generate failed.
# package 
query.sql:23:14: column "id" does not exist
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: UpdateAuthor :exec
UPDATE authors SET name=subquery.name, bio=subquery.bio
FROM (SELECT id, name, bio
        FROM unnest($1::authors[])) AS subquery
WHERE authors.id = subquery.id;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/146482ad583aa6e0a2980b0d0feb5e6c42628406a3f44b1eadfd925278b341e0

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
