### ISSUE TITLE
Query "SELECT * FROM unnest(..)" has wrong generated code

### ISSUE THREAD

**Issue by AntonOcean** [sqlc-dev/sqlc#3342]
### Version

1.25.0

### What happened?

This is my expectation from SQL-query
<img width="575" alt="expectation" src="https://github.com/sqlc-dev/sqlc/assets/22237661/7ee782bf-2921-44db-bb30-321d10687fb0">
<br>
But this is a reality of SQLC generated code
<img width="591" alt="reality" src="https://github.com/sqlc-dev/sqlc/assets/22237661/e6ebad7a-ba26-4ccf-9410-93abc89b33e4">

### Relevant log output

```shell
const getAuthors = `-- name: GetAuthors :exec
SELECT unnest FROM unnest($1::authors[])
`
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: GetAuthors :exec
SELECT * FROM unnest($1::authors[]);
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/92a526ef05f1b3ec8c4dbc2360e1ff0c7cc27464a8b5870957166137b8e119af

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
