### ISSUE TITLE
Temp table created using schema.sql is not insertable.

### ISSUE THREAD

**Issue by adi-kmt** [sqlc-dev/sqlc#3345]
### Version

1.26.0

### What happened?

Even though the table seems to be created, its not able to insert into that table saying that the schema 'table' is not found.

### Relevant log output

```shell
schema not found
```

### SQL queries

```sql
CREATE TEMP TABLE temp_table (LIKE prev_table include ALL) ON COMMIT DROP;
INSERT INTO temp_table (...) VALUES (...)
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/query/"
    schema: "db/migrations/"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v5"
        out: "db/sqlc"
        emit_interface: true
        emit_json_tags: true
        emit_pointers_for_null_types: true
        emit_result_struct_pointers: true
        overrides:
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
