### ISSUE TITLE
underscore is not properly supported

### ISSUE THREAD

**Issue by xackery** [sqlc-dev/sqlc#3351]
### Version

1.26.0

### What happened?

A bug happened!

given a table such as:

```sql
CREATE TABLE `items` (
  `id` int(11) NOT NULL DEFAULT 0,
  `casttime` int(11) NOT NULL DEFAULT 0,
  `casttime_` int(11) NOT NULL DEFAULT 0,
  `charmfile` varchar(32) NOT NULL DEFAULT '',
  `charmfileid` varchar(32) NOT NULL DEFAULT '',
    UNIQUE KEY `ID` (`id`),
  KEY `name_idx` (`Name`),
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

models.go generates:
```go
	Casttime            int32
	Casttime            int32
```

Which is invalid go

### What operating system are you using?

Linux

### What database engines are you using?

MySQL

### What type of code are you generating?

Go

**Comment by xackery** [comment]
Found the fix.
```yaml
sql:
  - engine: "mysql"
    queries: "mysql-queries.sql"
    schema: "mysql-schemas.sql"
    gen:
      go:
        package: "mysqlc"
        out: "mysqlc"
        rename:
          casttime_: "CastTime2"
```

[ref link](<https://docs.sqlc.dev/en/stable/howto/rename.html>)
