### ISSUE TITLE
Missing columns not being detected

### ISSUE THREAD

**Issue by strackfeldt** [sqlc-dev/sqlc#3355]
### Version

1.26.0

### What happened?

Hi, missing columns not being detected when not using parameters

### Relevant log output

```shell
none
```

### Database schema

```sql
create table a (
	id BIGSERIAL primary key
);

create table b (
	id BIGSERIAL primary key
);
```

### SQL queries

```sql
-- name: Test :one
select
	*
from
	a
where
	does_not_exist = 'does_not_exist';

-- name: Test2 :one
select
	a.*
from
	a
	join b on a.does_not_exist = b.does_not_exist;

-- -- name: Test3 :one <- THIS GETS DETECTED
-- select
--	*
-- from
--	a
-- where
--	does_not_exist = $1;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/3c9631eb7dc7e42a6a8c8fa81ee16f51869089c4fbd0f4ae2304d5e801dda5b9

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
