### ISSUE TITLE
sql\queries\users.sql:1:1: relation "users" does not exist

### ISSUE THREAD

**Issue by kaliban2056** [sqlc-dev/sqlc#3372]
### Version

1.26.0

### What happened?

I encountered this error when I ran the command “sqlc generate”, this is the structure of the sql and yaml files.
![image](https://github.com/sqlc-dev/sqlc/assets/51584162/d5604a08-80a3-49da-b04d-47dd29efc726)

### Relevant log output

```shell
PS C:\Users\%USERNAME%\Documents\project_1> sqlc generate
# package 
sql\queries\users.sql:1:1: relation "users" does not exist
```

### Database schema

```sql
-- +goose up

CREATE TABLE users (
     id UUID PRIMARY KEY,
     created_at TIMESTAMP NOT NULL,
     updated_at TIMESTAMP NOT NULL,
     name TEXT NOT NULL
);

-- +goose down

DROP TABLE USERS;
```

### SQL queries

```sql
-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name)
VALUES ($1, $2, $3, $4)
RETURNING *;
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "sql/schema"
    queries: "sql/queries"
    engine: "postgresql"
    gen:
      go:
        out: "internal/database"
```

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
