### ISSUE TITLE
Views models do not get updated when base tables are altered

### ISSUE THREAD

**Issue by tjlevel12** [sqlc-dev/sqlc#3374]
### Version

1.22.0

### What happened?

I'm seeing this in `1.22` locally, but I've tested it in `1.25` in the playground.

If you create a view that uses `select *`, the generated model for that view does not get updated when the base tables are altered.

In the attached playground link, I'd expect the structures of the `Author` and `AuthorsView` types to be the same.

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);

CREATE VIEW authors_view AS select * from authors;

ALTER TABLE authors ADD COLUMN foo text;
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors_view
WHERE id = $1 LIMIT 1;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/cc18541c6f9abb2ac15ebde4a91eec5f8d0bc85c0669e5cfb93616a3f1263a6e

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
