### ISSUE TITLE
wrong type for params in tuple

### ISSUE THREAD

**Issue by ehsangifani** [sqlc-dev/sqlc#3377]
### Version

1.26.0

### What happened?

The type for `id` is detected wrong.

```go
type ListTasksParams struct {
	CreateTime   pgtype.Timestamptz
	CreateTime_2 pgtype.Timestamptz
	Limit        int32
	Offset       int32
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
```

I expected it to be:
```go
type ListTasksParams struct {
	CreateTime   pgtype.Timestamptz
	IDorSth int64
	Limit        int32
	Offset       int32
}
```

### Database schema

```sql
create table tasks (
	id bigint generated by default as identity primary key,
	info text,
	create_time timestamp with time zone not null default current_timestamp
);
```

### SQL queries

```sql
select * from tasks
where
	(create_time, id) > ($1, $2)
order by create_time, id
limit $3 offset $4;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "dbgw"
        out: "dbgw"
        sql_package: "pgx/v5"
```

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
