### ISSUE TITLE
failed to encode args[2]: unable to encode &geom.Point{geom0:geom.geom0{layout:1, stride:2, flatCoords:[]float64{38.8951, 77.0364}, srid:0}} into text format for unknown type (OID 17977): cannot find encode plan

### ISSUE THREAD

**Issue by lewisd1996** [sqlc-dev/sqlc#3462]
### Version

1.26.0

### What happened?

I am trying to simply store geometry data using postgis.

The insert currently does not work. I have tried following https://docs.sqlc.dev/en/stable/reference/datatypes.html#using-github-com-twpayne-go-geom but currently failing to insert into my DB.

### Relevant log output

```shell
failed to encode args[2]: unable to encode &geom.Point{geom0:geom.geom0{layout:1, stride:2, flatCoords:[]float64{38.8951, 77.0364}, srid:0}} into text format for unknown type (OID 17977): cannot find encode plan
```

### Database schema

```sql
-- name: CreateObservation :exec
INSERT INTO "observation" (
    "user_id", 
    "facility_name", 
    "location"
    )
VALUES (
    $1, 
    $2,
    $3
    );

-- name: GetObservationByID :one
SELECT * FROM "observation"
WHERE "id" = $1 LIMIT 1;

-- name: GetObservationsByUserID :many
SELECT * FROM "observation"
WHERE "user_id" = $1;


// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: observation.sql

package pgsqlc

import (
	"context"

	go_geom "github.com/twpayne/go-geom"
)

const createObservation = `-- name: CreateObservation :exec
INSERT INTO "observation" (
    "user_id", 
    "facility_name", 
    "location"
    )
VALUES (
    $1, 
    $2,
    $3
    )
`

type CreateObservationParams struct {
	UserID       int64
	FacilityName string
	Location     *go_geom.Point
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) error {
	_, err := q.db.Exec(ctx, createObservation, arg.UserID, arg.FacilityName, arg.Location)
	return err
}

const getObservationByID = `-- name: GetObservationByID :one
SELECT id, uid, user_id, location, created_at, facility_name FROM "observation"
WHERE "id" = $1 LIMIT 1
`

func (q *Queries) GetObservationByID(ctx context.Context, id int64) (Observation, error) {
	row := q.db.QueryRow(ctx, getObservationByID, id)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.UID,
		&i.UserID,
		&i.Location,
		&i.CreatedAt,
		&i.FacilityName,
	)
	return i, err
}

const getObservationsByUserID = `-- name: GetObservationsByUserID :many
SELECT id, uid, user_id, location, created_at, facility_name FROM "observation"
WHERE "user_id" = $1
`

func (q *Queries) GetObservationsByUserID(ctx context.Context, userID int64) ([]Observation, error) {
	rows, err := q.db.Query(ctx, getObservationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.UID,
			&i.UserID,
			&i.Location,
			&i.CreatedAt,
			&i.FacilityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

### SQL queries

```sql
-- name: CreateObservation :exec
INSERT INTO "observation" (
    "user_id", 
    "facility_name", 
    "location"
    )
VALUES (
    $1, 
    $2,
    $3
    );

-- name: GetObservationByID :one
SELECT * FROM "observation"
WHERE "id" = $1 LIMIT 1;

-- name: GetObservationsByUserID :many
SELECT * FROM "observation"
WHERE "user_id" = $1;
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "db/postgres/migration"
    queries: "db/postgres/query"
    engine: "postgresql"
    gen:
      go:
        package: "pgsqlc"
        out: "internal/infrastructure/persistence/pgsqlc"
        sql_package: "pgx/v5"
        emit_json_tags: false
        emit_interface: true
        emit_empty_slices: true
        rename:
          uid: "UID"
          client_ip: "ClientIP"
        overrides:
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "timestamptz"
            go_type: "time.Time"
            nullable: true
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"
            nullable: true
          - db_type: "geometry"
            go_type:
              import: "github.com/twpayne/go-geom"
              pointer: true
              type: "Point"
          - db_type: "geometry"
            go_type:
              import: "github.com/twpayne/go-geom"
              pointer: true
              type: "Point"
            nullable: true
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
