### ISSUE TITLE
sqlc generate error parsing configuration files. sqlc.(yaml|yml) or sqlc.json: file does not exist

### ISSUE THREAD

**Issue by JuanVargas** [sqlc-dev/sqlc#3475]
### Version

1.26.0

### What happened?

I am running Linux/Ubuntu 22.04.4 LTS   with Go version is 1.22.4

I installed sqlc 1.26 by issuing the command     go get github.com/sqlc-dev/sqlc/cmd/sqlc

I created the sqlc.ymal with the content from https://docs.sqlc.dev/en/stable/reference/config.html 

See below

When I issue the command 

sqlc generate

I get the error message

error parsing configuration files. sqlc.(yaml|yml) or sqlc.json: file does not exist.

I repeated the setup in a different directory, this time getting sqlc via

sudo snap install sqlc.

Same result

### Relevant log output

```shell
error parsing configuration files. sqlc.(yaml|yml) or sqlc.json: file does not exist.
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name text    NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = ? LIMIT 1;

-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;

-- name: CreateAuthor :execresult
INSERT INTO authors (
  name, bio
) VALUES (
  ?, ?
);

-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = ?;
```

### Configuration

```yaml
version: "2"
cloud:
  project: "<PROJECT_ID>"
sql:
- schema: "postgresql/schema.sql"
  queries: "postgresql/query.sql"
  engine: "postgresql"
  gen:
    go: 
      package: "authors"
      out: "postgresql"
  database:
    managed: true
  rules:
    - sqlc/db-prepare
- schema: "mysql/schema.sql"
  queries: "mysql/query.sql"
  engine: "mysql"
  gen:
    go:
      package: "authors"
      out: "mysql"
```
