### ISSUE TITLE
emoji in queries generate broken queries

### ISSUE THREAD

**Issue by josharian** [sqlc-dev/sqlc#3478]
### Version

1.26.0

### What happened?

In query.sql:

```sql
-- name: EmojiOops :exec
SELECT
    '🤷' AS emoji
limit
    1;
```

Generated in query.sql.go:

```go
const emojiOops = `-- name: EmojiOops :exec
SELECT
    '🤷' AS emoji
limit
`
```

Observe the missing `1;` at the end. Looks like somebody is counting bytes instead of runes?

Yes, this happened in real code. It was pretty confusing to debug.

Appears to be happen with some dbs and not others? Didn't dig much.

### Configuration

```yaml
---
version: 2
sql:
  - engine: sqlite
    schema: schema.sql
    queries: query.sql
    gen:
      go:
        package: [redacted]
        out: .
        emit_exact_table_names: true
        emit_result_struct_pointers: true
        emit_params_struct_pointers: true
        query_parameter_limit: 3
        output_db_file_name: sqlc.go
```

### Playground URL

https://play.sqlc.dev/p/984f440606d6a2084f363f711e283a31b031901ea70d613a250636784d5cad33

### What operating system are you using?

Linux, macOS

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
