### ISSUE TITLE
bad query param structs generated for columns allowing null

### ISSUE THREAD

**Issue by jason-gigastar** [sqlc-dev/sqlc#3488]
### Version

1.26.0

### What happened?

I'm having difficulty supporting a mix of columns that are either optional or required with a mix of either null or not null.

A parameter in a nullable column update has 3 cases, where a `time.Time` can be represented as a `**time.Time` to allow:
1) not set       (`nil`)
2) set to `null` (`&nilPtr`)
3) set to value  (`&valuePtr`)

Given these overrides, sqlc generates structs with the correct types:
```yaml
version: "2"
sql:
  - engine: "postgresql"
   #... lines omitted
    gen:
      go:
        package: "db"
        out: "pkg/db/sqlc"
        sql_package: "pgx/v5"
        emit_pointers_for_null_types: true
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "timestamptz"
            nullable: true
            go_type: "*time.Time"
          - db_type: "pg_catalog.timestamptz"
            go_type: "time.Time"
          - db_type: "pg_catalog.timestamptz"
            nullable: true
            go_type: "*time.Time"
```
```sql
CREATE TABLE IF NOT EXISTS table1 (
    field1 TIMESTAMPZ NOT NULL,
);
```
```go
type CreateTable1Params struct {
    Field1 time.Time
}
type PatchTable1Params struct {
    Field1 *time.Time
}
```

However, if I introduce a field allowing `null` values I get bad results:
```sql
CREATE TABLE IF NOT EXISTS table1 (
    field1 TIMESTAMPZ NOT NULL,
    field2 TIMESTAMPZ
);
```
```go
type CreateTable1Params struct {
    Field1 time.Time
    Field2 *time.Time
}
type PatchTable1Params struct {
    Field1 *time.Time
    Field2 *time.Time // bad: type should be **time.Time, current type only allows 2 cases
}
```

I tried the following and get different bad/awkward results:
```yaml
version: "2"
sql:
  - engine: "postgresql"
   #... lines omitted
    gen:
      go:
        package: "db"
        out: "pkg/db/sqlc"
        sql_package: "pgx/v5"
        emit_pointers_for_null_types: true
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "timestamptz"
            nullable: true
            go_type: "*time.Time"
          - db_type: "pg_catalog.timestamptz"
            go_type: "time.Time"
          - db_type: "pg_catalog.timestamptz"
            nullable: true
            go_type: "*time.Time"
          - db_type: "null_time"
            go_type: "database/sql.NullTime"
          - db_type: "null_time"
            nullable: true
            go_type: "*database/sql.NullTime"
```
```sql
CREATE DOMAIN NULL_TIME AS TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS table1 (
    field1 TIMESTAMPZ NOT NULL,
    field2 NULL_TIME
);
```
```go
type CreateTable1Params struct {
    Field1 time.Time
    Field2 *sql.NullTime // awkward: should be simply sql.NullTime but it could work..
}
type PatchTable1Params struct {
    Field1 *time.Time
    Field2 *sql.NullTime // good: allows 3 cases mentioned above
}
```

Next I tried settling for the beginning of the epoch as a replacement for a null time but again, different bad/awkward results:
```yaml
version: "2"
sql:
  - engine: "postgresql"
   #... lines omitted
    gen:
      go:
        package: "db"
        out: "pkg/db/sqlc"
        sql_package: "pgx/v5"
        emit_pointers_for_null_types: true
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "timestamptz"
            nullable: true
            go_type: "*time.Time"
          - db_type: "pg_catalog.timestamptz"
            go_type: "time.Time"
          - db_type: "pg_catalog.timestamptz"
            nullable: true
            go_type: "*time.Time"
```
```sql
CREATE TABLE IF NOT EXISTS table1 (
    field1 TIMESTAMPZ NOT NULL,
    field2 TIMESTAMPTZ NOT NULL DEFAULT 'epoch'::timestamptz
);
```
```go
type CreateTable1Params struct {
    Field1 time.Time
    Field2 time.Time
}
type PatchTable1Params struct {
    Field1 *time.Time
    Field2 **time.Time // awkward: Should be *time.Time but could work..
}
```
In this last struct it's strange that it seems to be matching the nullable time override as the column is "NOT NULL".

Probably unrelated to this issue but some other odd things I've noticed:
1) the `db_type` in the override is case sensitive, I had to use lowercase
2) the override for `timestampz` requires a mix of `timestampz` and `pg_catalog.timestampz` overrides. The `timestampz` override seems sufficient in many cases but for `insert` parsing the `pg_catalog.timestampz` was required. I tried cooercing the types like in the next item but then the field name in the generated type would be lost and result in something generic.
3) with custom types my `update` queries required something like this for proper type detection: `field2 = coalesce($3::null_time, field2)` and I've also tried `field2 = coalesce(sqlc.narg('field2')::null_time, field2)` but I've settled on the shorter option for all types in `update` queries

### Database schema

```sql
See problem description in "What happened" section
```

### SQL queries

```sql
See problem description in "What happened" section
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
