### ISSUE TITLE
parsing of configuration file fails (sqlc.yaml)

### ISSUE THREAD

**Issue by calbch** [sqlc-dev/sqlc#3492]
### Version

1.26.0

### What happened?

I tried to switch to use the [enhanced analysis](https://docs.sqlc.dev/en/latest/howto/generate.html#enhanced-analysis-with-managed-databases) in order to be able to use multiple CTE's. In following the docs I added the `servers` config to the `sqlc.yaml`. I then encountered

```
error parsing sqlc.yaml: yaml: unmarshal errors:
  line 2: field servers not found in type config.Config
```

In order to make sure that it is not a problem with my local setup I tried to use
`docker run --rm -v $(pwd):/src -w /src sqlc/sqlc generate` with the config provided in the docs
```yaml
version: '2'
servers:
- engine: postgresql
  uri: ${DATABASE_URI}
sql:
- schema: schema.sql
  queries: query.sql
  engine: postgresql
  database:
    managed: true
```

The error message is still the same.

### Relevant log output

```shell
docker run --rm -v $(pwd):/src -w /src sqlc/sqlc generate
error parsing sqlc.yaml: yaml: unmarshal errors:
  line 2: field servers not found in type config.Config
```
```


### Database schema

```sql
Not necessarily important here, since the parsing of the config fails.
```

### Configuration

```yaml
initial


version: '2'
servers:
- engine: postgresql
  uri: ${DATABASE_URL}
sql:
  - engine: postgresql
    queries: "/db/query/"
    schema: "/db/schema/"
    database:
      managed: true
    gen:
      go:
        package: "db"
        out: "db"
        sql_package: "pgx/v5"
        rename:
          lower: "Name" # rename the struct field for user name insertion
        overrides:
          - column: "lenges.schedule"
            go_type:
              import: "lenge-backend/lenge/model"
              type: "Schedule"


to verify:
```yaml
version: '2'
servers:
- engine: postgresql
  uri: ${DATABASE_URI}
sql:
- schema: schema.sql
  queries: query.sql
  engine: postgresql
  database:
    managed: true
```
```


### Playground URL

_No response_

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
