### ISSUE TITLE
Non-nullable parameters generated when using overridden type + sqlc.narg + COALESCE

### ISSUE THREAD

**Issue by bbkane** [sqlc-dev/sqlc#3494]
### Version

1.26.0

### What happened?

I've got a SQLite table with a TEXT data type called create_time . I update create_time with the following update query:

```sql
-- See https://docs.sqlc.dev/en/latest/howto/named_parameters.html#nullable-parameters
-- name: EnvUpdate :exec
UPDATE env SET
    create_time = COALESCE(sqlc.narg('create_time'), create_time)
WHERE id = sqlc.arg('id');
```

This works fine and generates an update query parameter with a string pointer as I expect when using `sqlc.narg`:

```go
type EnvUpdateParams struct {
	CreateTime *string
	ID         int64
}
```

 However, if I create the type `type SQLiteTime string` and set create_time to use this type in sqlc.yaml (which I would like to do so I can attach methods to the type), the generated update code does NOT use a pointer as I expect:
 
 ```go
type EnvUpdateParams struct {
	CreateTime sqlite.SQLiteTime
	ID         int64
}
```

I would expect it to look like:

```go
type EnvUpdateParams struct {
	CreateTime *sqlite.SQLiteTime
	ID         int64
}
```

Not having it be a pointer means I can't assign `nil` to it, which breaks my `COALESCE` SQL update query.

As a full reproducible demo of this bug, I've made https://github.com/bbkane/sqlc-override-nullable . It has a `using-text` package that demos the correct codegen, and a `using-overrides` that demos the incorrect codegen.

Some more context about WHY I'd like to be able to to this:

I'm writing an [environment variable manager CLI](https://github.com/bbkane/envelope) that needs to store times. Instead of the ["sqlc-native"](https://docs.sqlc.dev/en/stable/reference/datatypes.html#dates-and-times) format as a stringified `time.Time`, I want to store times in the ["sqlite-native"](https://www.sqlite.org/lang_datefunc.html#tmval) format as a text column so I can run datetime queries on the columns.

Finally, thank you so much for writing sqlc! I've started GitHub sponsoring you because this tool removes a lot of the drudgery of working with SQL from Go, and I really appreciate that.

### Database schema

```sql
CREATE TABLE env (
    id INTEGER PRIMARY KEY,
    create_time TEXT NOT NULL
) STRICT;
```

### SQL queries

```sql
-- See https://docs.sqlc.dev/en/latest/howto/named_parameters.html#nullable-parameters
-- name: EnvUpdate :exec
UPDATE env SET
    create_time = COALESCE(sqlc.narg('create_time'), create_time)
WHERE id = sqlc.arg('id');
```

### Configuration

```yaml
sql:
  - engine: sqlite
    gen:
      go:
        emit_pointers_for_null_types: true
        out: sqlcgen
        package: sqlcgen
        overrides:
          - column: "env.create_time"
            go_type: "go.bbkane.com/sqlc-override-nullable/using-override/sqlite.SQLiteTime"
    queries: queries
    schema: migrations
# yq wants to double quote "2", but yamllint wants it single-quoted
# yamllint disable-line rule:quoted-strings
version: "2"
```

### What operating system are you using?

Linux, macOS

### What database engines are you using?

SQLite

### What type of code are you generating?

Go

**Comment by bogdanoff2049** [comment]
Hi, facing the same issue here, bumping this

**Comment by bbkane** [comment]
I haven't made time to try it yet, but [bob](https://github.com/stephenafamo/bob) is supposed to be able to handle this. Please let me know how it goes if you decide to try it @bogdanoff2049 

https://www.reddit.com/r/golang/s/wJAr5Hgi7O

**Comment by bogdanoff2049** [comment]
oh i found out the reason for my issue, i did not add in the pointer type for my conversion
```
          - db_type: "custom_type"
            go_type:
              import: "pkg/api"
              type: "CustomType"
          - db_type: "custom_type"
            nullable: true
            go_type:
              import: "pkg/api"
              type: "CustomType"
              pointer: true
```

**Comment by bbkane** [comment]
Ooh I'll try that!

**Comment by maddsua** [comment]
For me it basically boils down to sqlc ignoring an override for a nullable option and only generating the normal variant.

Config:
```yml
- column: "bucket_entries.bucket_id"
  go_type:
    import: "github.com/google/uuid"
    type: "UUID"
- column: "bucket_entries.bucket_id"
  nullable: true
  go_type:
    import: "github.com/google/uuid"
    type: "NullUUID"
```

I guess I'm not doing it right? Just seems strange that nullables get ignored in this case, as `sqlc.narg` would be the first thing I thought of as a use case.
