### ISSUE TITLE
Same parameter used multiple times not respected when using PgVector with pgx (Postgres)

### ISSUE THREAD

**Issue by rob2244** [sqlc-dev/sqlc#3496]
### Version

1.26.0

### What happened?

When using the same numbered parameter multiple times in the same statement, or when using sqlc.arg or sqlc.narg with the same parameter name with a PgVector Vector type, the parameter is output in the generated struct multiple times.

The expectation is that the parameter is generated in the struct only once and used multiple times in the SQL. It seems to only be a problem with PgVector and is working correctly with other data types.

### Database schema

```sql
CREATE TABLE IF NOT EXISTS client_portal.public.glossary (
    id SERIAL primary key,
    org_id uuid NOT NULL,
    user_id uuid NOT NULL,
    term varchar NOT NULL,
    definition varchar NOT NULL,
    tags varchar,
  	term_embedding vector(1024),
    tags_query tsquery,
    created_date timestamp DEFAULT (now() at time zone 'utc'),
    updated_date timestamp DEFAULT (now() at time zone 'utc'),
    UNIQUE(org_id, user_id, term)
);
```

### SQL queries

```sql
-- name: SearchGlossaryByEmbedding :many
SELECT
	id,
	term,
	definition,
	tags
FROM glossary
WHERE 1 - (term_embedding <=> $1) >= $2
	AND org_id = $3
ORDER BY 1 - (term_embedding <=> $1) DESC
LIMIT $4;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "/pkg/dal/queries/"
    schema: "migrations/"
    gen:
      go:
        package: "dal"
        out: "pkg/dal/sqlc"
        sql_package: "pgx/v5"
```

### Playground URL

https://play.sqlc.dev/p/ef4803670b12447e6b7b3bb4330920573dd2e1f32fbf0262657355baec04dd84

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
