### ISSUE TITLE
Renaming generated struct from a query that selects from multiple tables

### ISSUE THREAD

**Issue by jacob-winkler** [sqlc-dev/sqlc#3504]
### Version

1.26.0

### What happened?

I have a query like
```
-- name: MembersWithExternalId :many
SELECT m.*, mp.external_id
FROM member m
INNER JOIN member_provider mp ON mp.member_id = m.id;
```

This generates a query and struct like `MembersWithExternalIdRow`

I want to rename this generated struct to be `ExternalMember`

I've tried using the config rename to do this in many different forms, but none of the rename configs are working.
```
overrides:
  go:
    rename:
      members_with_external_id_row: "ExternalMember"
      memberswithexternalidrow: "ExternalMember"
      members_with_external_id: "ExternalMember"
      memberswithexternalid: "ExternalMember"
```

### SQL queries

```sql
-- name: MembersWithExternalId :many
SELECT m.*, mp.external_id
FROM member m
INNER JOIN member_provider mp ON mp.member_id = m.id;
```

### Configuration

```yaml
overrides:
  go:
    rename:
      members_with_external_id_row: "ExternalMember"
      memberswithexternalidrow: "ExternalMember"
      members_with_external_id: "ExternalMember"
      memberswithexternalid: "ExternalMember"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
