### ISSUE TITLE
upset with arg or narg doesn't work in sqlite3

### ISSUE THREAD

**Issue by yopoyka** [sqlc-dev/sqlc#3508]
### Version

1.25.0

### What happened?

sqlc fails to generate query placeholders and leaves `@arg` `sqlc.arg` `sqlc.narg` in generated query when doing upsert.
Doesn't output any errors.
Possibly related to #1881 

Generated code from playground
```go
const upsertAuthor = `-- name: UpsertAuthor :one
insert into authors (
  "id",
  "name",
  "bio"
) values (
  ?1,
  ?2,
  ?3
) on conflict("id") do update set
  "name" = @name,
  "bio" = sqlc.narg('bio')
returning id, name, bio
`
```

### Database schema

```sql
create table authors (
  id   text primary key,
  name text not null,
  bio  text
);
```

### SQL queries

```sql
-- name: UpsertAuthor :one
insert into authors (
  "id",
  "name",
  "bio"
) values (
  @id,
  @name,
  sqlc.narg('bio')
) on conflict("id") do update set
  "name" = @name,
  "bio" = sqlc.narg('bio')
returning *;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "sqlite",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/4b01c7bd73781a3aeaf17fa1c9fba826640a5907f97b2faaee51ccac9197d00e

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
