### ISSUE TITLE
Enum array gets output as []interface{}

### ISSUE THREAD

**Issue by knpwrs** [sqlc-dev/sqlc#3511]
### Version

1.26.0

### What happened?

When I select an enum array column in Postgres (pgx) with sqlc the generated type for that column is `[]interface{}`. For some reason this doesn't reproduce in the playground.

I came across this issue but I am new to Go and I'm not quite sure what to do with this code, or if it is even relevant to the issue I am seeing: https://github.com/sqlc-dev/sqlc/issues/2116#issuecomment-1493299852

### Database schema

```sql
CREATE TYPE upload_variant AS ENUM (
    'VIDEO_4K',
    'VIDEO_4K_DOWNLOAD',
    'VIDEO_1080P',
    'VIDEO_1080P_DOWNLOAD',
    'VIDEO_720P',
    'VIDEO_720P_DOWNLOAD',
    'VIDEO_480P',
    'VIDEO_480P_DOWNLOAD',
    'VIDEO_360P',
    'VIDEO_360P_DOWNLOAD',
    'AUDIO',
    'AUDIO_DOWNLOAD'
);

CREATE TABLE upload (
  id   BIGSERIAL PRIMARY KEY,
  variants upload_variant[]
);
```

### SQL queries

```sql
-- name: GetUploads :many
SELECT * FROM upload;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "./app/data"
    database:
      uri: ${DATABASE_URL}
    gen:
      go:
        package: "data"
        out: "./app/data"
        sql_package: "pgx/v5"
```

### Playground URL

https://play.sqlc.dev/p/e60a8ebfe202c5a91bdaaee9b3aef12b085f188ceec8e62b4503c59c6f1d553c

### What operating system are you using?

Linux, macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
