### ISSUE TITLE
update table from select another table cause error

### ISSUE THREAD

**Issue by cytown** [sqlc-dev/sqlc#3515]
### Version

1.26.0

### What happened?

First time I tried field name "id" in both table, it's very common in realworld, but it said "id" is ambiguous, so I change the id to bid in second table, but still get wrong...

Also tried sqlc.args(xxx), but will failed either.

For your reference, the sql clause should not failed.
 

### Relevant log output

```shell
sqlc generate failed.
# package 
query.sql:6:40: column reference "bid" is ambiguous
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);


CREATE TABLE authors2 (
  bid   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: CreateAuthor2 :one
UPDATE authors SET (
  name, bio
) = (
  select name, bio from authors2 where bid=$2
) where id=$1
RETURNING *;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/3ef93462e0cc926c18e7d79bbdd1ce8239fe3b1c4afed1026cd357502a8c7adf

### What operating system are you using?

Linux, macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by ed-henrique** [comment]
Similar problem here, but with a different input:
### Version

1.26.0

### Relevant log output

```
# package db
queries/queries.sql:5:7: column reference "id" is ambiguous
```

From playground:

```
sqlc generate failed.

2024/08/08 15:33:36 sqlite.convertLiteral: Unknown node type *parser.Expr_literalContext
2024/08/08 15:33:36 sqlite.convertLiteral: Unknown node type *parser.Expr_literalContext
2024/08/08 15:33:36 sqlite.convert(case=default): Unknown node type *parser.Expr_unaryContext
# package 
query.sql:5:7: column reference "id" is ambiguous
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER PRIMARY KEY,
  DOCUMENT INTEGER,
  REMOVED_AT TEXT,
  FOREIGN KEY (DOCUMENT) REFERENCES DOCUMENTS (ID)
);

CREATE TABLE IF NOT EXISTS DOCUMENTS (
  ID INTEGER PRIMARY KEY,
  REMOVED_AT TEXT
);
```

### SQL queries

```sql
-- name: RemoveDocument :execrows
UPDATE DOCUMENTS
SET
  removed_at = CURRENT_TIMESTAMP
WHERE id = ?1
  AND removed_at IS NULL
  AND id NOT IN (SELECT document FROM USERS WHERE document IS NOT NULL);
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "sqlite"
    queries: "./queries"
    schema: "./migrations"
    gen:
      go:
        out: "."
        package: "db"
```

### Playground URL

https://play.sqlc.dev/p/906eac25119af6f519b77983cfe4a67e5aa41465e76dbcdbe08af6c8b5b033e3

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go

**Comment by dimmerz92** [comment]
Also having this issue, as above, tried aliasing to no avail.

## Version
v1.27.0

## Relevant log output
```
line 71:2 no viable alternative at input 'UPDATE\n\tEvents AS e\nSET\n\te.'
line 78:3 no viable alternative at input 'Entries'
# package models
sql/queries/events.sql:1:1: no viable alternative at input 'Entries'
```

## Database schema
```sql
-- +goose Up
CREATE TABLE IF NOT EXISTS Events (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	Description TEXT NOT NULL,
	Visible INTEGER NOT NULL DEFAULT (1) CHECK (Visible IN (0, 1)),
	Location TEXT REFERENCES Locations(Name),
	EventDateTime INTEGER NOT NULL CHECK (EventDateTime > strftime('%s', 'now')),
	CreatedAt INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
	UpdatedAt INTEGER
) STRICT;

-- +goose Up
CREATE TABLE IF NOT EXISTS Entries (
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	Description TEXT,
	UserId TEXT NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
	EventId INTEGER NOT NULL REFERENCES Events(Id) ON DELETE CASCADE,
	Category TEXT NOT NULL REFERENCES Categories(Name) ON DELETE CASCADE,
	Score INTEGER CHECK (Score BETWEEN 0 AND 10),
	CreatedAt INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
	UpdatedAt INTEGER
) STRICT;
```

## SQL queries
```sql
-- name: ToggleEventVisibility :one
UPDATE
	Events AS e
SET
	e.Visible = 1 - e.Visible
WHERE
	e.Id = ? AND
	e.Id NOT IN (
		SELECT DISTINCT
			t.EventId
		FROM
			Entries AS t
	)
RETURNING
	COUNT(*);
```

## Configuration
```yaml
version: "2"
sql:
  - engine: "sqlite"
    queries: "./sql/queries/*"
    schema: "./sql/schema"
    gen:
      go:
        package: "models"
        out: "./internal/models"
```

## Playground URL
https://play.sqlc.dev/p/c8f1b46ed9a1b6cdf7a2ccecd1ec32b79aa1cdee3d8e80f4b1b5f6c7ec1ba3f6

## What operating system are you using?
**OS 1:**
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

**OS 2:**
Apple M1
ProductName:    macOS
ProductVersion: 14.5
BuildVersion:   23F79

## What database engines are you using?
SQLite

## What type of code are you generating?
Go
