### ISSUE TITLE
Incorrect sqlc header version generation using docker.io/sqlc/sqlc:1.26.0 image

### ISSUE THREAD

**Issue by kyleconroy** [sqlc-dev/sqlc#3523]
### Discussed in https://github.com/sqlc-dev/sqlc/discussions/3389

<div type='discussions-op-text'>

<sup>Originally posted by **phil535** May 17, 2024</sup>
Running sqlc version 1.26.0 using docker [image](https://hub.docker.com/layers/sqlc/sqlc/1.26.0/images/sha256-c1f0b5dc0420269543bb558f5d41933aa684c07df866cfe5d880e55167ecefed?context=explore) generates wrong  sqlc version header.

![sqlc1 26](https://github.com/sqlc-dev/sqlc/assets/7596830/7e5c7348-61c7-4c8d-a206-6e0bfc1e7c1d)

Command:
`docker run --rm --user $UID:$GID --volume ./:/src --workdir /src sqlc/sqlc:1.26.0 generate`

I used the postgres tutorial example for input but the input should not matter.

This is my sqlc config:

``` yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "*.sql"
    schema: "*.sql"
    gen:
      go:
        package: "tutorial"
        out: "tutorial"
        sql_package: "pgx/v5"

```

The sqlc 1.26.0 [release](https://github.com/sqlc-dev/sqlc/releases/tag/v1.26.0) with the same config and input works as expected.

Is there anything i missed? Do you have the same behavious with that image from docker.io?</div>
