### ISSUE TITLE
sqlite generation fails with column does not exist

### ISSUE THREAD

**Issue by cyberbeast** [sqlc-dev/sqlc#3533]
### Version

1.27.0

### What happened?

See https://play.sqlc.dev/p/2a3e654eb38e3f41b755dae51c6aa521a639eec925e4fec1cdf8455152754907 for error. Something about the CreateDoc query doesn't sit well with the compiler.

### Database schema

```sql
CREATE TABLE docs (
  id          text  primary key
  htmlcontent text  not null
  textcontent text  not null
);
```

### SQL queries

```sql
-- name: GetDoc :one
SELECT * FROM docs
WHERE id = ? LIMIT 1;

-- name: CreateDoc :one
INSERT INTO docs (
  id, 
  htmlcontent,
  textcontent
) VALUES (
  ?, ?, ?
)
RETURNING *;

-- name: DeleteDoc :exec
DELETE FROM docs
WHERE id = ?;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "sqlite",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/2a3e654eb38e3f41b755dae51c6aa521a639eec925e4fec1cdf8455152754907

### What operating system are you using?

macOS

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
