### ISSUE TITLE
Overridden type works for ARRAY of objects but not for a single object

### ISSUE THREAD

**Issue by kayshav** [sqlc-dev/sqlc#3534]
### Version

1.27.0

### What happened?

Have a simple ddl for an object in postgres. It uses a TYPE both as an ARRAY and also as a simple object. The sqlc.yaml has an override to map the TYPE (see sqlc.yaml).  In the generated code, the ARRAY is mapped correctly to the overridden type but the simple object is mapped to sql.NullString.

### Relevant log output

```shell
In the generated code, we see:

type FleetmanagerSchemaTag struct {
        CreateDate pgtype.Timestamp
        ID         int64
        Name       string
        Owner      sql.NullString
        Devices    []common.ObjRef
}
Notice that the Devices element is mapped to []ObjRef correctly but the Owner element is mapped to NullString. And both are of type ObjRef
```

### Database schema

```sql
ddls.sql
-- Create schema for fleet manager. Subject to change before going to production
CREATE SCHEMA fleetmanager_schema;

-- Add schema to search path
SET search_path TO fleetmanager_schema, public;


-- Using a domain to ensure that the obj_id and obj_type that are declared in a type are not null
CREATE DOMAIN nonnull_string VARCHAR(255) NOT NULL;
CREATE DOMAIN nonull_int8 int8 NOT NULL;

CREATE TYPE fleetmanager_schema.obj_ref AS  (
    obj_id nonnull_int8,
    obj_type nonnull_string
);




CREATE TABLE fleetmanager_schema.tag (
   create_date TIMESTAMP DEFAULT NOW() NOT NULL,
   id int8 NOT NULL,
    PRIMARY KEY (id),

   name VARCHAR(255) NOT NULL,
   owner fleetmanager_schema.obj_ref,
   devices fleetmanager_schema.obj_ref ARRAY
);
```

### SQL queries

```sql
-----------------queries.sql
-- name: InsertTag :one
INSERT INTO fleetmanager_schema.tag (
    create_date,  name, name,  owner, devices
) VALUES (
             $1, $2, $3, $4, $5
         ) RETURNING *;

-- name: GetTag :one
SELECT *
FROM fleetmanager_schema.tag
WHERE id = $1;
```

### Configuration

```yaml
------sqlc.yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "./queries.sql"
    schema: "./ddls.sql"
    gen:
      go:
        package: "db"
        out: "./generated"
        sql_package: "pgx/v5"
        overrides:
          - go_type:
              import: "fleet-api-server/generated/common"
              type: "ObjRef"
            db_type: "fleetmanager_schema.obj_ref"
            null: false
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
