### ISSUE TITLE
column "ordinality" does not exist  when generating golang code

### ISSUE THREAD

**Issue by blanc42** [sqlc-dev/sqlc#3540]
### Version

1.26.0

### What happened?

```sql
JOIN LATERAL (
      SELECT ordinality AS ord
      FROM jsonb_array_elements_text(p.variants) WITH ORDINALITY
      WHERE value = v.id::text
) idx ON true
 ```
 
 get_multiple_products.sql:99:21: column "ordinality" does not exist   
 
 the whole query worked used directly with the database

### Relevant log output

```shell
get_multiple_products.sql:99:21: column "ordinality" does not exist
```

### Database schema

```sql
JOIN LATERAL (
      SELECT ordinality AS ord
      FROM jsonb_array_elements_text(p.variants) WITH ORDINALITY
      WHERE value = v.id::text
) idx ON true
```

### SQL queries

```sql
JOIN LATERAL (
      SELECT ordinality AS ord
      FROM jsonb_array_elements_text(p.variants) WITH ORDINALITY
      WHERE value = v.id::text
) idx ON true
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "./pkg/db/query/"
    schema: "./pkg/db/schema/"
    gen:
      go:
        package: "db"
        out: "./pkg/db/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_prepared_queries: false
        emit_interface: false
        emit_exact_table_names: false
        overrides:
          - db_type: "jsonb"
            nullable: true
            engine: "postgresql"
            go_type:
              import: "encoding/json"
              type: "RawMessage"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
