### ISSUE TITLE
public.vector doesn't emit pgvector.Vector

### ISSUE THREAD

**Issue by newhook** [sqlc-dev/sqlc#3548]
### Version

1.26.0

### What happened?

My schema, generated from pg_dump, has:
```
embedding public.vector(1536)
```

This generates `interface{}` which won't scan correctly. Whereas 

```
embedding vector(1536)
```

Generates `pgvector.Vector` which does.

**Comment by spa5k** [comment]
Yeah, faced the same issue, change public.vector to vector works, also overriding it does not work in the sqlc

```yml
    gen:
      go:
        sql_package: "pgx/v5"
        out: "internal/database/models"
        package: "models"
        emit_db_tags: true
        emit_exported_queries: false
        emit_json_tags: true
        emit_prepared_queries: true
        emit_enum_valid_method: true
        emit_pointers_for_null_types: true
        emit_all_enum_values: true
        emit_sql_as_comment: true
        overrides:
          - db_type: "vector"
            go_type:
              import: "github.com/pgvector/pgvector-go"
              type: "pgvector.Vector"
              pointer: true
```
