### ISSUE TITLE
Verify: ERROR unknown query set: queryset_0 Error verifying queries: errored

### ISSUE THREAD

**Issue by veqryn** [sqlc-dev/sqlc#3567]
### Version

1.27.0

### What happened?

I am trying to go through the tutorial, except with my own basic queries.
I get to the part where I am to try out the `verify` command, and get this error:

```shell
$ sqlc verify --against learning
FAIL    queryset_0
  ERROR unknown query set: queryset_0
Error verifying queries: errored
```

Please note that the generated model and queries work just fine.

### Database schema

```sql
CREATE TYPE COLORS AS ENUM('red', 'green', 'blue');

CREATE TABLE accounts (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(50)              NOT NULL,
    email       VARCHAR(50) UNIQUE       NOT NULL,
    active      BOOLEAN                  NOT NULL,
    fav_color   COLORS,
    fav_numbers INTEGER[],
    properties  JSONB,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO accounts (id, name, email, active, fav_color, fav_numbers, properties, created_at)
VALUES (1, 'Bob', 'bob@internal.com', true, 'red', '{5}', '{"tags": ["fun"]}', '2024-08-28T01:02:03Z'),
       (2, 'Jane', 'jane@internal.com', true, 'green', '{3, 19}', '{"tags": ["happy"]}', '2024-08-28T01:04:05Z'),
       (3, 'John', 'john@internal.com', false, null, '{}', '{}', '2024-08-28T01:06:07Z'),
       (4, 'Jack', 'jack@internal.com', false, null, null, null, NOW())
;
```

### SQL queries

```sql
-- name: SelectAccountByID :one
SELECT *
FROM accounts
WHERE id = $1;

-- name: SelectAllAccounts :many
SELECT *
FROM accounts
ORDER BY id;
```

### Configuration

```yaml
version: "2"
cloud:
  project: 'myprojectid'
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "../data/01_schema.sql"
    gen:
      go:
        package: "model"
        out: "internal/model"
        sql_package: "pgx/v5"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by santheipman** [comment]
I have similar issue. I fixed it by add `name` to the config. In your case, the config should look like this:

`
version: "2"
cloud:
  project: 'myprojectid'
sql:
  - name: "queryName"
    engine: "postgresql"
    queries: "query.sql"
    schema: "../data/01_schema.sql"
    gen:
      go:
        package: "model"
        out: "internal/model"
        sql_package: "pgx/v5"
`

The error message `ERROR unknown query set: queryset_0` should be improved

**Comment by Kogoro** [comment]
I followed the same tutorial but now getting another error even after setting a name attribute.
```
sqlc verify --against tutorial
FAIL    queryName
  ERROR no PostgreSQL database server found
Error verifying queries: errored
```
Is there any other config attribute missing?

```
version: "2"
cloud:
  project: 'XXXX'
sql:
  - name: "queryName"
    engine: "postgresql"
    queries: "query.sql"
    schema: "migrations/"
    gen:
      go:
        package: "tutorial"
        out: "tutorial"
        sql_package: "pgx/v5"
```
