### ISSUE TITLE
Playground does not work when a column is named "user"

### ISSUE THREAD

**Issue by EwenQuim** [sqlc-dev/sqlc#3575]
### Version

1.27.0

### What happened?

- with a column named "user" : breaks https://play.sqlc.dev/p/d9484101cc7acc23148e19ef6e07a63381d0c4be591904909a02b83b5ac7e0c8
- without this column (no other difference) : works https://play.sqlc.dev/p/863a2ec503acd2b45dfb43b7afa67c9b62fce63d07bc38669c3aebb5e8214d86

### Relevant log output

```shell
sqlc generate failed.
# package 
schema.sql:4:4: syntax error at or near "user"
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS notes (
  id text PRIMARY KEY,
  slug text NOT NULL,
  user text NOT NULL, 
  UNIQUE(slug, user)
);
```

### SQL queries

```sql
None
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/d9484101cc7acc23148e19ef6e07a63381d0c4be591904909a02b83b5ac7e0c8
