### ISSUE TITLE
SUM() returns `interface{}` type for mysql

### ISSUE THREAD

**Issue by meblum** [sqlc-dev/sqlc#3579]
### Version

1.27.0

### What happened?

Querying `SELECT SUM(val) FROM authors` will return `interface{}` instead if `int`

### Database schema

```sql
CREATE TABLE authors (
  val   INT NOT NULL
);
```

### SQL queries

```sql
-- name: GetSum :one
SELECT SUM(val) FROM authors;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "mysql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/a38fb22db5ce7e2309fd44c197b20ade5e3b8f8f61085b8b39656ee651ff4ddf

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
