### ISSUE TITLE
Documentation missing for sql_driver

### ISSUE THREAD

**Issue by YvanDaSilva** [sqlc-dev/sqlc#3582]
### Version

1.27.0

### What happened?

Missing configuration entry for driver change.
https://docs.sqlc.dev/en/stable/reference/config.html#go

Driver changes can be required by sqlc, such as when using `:copyfrom`
https://docs.sqlc.dev/en/stable/howto/insert.html#using-copyfrom

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "mysql",
    "gen": {
      "go": {
        "out": "db",
        "sql_driver": "github.com/go-sql-driver/mysql"
      }
    }
  }]
}
```
