### ISSUE TITLE
syntax error when using `lines` as table name or name in `sqlc.slice(lines)` or `sqlc.arg(lines)`

### ISSUE THREAD

**Issue by meblum** [sqlc-dev/sqlc#3599]
### Version

1.27.0

### What happened?

Using the word `lines` throws a syntax error when using mysql engine

### Relevant log output

```shell
syntax error near "lines));"
```

### Database schema

```sql
CREATE TABLE authors (
  line varchar(100)
);
```

### SQL queries

```sql
-- name: lines :many
SELECT line FROM authors WHERE line IN (sqlc.slice(lines));
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "mysql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/2899430310b74231cbb1ad09f41593c360f5b121dca1cadeaa17bc4da75bdb0b

### What operating system are you using?

Windows

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
