### ISSUE TITLE
:one without results is supposed to return "sql: no rows in result set" which is the same as database/sql.ErrNoRows but returning "no rows in result set"

### ISSUE THREAD

**Issue by ezekielchow** [sqlc-dev/sqlc#3618]
### Version

1.27.0

### What happened?

Go version: 1.22.5

Error returned for :one query without results doesn't match database/sql.ErrNoRows

### Database schema

```sql
CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    email varchar(255) NOT NULL,
    password_hash text,
    created_at timestamp DEFAULT now(),
    updated_at timestamp 
);
```

### SQL queries

```sql
-- name: FindUserWithEmail :one
SELECT * FROM users WHERE email=$1;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "../../migrations"
    gen:
      go:
        package: "userstoregenerated"
        out: "./generated"
        sql_package: "pgx/v5"
        emit_pointers_for_null_types: true
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
