### ISSUE TITLE
sqlc ignores parameters following a HAVING clause

### ISSUE THREAD

**Issue by nkicg6** [sqlc-dev/sqlc#3624]
### Version

1.27.0

### What happened?

parameters following HAVING clause are ignored. parameters should be included in generated functions.

### Database schema

```sql
CREATE TABLE tab(a TEXT, b TEXT, c TEXT);
```

### SQL queries

```sql
-- name: WhereQueryWorks :many
SELECT a, b, c
FROM tab
WHERE a LIKE (?);

-- name: HavingQueryFails :many
SELECT a, b, c
FROM tab
GROUP BY b,c
HAVING
a LIKE (?);
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "sqlite"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "db"
        out: "db"
```

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
