### ISSUE TITLE
Return type of Postgres functions converting into interface{}  instead of Struct.

### ISSUE THREAD

**Issue by anazibinurasheed** [sqlc-dev/sqlc#3638]
### Version

1.27.0

### What happened?

Sqlc not binding Postgres function's table type returning to a struct, it is directly binding into  an `interface{}` type as an array.

### Relevant log output

```shell
[5 2024-10-07 17:42:57.801246 +0530 IST 2024-10-07 17:42:57.801246 +0530 IST]
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    phone text ,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
)

CREATE OR REPLACE FUNCTION public.fn_authrepo_create_user(
    var_phone text,
    var_created_at timestamp with time zone,
    var_updated_at timestamp with time zone)
    RETURNS TABLE(user_id BIGINT, created_at timestamp with time zone, updated_at timestamp with time zone)
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    v_user_id BIGINT;
    v_created_at TIMESTAMPTZ;
    v_updated_at TIMESTAMPTZ;
BEGIN
    INSERT INTO users (phone, created_at, updated_at)
    VALUES (var_phone, var_created_at, var_updated_at)
    RETURNING users.id, users.created_at, users.updated_at
    INTO v_user_id, v_created_at, v_updated_at;

    RETURN QUERY SELECT v_user_id, v_created_at, v_updated_at;
END;
$BODY$;
```

### SQL queries

```sql
-- name: CreateUser :one
SELECT * FROM fn_authrepo_create_user($1, $2, $3);
```

### Configuration

```yaml
version: "2"
cloud:
  project: "<PROJECT_ID>"
sql:
- schema: "migrations/authdb/schema/*.sql"
  queries: "migrations/authdb/queries/*.sql"
  engine: "postgresql"
  gen:
    go: 
      package: "authdb"
      out: "internal/repository/authrepo/authdb"
      sql_package: "pgx/v5"
      emit_sql_as_comment: true
      emit_interface: true
      emit_prepared_queries: true
```

### Playground URL

https://play.sqlc.dev/p/149e4929dbc625971466f68f4c1178337f2d4fb6e6168104aa2a007ff8f2f807

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by anazibinurasheed** [comment]
Figured out the way to do it

**Comment by RunicBean** [comment]
> Figured out the way to do it

@anazcodes Can you please explain how you made it? For now I have to write custom functions that return table into a separated .go file instead of using auto-generated one.

**Comment by anazcodes** [comment]
@RunicBean 


### queries.sql
**Define the returning fields like this with appropriate type casting.**
```sql 
-- name: CreateUser :one
SELECT user_id::BIGINT, phone::TEXT, created_at::TIMESTAMPTZ, updated_at::TIMESTAMPTZ FROM fn_authdb_create_user($1, $2, $3);
``` 


### schema.sql
**Define the procedure in schema file.**
```sql 

CREATE OR REPLACE FUNCTION public.fn_authdb_create_user(
    var_phone text,
    var_created_at timestamp with time zone,
    var_updated_at timestamp with time zone)
    RETURNS TABLE(user_id BIGINT, phone text, created_at timestamp with time zone, updated_at timestamp with time zone)
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    v_user_id BIGINT;
    v_phone TEXT;
    v_created_at TIMESTAMPTZ;
    v_updated_at TIMESTAMPTZ;
BEGIN
    INSERT INTO users (phone, created_at, updated_at)
    VALUES (var_phone, var_created_at, var_updated_at)
    RETURNING users.id, users.created_at, users.updated_at
    INTO v_user_id, v_created_at, v_updated_at;

    RETURN QUERY SELECT v_user_id, v_phone, v_created_at, v_updated_at;
END;
$BODY$;
```

**Note: This does not work for procedures. Only works for PostgreSQL functions.**


_Hope this helps._

**Comment by anazcodes** [comment]
> > Figured out the way to do it
> 
> @anazcodes Can you please explain how you made it? For now I have to write custom functions that return table into a separated .go file instead of using auto-generated one.

@RunicBean 


### queries.sql
**Define the returning fields like this with appropriate type casting.**
```sql 
-- name: CreateUser :one
SELECT user_id::BIGINT, phone::TEXT, created_at::TIMESTAMPTZ, updated_at::TIMESTAMPTZ FROM fn_authdb_create_user($1, $2, $3);
``` 


### schema.sql
**Define the procedure in schema file.**
```sql 

CREATE OR REPLACE FUNCTION public.fn_authdb_create_user(
    var_phone text,
    var_created_at timestamp with time zone,
    var_updated_at timestamp with time zone)
    RETURNS TABLE(user_id BIGINT, phone text, created_at timestamp with time zone, updated_at timestamp with time zone)
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
    v_user_id BIGINT;
    v_phone TEXT;
    v_created_at TIMESTAMPTZ;
    v_updated_at TIMESTAMPTZ;
BEGIN
    INSERT INTO users (phone, created_at, updated_at)
    VALUES (var_phone, var_created_at, var_updated_at)
    RETURNING users.id, users.created_at, users.updated_at
    INTO v_user_id, v_created_at, v_updated_at;

    RETURN QUERY SELECT v_user_id, v_phone, v_created_at, v_updated_at;
END;
$BODY$;
```

**Note: This does not work for procedures. Only works for PostgreSQL functions.**


_Hope this helps._

**Comment by anazcodes** [comment]
Hi @irreal, you can use this configuration for reference.

 
### Configuration

```yaml
- schema: "migrations/productdb/schema/*.up.sql"
  queries: "migrations/productdb/queries/*.sql"
  engine: "postgresql"
  gen:
    go:
      package: "productdb"
      out: "internal/repository/productrepo/productdb"
      sql_package: "pgx/v5"
      emit_interface: true
      # emit_pointers_for_null_types: true  // this also may help
      emit_prepared_queries: true
      # omit_unused_structs: true
      emit_sql_as_comment: true
      overrides:
        - db_type: "text"
          go_type:
            import: "github.com/jackc/pgx/v5/pgtype"
            type: "Text"
```

Try out with this, you may get corresponding `pgtype` for DB types, mention overrides with it.



### Here is what I achieved through this way (Auto Gen).


```go
const getProducts = `-- name: GetProducts :many
select id::bigint, name::text, description::text, price::numeric, created_at::timestamp with time zone, updated_at::timestamp with time zone
from public.fn_productrepo_get_products()
`

type GetProductsRow struct {
	ID          int64
	Name        pgtype.Text
	Description pgtype.Text
	Price       pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// GetProducts
//
//	select id::bigint, name::text, description::text, price::numeric, created_at::timestamp with time zone, updated_at::timestamp with time zone
//	from public.fn_productrepo_get_products()
func (q *Queries) GetProducts(ctx context.Context) ([]GetProductsRow, error) {
	rows, err := q.db.Query(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsRow
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

**Comment by irreal** [comment]
Hi @anazcodes  thank you so much! 

`emit_pointers_for_null_types: true` did not help, I think sqlc is just failing to understand it's nullable.

however, I was able to override the type in the config:
```
          - db_type: "int4"
            go_type:
              import: "github.com/jackc/pgx/v5/pgtype"
              type: "Int4"
```

this worked great.

It overrides even in other places, where the column is guaranteed not null, but that is acceptable to me.

thanks!
