### ISSUE TITLE
pgvector & :copyfrom command not working

### ISSUE THREAD

**Issue by embiem** [sqlc-dev/sqlc#3655]
### Version

1.27.0

### What happened?

The pgvector support introduced in v1.23.0 doesn't seem to play nicely with the `:copyfrom` command. I get the following error with the setup described in this issue: `ERROR: vector cannot have more than 16000 dimensions (SQLSTATE 54000)`. Even though the inserted pgvector has the dimension of 1024, same as the column.

When I use the following query with that same vector, it works without problems:

```
-- name: CreateEmbedding :exec
INSERT INTO "embeddings"."embeddings_1024" (node_id, embedding)
VALUES (
  $1, $2
);
```

### Relevant log output

```shell
ERROR: vector cannot have more than 16000 dimensions (SQLSTATE 54000)
```

### Database schema

```sql
CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS "embeddings";

CREATE TABLE "embeddings"."embeddings_1024" (
    node_id BIGINT PRIMARY KEY,
    embedding VECTOR(1024)
);
```

### SQL queries

```sql
-- name: CreateEmbeddings :copyfrom
INSERT INTO "embeddings"."embeddings_1024" (node_id, embedding)
VALUES (
  $1, $2
);
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/query.sql"
    schema: "db/migrations"
    gen:
      go:
        package: "data"
        out: "data"
        sql_package: "pgx/v5"
```

### Playground URL

can't use pgvector

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
