### ISSUE TITLE
sqlc generate non idiomatic field names, when column names are in PascalCase or camelCase

### ISSUE THREAD

**Issue by Crushless** [sqlc-dev/sqlc#3664]
### Version

1.27.0

### What happened?

In our company there is a strict rule to never use snake_case in table column names. Table column names must always be in PascalCase (we are using "\_" to separate column names when defining index names for example). When using sqlc to generate code, sqlc looks for "\_" in the column names to generate idiomatic go struct fields, but because there is no "\_" in PascalCase, the generated field names are not idiomatic go code. Also the "initialisms" feature does not work, because it always compares whole chunks (words between "\_") in the column names.

### Relevant log output

```shell
//Generated go struct:
type Bookmark struct {
	ID       int64   `db:"id" json:"id"`
	Scriptid int64   `db:"scriptid" json:"scriptid"`
	Lineno   int64   `db:"lineno" json:"lineno"`
	Label    *string `db:"label" json:"label"`
}
```

### Database schema

```sql
CREATE TABLE Bookmarks(
    ID          INTEGER PRIMARY KEY,
    ScriptID    INTEGER NOT NULL,
    LineNo      INTEGER NOT NULL,
    Label       TEXT,
    FOREIGN KEY (ScriptID) REFERENCES Scripts(ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idxBookmarks_ScriptID_LineNo ON Bookmarks(ScriptID, LineNo);
```

### SQL queries

```sql
-- name: ListBookmarks :many
SELECT ID, ScriptID, LineNo, Label FROM Bookmarks;
```

### Configuration

```yaml
version: '2'
sql:
  - engine: 'sqlite'
    queries: 'queries'
    schema: 'schema.sql'
    gen:
      go:
        emit_db_tags: true
        emit_json_tags: true
        emit_prepared_queries: true
        emit_empty_slices: true
        emit_pointers_for_null_types: true
        package: 'dto'
        out: '../dto'
    database:
      uri: 'file:../db.sqlite'
    rules:
      - sqlc/db-prepare
```

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
