### ISSUE TITLE
The copyform for MySQL throws "can't encode type float64 to TSV" when one of the column is of type float

### ISSUE THREAD

**Issue by bignyap** [sqlc-dev/sqlc#3677]
### Version

1.25.0

### What happened?

Copy or Load data should have gone without any error.

### Relevant log output

```shell
can't encode type float64 to TSV
```

### Database schema

```sql
CREATE TABLE tier_base_pricing (
  tier_base_pricing_id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  base_cost_per_call float NOT NULL,
  base_rate_limit int,
  api_endpoint_id int NOT NULL,
  subscription_tier_id int NOT NULL
);
```

### SQL queries

```sql
-- name: CreateTierPricings :copyfrom
INSERT INTO tier_base_pricing (subscription_tier_id, api_endpoint_id, base_cost_per_call, base_rate_limit) 
VALUES (?, ?, ?, ?);
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "database/sqlc/schema"
    queries: "database/sqlc/queries"
    engine: "mysql"
    gen:
      go:
        out: "database/sqlcgen"
        sql_package: database/sql
        sql_driver: github.com/go-sql-driver/mysql
        emit_empty_slices: true
```

### What operating system are you using?

Windows

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
