### ISSUE TITLE
sqlc generate:when I change uri localhost to aliyun  RDS  PG16, some problems appeared

### ISSUE THREAD

**Issue by LuoShenKui** [sqlc-dev/sqlc#3687]
### Version

1.27.0

### What happened?

The database has two schema.
- 1 The SQL statement needs to specify the schema name.When the uri is local, this is not required.
- 2 For All  statements with arguments , the automatically generated arguments are column 1,2,3... . When the uri is local, The parameters are clear.
- 3 'select * ' and 'returning * ' is not allowed.   Must specify parameters. When the uri is local, * is   allowed.
- 4 Parameters of the int type are automatically converted to pgtype.Int. Parameters of the String type are automatically converted to pgtype.Text. When the uri is local, int64 is int64. Override db type bigint to go type int64 didn't work when I used it.
- 5 timestamp(6) with time zone is changed to  interface{}. When the uri is local, It is right pgtype.Timestamptz.
- 6 else: the uri password  don’t support '@' '#' '%' .

### Relevant log output

```shell
1 dto/pg/query/a.sql:13:7: relation "table_a" does not exist
3 dto/pg/query/a.sql:14:1: star expansion failed for query
6 invalid URL escape "%A")
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS blacklist
(
    id bigint NOT NULL DEFAULT nextval('blacklist_id_seq'::regclass),
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    state smallint NOT NULL DEFAULT 0,
    remark character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    CONSTRAINT blacklist_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;
```

### SQL queries

```sql
-- name: CreateBlackList :one
INSERT INTO a.table_a(id,type,name) 
VALUES ($1,$2,$3)
returning id;

type CreateBlackListParams struct {
	Column1 pgtype.Int8 `json:"column_1"`
	Column2 pgtype.Int2 `json:"column_2"`
	Column3 pgtype.Text `json:"column_3"`
	 
}


type GetBlackListRow struct {
 	CreatedAt     interface{} `json:"created_at"
}
```

### Configuration

```yaml
version: "2"
sql:
- schema: "dto/pg/schema/"
  queries: "dto/pg/query/"
  engine: "postgresql"
  gen:
    go: 
      package: "db"
      sql_package: "pgx/v5"
      out: "dto/pgtree/sqlc"
      emit_json_tags: true
      emit_interface: true
      emit_empty_slices: true 
  database:
    uri: xxx
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
