### ISSUE TITLE
error parsing sqlc.yaml: file does not exist

### ISSUE THREAD

**Issue by NiketanSaini** [sqlc-dev/sqlc#3708]
### Version

1.27.0

### What happened?

I was trying to set up a Go project using sqlc.
But facing the very annoying issue.
![Screenshot from 2024-11-15 17-16-36](https://github.com/user-attachments/assets/d4e10e3d-8f95-4cf0-a471-25a0c75d6e14)

### Relevant log output

```shell
asus@asus-Vivobook-ASUSLaptop-M6500QC-M6500QC:~/Projects/BackendMasterClass/simplebank$ sqlc init
sqlc.yaml is already created
asus@asus-Vivobook-ASUSLaptop-M6500QC-M6500QC:~/Projects/BackendMasterClass/simplebank$ sqlc version
v1.27.0
asus@asus-Vivobook-ASUSLaptop-M6500QC-M6500QC:~/Projects/BackendMasterClass/simplebank$ sqlc generate
error parsing sqlc.yaml: file does not exist
asus@asus-Vivobook-ASUSLaptop-M6500QC-M6500QC:~/Projects/BackendMasterClass/simplebank$
```

### Database schema

```sql
CREATE TABLE "account" (
  "id" bigserial PRIMARY KEY,
  "owner" varchar NOT NULL,
  "balance" bigint NOT NULL,
  "currency" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "entries" (
  "id" bigserial PRIMARY KEY,
  "account_id" bigint,
  "amount" bigint NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "transfers" (
  "id" bigserial PRIMARY KEY,
  "from_account_id" bigint,
  "to_account_id" bigint,
  "amount" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX ON "account" ("owner");

CREATE INDEX ON "entries" ("account_id");

CREATE INDEX ON "transfers" ("from_account_id");

CREATE INDEX ON "transfers" ("to_account_id");

CREATE INDEX ON "transfers" ("from_account_id", "to_account_id");

COMMENT ON COLUMN "entries"."amount" IS 'can be negative and positive';

COMMENT ON COLUMN "transfers"."amount" IS 'only positve values';

ALTER TABLE "entries" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");

ALTER TABLE "transfers" ADD FOREIGN KEY ("from_account_id") REFERENCES "account" ("id");

ALTER TABLE "transfers" ADD FOREIGN KEY ("to_account_id") REFERENCES "account" ("id");
```

### SQL queries

```sql
SELECT * FROM account;
```

### Configuration

```yaml
version: "2"
sql:
  - schema: ./db/migration/000001_init_schema.down.sql   # Path to your schema or migration files
    queries: ./db/query/account.sql                     # Path where your SQL query files are stored
    engine: postgresql                                  # Database engine (e.g., postgresql, mysql, sqlite)
    codegen:
      go:
        package: github.com/techschool                  # Package name for generated code
        out: sqlc                                       # Directory where generated code will be placed
        emit_json_tags: true                            # Emit JSON tags in structs
        emit_prepared_queries: false
        emit_interface: false
        emit_exact_table_names: false
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
