### ISSUE TITLE
How to map `pg_catalog.timestamptz` to `time.Time` and `*time.Time` with `pgx/v5`

### ISSUE THREAD

**Issue by i11010520** [sqlc-dev/sqlc#3709]
### Version

1.27.0

### What happened?

I wanna map `timestamp with time zone` to `time.Time` or `*time.Time` when `nullable`,
but it always generates to be `pgtype.Timestamptz` (even for `nullable`).

just like `d1` and `d2` at play.

### Playground URL

https://play.sqlc.dev/p/932bb09938a263e32515fb123186cf613a9317004d0ac54437e837217a06980c

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by i11010520** [comment]
I tried to use `pg_catalog.timestamptz`, it works for `NOT NULL` field, but the `nullable` field will generate `**time.Time` instead of `*time.Time` (even without `emit_pointer_for_null_types`).
```
overrides:
  go:
    overrides:
      - db_type: "pg_catalog.timestamptz"
        go_type: "time.Time"
      - db_type: "pg_catalog.timestamptz"
        nullable: true
        go_type: "*time.Time"
```

like:
https://play.sqlc.dev/p/af8dfab8c2e50b02d6b70cfb20695385b0d96f8a0fcbe300fd82f6a852e4b1a8

**Comment by i11010520** [comment]
```
[[sqlc/internal/codegen/golang/postgresql_type.go]](https://github.com/sqlc-dev/sqlc/blob/main/internal/codegen/golang/postgresql_type.go#L37)
func postgresType(req *plugin.GenerateRequest, options *opts.Options, col *plugin.Column) string {
	columnType := sdk.DataType(col.Type)
	notNull := col.NotNull || col.IsArray
	driver := parseDriver(options.SqlPackage)
	emitPointersForNull := driver.IsPGX() && options.EmitPointersForNullTypes

	switch columnType {
        ...
        case "pg_catalog.timestamptz", "timestamptz":
		if driver == opts.SQLDriverPGXV5 {
			return "pgtype.Timestamptz"
		}
		if notNull {
			return "time.Time"
		}
		if emitPointersForNull {
			return "*time.Time"
		}
		return "sql.NullTime"
```

The logic of gencode source code is weired:

`EmitPointersForNullTypes` is only valid when `sql_package` is `pgx/*`;
so 
if `sql_package` is not `pgx/*`, `pg_catalog.timestamptz` may be mapped to `time.Time` or `sql.NullTime`,
if `sql_package` is `pgx/*`, `pg_catalog.timestamptz` only possibly be mapped to `pgtype.Timestmptz`,

**`*time.Time` never will be selected.**

**Comment by dcrystalj** [comment]
I use this config and works fine 
```
          - db_type: "timestamptz"
            go_type:
              import: "time"
              type: "Time"
          - db_type: "timestamptz"
            go_type:
              import: "time"
              type: "Time"
              pointer: true
            nullable: true
    ````

**Comment by i11010520** [comment]
> I use this config and works fine
> 
> ```
>           - db_type: "timestamptz"
>             go_type:
>               import: "time"
>               type: "Time"
>           - db_type: "timestamptz"
>             go_type:
>               import: "time"
>               type: "Time"
>               pointer: true
>             nullable: true
>     ````
> ```

@dcrystalj It works!
Thanks for your great sharing!

But for me, it worked only after changing `db_type:` to be `"pg_catalog.timestamptz"`.

**Comment by dcrystalj** [comment]
> unfortunately this way not work for nullable `boolean`, `int`, `uuid`

For int it definitely works for me. Here's more of my config...
```
          - db_type: "bigserial"
            go_type:
              type: "uint"
          - db_type: "pg_catalog.int8"
            go_type:
              type: "uint"
              pointer: true
            nullable: true
          - db_type: "pg_catalog.int8"
            go_type:
              type: "uint"
          - db_type: "pg_catalog.int4"
            go_type:
              type: "int"
          - db_type: "pg_catalog.int4"
            go_type:
              type: "int"
              pointer: true
            nullable: true
            ```

**Comment by i11010520** [comment]
> > unfortunately this way not work for nullable `boolean`, `int`, `uuid`
> 
> For int it definitely works for me. Here's more of my config...
> 
> ```
>    gen:
>      go:
>          emit_pointers_for_null_types: true
>         ....
>         sql_package: "pgx/v5"
>         overrides:
>           ...
>           - db_type: "bigserial"
>             go_type:
>               type: "uint"
>           - db_type: "pg_catalog.int8"
>             go_type:
>               type: "uint"
>               pointer: true
>             nullable: true
>           - db_type: "pg_catalog.int8"
>             go_type:
>               type: "uint"
>           - db_type: "pg_catalog.int4"
>             go_type:
>               type: "int"
>           - db_type: "pg_catalog.int4"
>             go_type:
>               type: "int"
>               pointer: true
>             nullable: true
>             ```
> ```

With `"pgx/v5"` mode, `emit_pointers_for_null_types` is quite useful.
But it will enforce generating `pgtype.UUID` for `uuid`, while I wanna use `google's uuid.UUID`,

**Comment by AKSarav** [comment]
After taking inspiration from this thread - I have tried and here is the final version of my `SQLC.yml` file that worked.

Sharing this here for anyone's future reference


```
version: "2"

sql:
  - schema: 
      - "./internal/database/migrations/local"
    queries: "./internal/database/queries"
    engine: "postgresql"
    
    gen:
      go:
        package: "dbstore"
        out: "internal/database/dbstore"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_prepared_queries: true
        emit_interface: true
        emit_exact_table_names: true
        emit_empty_slices: true
        overrides:
          - db_type: "pg_catalog.timestamptz"
            go_type: 
              import: "time"
              type: "Time"
          - db_type: "pg_catalog.timestamptz"
            go_type:
              import: "time"
              type: "Time"
            nullable: true
          - db_type: "pg_catalog.varchar"
            go_type:
              type: "string"
            nullable: true
          - db_type: "pg_catalog.text"
            go_type:
              type: "string"
            nullable: true
          - db_type: "text"
            go_type:
              type: "string"
            nullable: true
          - db_type: "pg_catalog.timestamp"
            go_type:
              type: "time.Time"
            nullable: true
          - db_type: "pg_catalog.timestamp"
            go_type:
              type: "time.Time"

```
