### ISSUE TITLE
`overrides` not work for `inet`

### ISSUE THREAD

**Issue by i11010520** [sqlc-dev/sqlc#3715]
### Version

1.27.0

### What happened?

```
version: "2"
sql:
  - schema: ["sql/schema/*.sql"]
    queries: ["sql/query/*.sql"]
    engine: "postgresql"
    database:
      uri: ${DB_URL}
    gen:
      go:
        out: "model"
        emit_interface: true
        emit_json_tags: true
        emit_pointers_for_null_types: true
        overrides:
          - db_type: "inet"
            go_type: "net/netip.Addr"
```

for field:
```
  ip_address inet,
```
generated:
```
	IpAddress  pqtype.Inet   `json:"ip_address"`
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by i11010520** [comment]
I tried
```
overrides:
          - db_type: "inet"
            go_type: "string"
```

still failed.

**Comment by crast** [comment]
@i11010520 Unless your `inet` is also `NOT NULL` in the schema, you want `nullable: true` in your override
IOW
```yaml
        overrides:
          - db_type: "inet"
            go_type: "net/netip.Addr"
            nullable: true
```
