### ISSUE TITLE
JSONB "-- name:XXX :one" Get wrong type. many action is ok.

### ISSUE THREAD

**Issue by piyongcai-liucai** [sqlc-dev/sqlc#3724]
### Version

1.27.0

### What happened?

A bug happened!
1. database: postgres 16.x

2. custom type
```go
type FundSummary struct {
	// ...
        X        string          `json:"bank"`         // 银行
	// ...
}
```

3. sqlc generate. GetFundSummary get wrong extend type.
```go
const getFundSummary = `-- name: GetFundSummary :one
SELECT id,
       account,
       name,
       extent
  FROM auth_user
 WHERE id = $1
 LIMIT 1
`

type GetFundSummaryRow struct {
	ID      int32           `json:"id"`
	Account string          `json:"account"`
	Name    string          `json:"name"`
	Extent  json.RawMessage `json:"extent"`                    // <--------- WRONG TYPE
}

func (q *Queries) GetFundSummary(ctx context.Context, id int32) (*GetFundSummaryRow, error) {
	row := q.db.QueryRow(ctx, getFundSummary, id)
	var i GetFundSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Name,
		&i.Extent,
	)
	return &i, err
}

const selectFundSummary = `-- name: SelectFundSummary :many
SELECT name,
       extent
  FROM auth_user
 WHERE user_type = 'manager'
  ORDER BY name
`

type SelectFundSummaryRow struct {
	Name   string             `json:"name"`
	Extent schema.FundSummary `json:"extent"`     // <---- BUT HERE GET CORRECT TYPE
}

func (q *Queries) SelectFundSummary(ctx context.Context) ([]*SelectFundSummaryRow, error) {
	rows, err := q.db.Query(ctx, selectFundSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SelectFundSummaryRow
	for rows.Next() {
		var i SelectFundSummaryRow
		if err := rows.Scan(&i.Name, &i.Extent); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

```

### Relevant log output

```shell
const getFundSummary = `-- name: GetFundSummary :one
SELECT id,
       account,
       name,
       extent
  FROM auth_user
 WHERE id = $1
 LIMIT 1
`

type GetFundSummaryRow struct {
	ID      int32           `json:"id"`
	Account string          `json:"account"`
	Name    string          `json:"name"`
	Extent  json.RawMessage `json:"extent"`                    // <--------- WRONG TYPE
}

func (q *Queries) GetFundSummary(ctx context.Context, id int32) (*GetFundSummaryRow, error) {
	row := q.db.QueryRow(ctx, getFundSummary, id)
	var i GetFundSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Name,
		&i.Extent,
	)
	return &i, err
}

const selectFundSummary = `-- name: SelectFundSummary :many
SELECT name,
       extent
  FROM auth_user
 WHERE user_type = 'manager'
  ORDER BY name
`

type SelectFundSummaryRow struct {
	Name   string             `json:"name"`
	Extent schema.FundSummary `json:"extent"`     // <---- BUT HERE GET CORRECT TYPE
}

func (q *Queries) SelectFundSummary(ctx context.Context) ([]*SelectFundSummaryRow, error) {
	rows, err := q.db.Query(ctx, selectFundSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SelectFundSummaryRow
	for rows.Next() {
		var i SelectFundSummaryRow
		if err := rows.Scan(&i.Name, &i.Extent); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS auth_user
(
    id      SERIAL  PRIMARY KEY, -- ID
    name    VARCHAR NOT NULL,   
    user_type VARCHAR NOT NULL,
    extent  JSONB   NOT NULL DEFAULT '{}', --
    dept_id INTEGER              -- 部门ID
);
```

### SQL queries

```sql
-- name: SelectFundSummary :many
SELECT name,
       extent
  FROM auth_user
 WHERE user_type = 'manager'
  ORDER BY name; 

-- name: GetFundSummary :one
SELECT id,
       account,
       name,
       extent
  FROM auth_user
 WHERE id = $1
 LIMIT 1;
```

### Configuration

```yaml
version: 2
sql:
  - queries: sql
    engine: postgresql
    database:
      uri: postgresql://postgres:123@localhost:5432/postgres?search_path=zjbmis
    schema: sql/schema
    gen:
      go:
        sql_package: pgx/v5
        emit_json_tags: true
        emit_db_tags: false
        emit_interface: false
        emit_result_struct_pointers: true
        emit_pointers_for_null_types: true
        emit_params_struct_pointers: true
        emit_enum_valid_method: true
        emit_all_enum_values: true
        package: crud
        out: crud
        overrides:
          - column: auth_user.extent
            go_type: liucai.com/zjbmis/schema.FundSummary
```
