### ISSUE TITLE
DATE, DATETIME, TIMESTAMP in SQLite are incorrectly typed as time.Time in Go

### ISSUE THREAD

**Issue by braaar** [sqlc-dev/sqlc#3736]
### Version

1.27.0

### What happened?

For DATE, DATETIME and TIMESTAMP columns in SQLite, SQLC generates `time.Time` fields in the corresponding Go struct.

When I attempt to read data from such columns from an SQLite database with the generated SQLC code, I get an Unsupported Scan error, since the actual type of the data is NUMERIC (can be int or float, in my case I store unix epoch timestamps so the actual values will be int64). 

SQLite has no true datetime datatype. A column named DATE, DATETIME, TIMESTAMP or SLARTIBARTFAST in SQlite is going to end up being NUMERIC, due to SQLite's [type affinity system](https://www.sqlite.org/datatype3.html#affinity). It would be advisable to change the SQLC generated types of such columns to be either `int64`, which would apply well to cases like mine where an integer is stored, or float64, which would apply well in cases where float values are stored in the database.

Alternatively, one could write some kind of parser, but as far as I understand, this would not fall within the scope of SQLC. 

I believe [this is the relevant code](https://github.com/sqlc-dev/sqlc/blob/main/internal/codegen/golang/sqlite_type.go#L50-L57) that needs to be changed.

### Relevant log output

```shell
ERROR An unexpected database error has occured error="sql: Scan error on column index 3, name \"my_date\": unsupported Scan, storing driver.Value type int64 into type *time.Time"
```
```


### Database schema

```sql
CREATE TABLE
    my_table (
        my_date TIMESTAMP NOT NULL
    );
```

### SQL queries

```sql
SELECT
    my_date
FROM
    my_table
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "sqlite"
    queries:
      - "internal/storage/queries/*.sql"
    schema: "internal/storage/migrations"
    gen:
      go:
        package: "sql"
        out: "generated/sql"
        emit_interface: true
```

### What operating system are you using?

macOS

### What database engines are you using?

SQLite

### What type of code are you generating?

Go

**Comment by rishi-kulkarni** [comment]
I suspect this was done to keep compatibility with mattn's driver: https://github.com/mattn/go-sqlite3/issues/748. It would be a breaking change to fix it at this point.

**Comment by braaar** [comment]
I see. I'm using [tursodatabase/libsql-client-go](https://pkg.go.dev/github.com/tursodatabase/libsql-client-go), which doesn't do the timestamp thingy, or not in the same way, at least. So it's a compatibility issue, either way, I suppose. 

Would it make sense to add a configuration field for modifying the datetime/timetamp logic? 
The default option would preserve the current behaviour for the sake of backwards compatibility. 

When I find the time, I could try to figure out exactly which types would work well with libsql-client-go and then we could perhaps move towards adding some kind of libsql-client-go compatibility option? I suppose there are other sqlite drivers to consider, as well, though.

**Comment by AxelRHD** [comment]
Is there solution or workaround for this issue (using SQLite)? I just started with sqlc and this is a real dealbreaker.

**Comment by rishi-kulkarni** [comment]
I typically use a time wrapper like this, which ensures the time is stored as an int64. The column dtype in my DDL is just INTEGER. 

```go
type UnixTime struct {
	time.Time
}

func (ut *UnixTime) Scan(src interface{}) error {
	if src == nil {
		ut.Time = time.Time{}
		return nil
	}
	
	switch v := src.(type) {
	case int64:
		ut.Time = time.Unix(v, 0)
	default:
		return fmt.Errorf("unsupported type for UnixTime: %T, expected int64", src)
	}
	return nil
}

func (ut UnixTime) Value() (driver.Value, error) {
	return ut.Unix(), nil
}
```

**Comment by AxelRHD** [comment]
> I typically use a time wrapper like this, which ensures the time is stored as an int64. The column dtype in my DDL is just INTEGER.
> 
> type UnixTime struct {
> 	time.Time
> }
> 
> func (ut *UnixTime) Scan(src interface{}) error {
> 	if src == nil {
> 		ut.Time = time.Time{}
> 		return nil
> 	}
> 	
> 	switch v := src.(type) {
> 	case int64:
> 		ut.Time = time.Unix(v, 0)
> 	default:
> 		return fmt.Errorf("unsupported type for UnixTime: %T, expected int64", src)
> 	}
> 	return nil
> }
> 
> func (ut UnixTime) Value() (driver.Value, error) {
> 	return ut.Unix(), nil
> }

And your custom type is then usable with sqlc?

**Comment by AxelRHD** [comment]
Got it. Thank you! I changed the database format to `TEXT` instead of `INTEGER` to use the SQLite included datetime functions. Works like a charm.

**Comment by felipsmartins** [comment]
+1

**Comment by braaar** [comment]
@AxelRHD, in order to achieve that, use a unique type name like TIMESTAMP_TEXT or DATETIME_INTEGER in the DDL. These will of course just be text/integer columns under the hood, but you can configure SQLC to override the type with a type like the snippet @rishi-kulkarni provided. 

Here is my implementation of that, using integers. I am probably going to move to using TEXT to store dates instead, though. It's just nice to be able to read the raw values with human eyes. Still, the overall concept is still the same regardless if you store it as INTEGER or TEXT.

`sqlc.yaml`
```yaml
version: "2"
sql:
  - engine: "sqlite"
    queries:
      - "internal/storage/queries/*.sql"
    schema: "internal/storage/schema"
    gen:
      go:
        package: "sql"
        out: "generated/sql"
        overrides:
          - db_type: "UNIX_EPOCH_INTEGER"
            go_type:
              import: "github.com/myorg/myproject/internal/storage/overrides"
              type: "UnixTime"
          - db_type: "UNIX_EPOCH_INTEGER"
            nullable: true
            go_type:
              import: "github.com/myorg/myproject/internal/storage/overrides"
              type: "NullUnixTime"
        emit_interface: true
```

`null_unix_time.go`
```go
package overrides

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type NullUnixTime struct {
	Time  time.Time
	Valid bool
}

func (nut *NullUnixTime) Scan(src interface{}) error {
	if src == nil {
		nut.Time = time.Time{}
		nut.Valid = false
		return nil
	}

	switch v := src.(type) {
	case int64:
		nut.Time = time.Unix(v, 0)
		nut.Valid = true
	default:
		return fmt.Errorf("unsupported type for NullUnixTime: %T, expected int64", src)
	}
	return nil
}

func (nut NullUnixTime) Value() (driver.Value, error) {
	if !nut.Valid {
		return nil, nil
	}
	return nut.Time.Unix(), nil
}

func (nut NullUnixTime) IsZero() bool {
	return !nut.Valid || nut.Time.IsZero()
}
```

`unix_time.go`
```go
package overrides

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type UnixTime struct {
	time.Time
}

func (ut *UnixTime) Scan(src interface{}) error {
	if src == nil {
		ut.Time = time.Time{}
		return nil
	}

	switch v := src.(type) {
	case int64:
		ut.Time = time.Unix(v, 0)
	default:
		return fmt.Errorf("unsupported type for UnixTime: %T, expected int64", src)
	}
	return nil
}

func (ut UnixTime) Value() (driver.Value, error) {
	return ut.Unix(), nil
}

```
