### ISSUE TITLE
Override timestpamtz does not work for me.

### ISSUE THREAD

**Issue by idefixcert** [sqlc-dev/sqlc#3751]
### Version

1.27.0

### What happened?

I have:
```
        emit_result_struct_pointers: true
        emit_params_struct_pointers: true
        emit_pointers_for_null_types: true
        overrides:
          - db_type: "timestamptz"
            nullable: false
            go_type:
              type: "time.Time"
              pointer: false
          - db_type: "timestamptz"
            nullable: true
            go_type:
              type: "time.Time"
              pointer: true
```
also I have
```
create table if not exists portal.purchase_order
(
    id                 bigint       not null
        constraint purchase_order_pk
            primary key,
    uuid               char(36)  not null
        constraint purchase_order_uk
            unique,
    parent_id          bigint
        constraint purchase_order_purchase_order_id_fk
            references portal.purchase_order,
    organization_id          bigint not null 
        constraint purchase_order_organization_id_fk
            references portal.organization,
    name               varchar(255) NOT NULL,
    note               text,
    license_server_url text         NOT NULL,
    tsnotbefore         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tsnotafter             timestamptz NOT NULL,
    tscreated         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tsmodified         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tsapproved        timestamptz,
    tsrejected        timestamptz,
    tsexpack        timestamptz,
    license_days_valid  int NOT NULL
);
```
and
```
-- name: PurchaseOrderUpdate :exec
UPDATE portal.purchase_order
SET
    name = @name,
    note = @note,
    parent_id = @parent_id,
    license_server_url = @license_server_url,
    tsnotbefore = @tsnotbefore::timestamptz,
    tsnotafter = @tsnotafter::timestamptz,
    license_days_valid = @license_days_valid,
    tsmodified=CURRENT_TIMESTAMP,
    tsapproved = @tsapproved::timestamptz
WHERE uuid = @uuid
;
```

I would assume that tsapproved will become a pointer
but I get:
```
type PurchaseOrderUpdateParams struct {
	Name             string
	Note             *string
	ParentID         *int64
	LicenseServerURL string
	Tsnotbefore      time.Time
	Tsnotafter       time.Time
	LicenseDaysValid int32
	Tsapproved       time.Time
	UUID             string
}
```

### Database schema

```sql
create table if not exists portal.purchase_order
(
    id                 bigint       not null
        constraint purchase_order_pk
            primary key,
    uuid               char(36)  not null
        constraint purchase_order_uk
            unique,
    parent_id          bigint
        constraint purchase_order_purchase_order_id_fk
            references portal.purchase_order,
    organization_id          bigint not null 
        constraint purchase_order_organization_id_fk
            references portal.organization,
    name               varchar(255) NOT NULL,
    note               text,
    license_server_url text         NOT NULL,
    tsnotbefore         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tsnotafter             timestamptz NOT NULL,
    tscreated         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tsmodified         timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tsapproved        timestamptz,
    tsrejected        timestamptz,
    tsexpack        timestamptz,
    license_days_valid  int NOT NULL
);
```

### SQL queries

```sql
-- name: PurchaseOrderUpdate :exec
UPDATE portal.purchase_order
SET
    name = @name,
    note = @note,
    parent_id = @parent_id,
    license_server_url = @license_server_url,
    tsnotbefore = @tsnotbefore::timestamptz,
    tsnotafter = @tsnotafter::timestamptz,
    license_days_valid = @license_days_valid,
    tsmodified=CURRENT_TIMESTAMP,
    tsapproved = @tsapproved::timestamptz
WHERE uuid = @uuid
;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries:
      - "query_license.sql"
    schema:
    - "schema.sql"
    - "../../../portal-backend/src/main/resources/db/migration/V1.0.6__licensing_v2_1.sql" #just for now
    database:
      uri: "postgres://portal:portal@localhost:49174/quarkus"
    gen:
      go:
        package: "db"
        out: "."
        sql_package: "pgx/v5"
        emit_result_struct_pointers: true
        emit_params_struct_pointers: true
        emit_pointers_for_null_types: true
        omit_unused_structs: true
        query_parameter_limit: 4
#        emit_sql_as_comment: true
#        emit_exact_table_names: true
        emit_methods_with_db_argument: true
        rename:
          license_server_url: "LicenseServerURL"
          uuid: "UUID"
        overrides:
          - db_type: "timestamptz"
            nullable: false
            go_type:
              type: "time.Time"
              pointer: false
          - db_type: "timestamptz"
            nullable: true
            go_type:
              type: "time.Time"
              pointer: true
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by idefixcert** [comment]
thanx @jhbrown-apeiron I saw that also in the documentation, but I also wanna tell the system to use ::timestamptz, and I was not able to specify that with @sqlc.narg.

but now during writing this I realize I could use:
```
    tsapproved = sqlc.narg(tsapproved)::timestamptz,
 ```
 
 thanx for the help

**Comment by ip75** [comment]
I have the same issue in v1.29.0 
override don't work at all

config:
```
version: "2"
overrides:
  go:
    overrides:
      - db_type: "bigserial"
        go_type: "uint"
      - db_type: "bigint"
        go_type: "int"
      - db_type: "serial"
        go_type: "int"
      - db_type: "integer"
        go_type: "int"
      - db_type: "timestamptz"
        nullable: true
        go_type:
          type: "time.Time"
          pointer: true
      - db_type: "timestamptz"
        nullable: false
        go_type:
          type: "time.Time"
          pointer: false
      - db_type: "timestamp"
        nullable: true
        go_type:
          type: "time.Time"
          pointer: true
      - db_type: "timestamp"
        nullable: false
        go_type:
          type: "time.Time"
          pointer: false
```

result:
```
type TgConfig struct {
	GroupID int64 `json:"group_id"`
....
	RecentUpdateTime pgtype.Timestamp `json:"recent_update_time"`
}
```
