### ISSUE TITLE
RETURNING doesn't work when inserting default values.

### ISSUE THREAD

**Issue by 2LeoCode** [sqlc-dev/sqlc#3781]
### Version

1.27.0

### What happened?

A bug happened!

### Relevant log output

```shell
sql/queries/discussion.sql:1:1: extraneous input 'RETURNING' expecting {<EOF>, ';', ALTER_, ANALYZE_, ATTACH_, BEGIN_, COMMIT_, CREATE_, DEFAULT_, DELETE_, DETACH_, DROP_, END_, EXPLAIN_, INSERT_, PRAGMA_, REINDEX_, RELEASE_, REPLACE_, ROLLBACK_, SAVEPOINT_, SELECT_, UPDATE_, VACUUM_, VALUES_, WITH_}
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS discussion (
  id INTEGER PRIMARY KEY,
  creation_time INTEGER NOT NULL DEFAULT (unixepoch())
);
```

### SQL queries

```sql
-- name: Discussion_Create :one
INSERT INTO discussion DEFAULT VALUES RETURNING id;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "engine": "sqlite",
    "schema": "sql/schema",
    "queries": "sql/queries",
    "gen": {
      "go": {
        "out": "go/database/sqlc",
        "emit_pointers_for_null_types": true
      },
      "json": {
        "out": "go/database"
      }
    }
  }]
}
```

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
