### ISSUE TITLE
Add a way to tell sqlc to always use nullable type when casting

### ISSUE THREAD

**Issue by quinn** [sqlc-dev/sqlc#3782]
### What do you want to change?

for example:

`select null::float8` is a `pgtype.Float8`. However,
```
    select CASE WHEN true THEN null
    ELSE 0 END::float8,
```
is a float64. I'm basically having to do a bunch of weird stuff in sql to get sqlc to give up and codegen an `interface{}`, which sucks, but at least does not panic. And then I cast it at runtime to the correct type. 

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by snowtoslow** [comment]
Hey sir

In your `sqlc.yaml/yml/json` file you can add:

```yml
      go:
        #other config ommited for brievity
        overrides:
          - db_type: "float8"
            # nullable: true => should not be set, because it causes generation of `float64` idk why btw
            go_type:
              import: 'github.com/jackc/pgx/v5/pgtype'
              type: 'Float8'
```

No need to specify `nullable: true`.
