### ISSUE TITLE
`engine: sqlite` `json_each` parameter not getting replaced with positional parameter

### ISSUE THREAD

**Issue by lumosminima** [sqlc-dev/sqlc#3785]
### Version

1.27.0

### What happened?

I've also reported this on https://github.com/sqlc-dev/sqlc-gen-typescript/issues/53.

### Relevant log output

```shell
const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors
WHERE id = ?1 AND (
      ?2 IS NULL
      OR name IN (
        SELECT value
        FROM json_each(@names)
      )
    ) LIMIT 1
`
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = @id AND (
      @name IS NULL
      OR name IN (
        SELECT value
        FROM json_each(@names)
      )
    ) LIMIT 1;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "sqlite",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/8c9eef14c721c93dbf457729132606f6a7011193f13ad3f20b0ed006ccd40050

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
