### ISSUE TITLE
Relation does not exists when name is surrounded by ` character

### ISSUE THREAD

**Issue by Codebreaker101** [sqlc-dev/sqlc#3800]
### Version

1.28.0

### What happened?

I'm using this `sqlite3` command to export schema from the database: `sqlite3 db/data.db '.schema authors' > ./db/schema.sql` and it generates an sql schema where all table and column names are surrounded with backtick character. This schema cannot be parsed by `sqlc `.  Removing the backtick characters using command ```sed -i "s/\`//g" db/schema.sql``` allows sqlc to generate the code.

### Relevant log output

```shell
# package db
db/query.sql:6:1: relation "authors" does not exist
```

### Database schema

```sql
CREATE TABLE `authors` (
  id   INTEGER PRIMARY KEY,
  name text    NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors WHERE id = ? LIMIT 1;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "sqlite"
    queries: "db/query.sql"
    schema: "db/schema.sql"
    gen:
      go:
        package: "db"
        out: "db"
```

### Playground URL

https://play.sqlc.dev/p/d694201d3cb8e4a2d59969022083a9c1f7e8c906a1a43dcf3107d350174e5d56

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
