### ISSUE TITLE
Singularizing plural table names can generate redeclared models, forcing me to use `emit_exact_table_names: true`

### ISSUE THREAD

**Issue by Jonathan-Landeed** [sqlc-dev/sqlc#3835]
### Version

1.28.0

### What happened?

One of my table names is a plural of another one of my table names. This causes the auto-generated model to be re-declared.

> DjangoCeleryBeatPeriodictask redeclared in this block (see details)

```
type DjangoCeleryBeatPeriodictask struct {
	ID            int32
	Name          string
	Task          string
	Args          string
	Kwargs        string
	Queue         pgtype.Text
	Exchange      pgtype.Text
	RoutingKey    pgtype.Text
	Expires       pgtype.Timestamptz
	Enabled       bool
	LastRunAt     pgtype.Timestamptz
	TotalRunCount int32
	DateChanged   pgtype.Timestamptz
	Description   string
	CrontabID     pgtype.Int4
	IntervalID    pgtype.Int4
	SolarID       pgtype.Int4
	OneOff        bool
	StartTime     pgtype.Timestamptz
	Priority      pgtype.Int4
	Headers       string
	ClockedID     pgtype.Int4
	ExpireSeconds pgtype.Int4
}

type DjangoCeleryBeatPeriodictask struct {
	Ident      int16
	LastUpdate pgtype.Timestamptz
}
```

I'm generating sqlc models for an existing db, using `pg_dump $DATABASE_URL --schema-only > "$OUTPUT_FILE"`, so I don't have control over the schema. I generally like `emit_exact_table_names: false`, but I can't use it for this project. It would be nice if sqlc could detect the collision and use a plural model name for `django_celery_beat_periodictasks`.

### Relevant log output

```shell

```

### Database schema

```sql
--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: landeed_user
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);

--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: landeed_user
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);
```

### SQL queries

```sql

```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "sqlc/db/query.sql"
    schema: "sqlc/db/schema.sql"
    gen:
      go:
        package: "dbmodels"
        out: "gensqlc/db/project"
        sql_package: "pgx/v5"
        emit_exact_table_names: false
        overrides:
          - db_type: uuid
            go_type:
              import: github.com/google/uuid
              type: UUID
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
