### ISSUE TITLE
Add text column with default empty string value causes syntax error

### ISSUE THREAD

**Issue by andylin-0** [sqlc-dev/sqlc#3859]
### Version

1.27.0

### What happened?

Parsing DB migration file with setting the default value of a column to ('') causes a syntax error.

It works without enclosing the single-quotes in parentheses, but this value does not work with the goose migration tool

### Relevant log output

```shell
sqlc generate failed.
# package 
schema.sql:7:69: syntax error near "'');" "
```

### Database schema

```sql
CREATE TABLE authors (
  id   INT PRIMARY KEY,
  name text      NOT NULL,
  bio  text NOT NULL
);
```

### SQL queries

```sql
ALTER TABLE authors ADD COLUMN explanation text NOT NULL DEFAULT ('');
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "mysql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/03fc37dddde035591dd2876ed1c650c35243afe7015e2c831a3427e982c468de

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
