### ISSUE TITLE
Query with `RANDOM()` cannot be generated

### ISSUE THREAD

**Issue by erendogan51** [sqlc-dev/sqlc#3866]
### Version

1.28.0

### What happened?

Any query i try to generate where a random() function is contained fails to be found and generated. And on a side note, the sqlc playground throws an 500 error response when the version is higher than 1.25.

### Relevant log output

```shell
# package 
query.sql:3:8: function random(unknown, unknown) does not exist
```

### Database schema

```sql
CREATE TABLE foo (
  id   BIGSERIAL PRIMARY KEY,
  value int not null
);
```

### SQL queries

```sql
-- name: InsertBarV0 :exec
insert into foo(value)
SELECT random(-100000, -30000);
         
-- name: InsertBarV1 :exec
insert into foo(value)
SELECT random(-100000, -30000)
from generate_series(sqlc.arg('intervalStart')::timestamptz, sqlc.arg('intervalEnd')::timestamptz,
                     sqlc.arg('interval')) g
         cross join generate_series(0, sqlc.arg('multiplier')::int) gg;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [{
    "schema": "schema.sql",
    "queries": "query.sql",
    "engine": "postgresql",
    "gen": {
      "go": {
        "out": "db"
      }
    }
  }]
}
```

### Playground URL

https://play.sqlc.dev/p/a2c60ef18b2a8453b0aa6c35c2f9dc6ec903385532362e2bb777d5fd892af60d

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
