### ISSUE TITLE
Casing issue with DROP TABLE statement ...

### ISSUE THREAD

**Issue by TorrinLynn** [sqlc-dev/sqlc#3936]
### Version

1.29.0

### What happened?

If schema.sql contains a mixed case table name, you can only drop the table using lowercase name, otherwise, you get a relation `"<table name>" does not exist`. The following schema.sql illustrates the problem:

```
CREATE TABLE Authors (
  id   INTEGER PRIMARY KEY,
  name text    NOT NULL
);

DROP TABLE Authors; -- generates relation "Authors" does not exist error
```

Changing the drop statement to `DROP TABLE authors` fixes the reported error.

The bug first appeared in 1.28.0 and continues to exist in 1.29.0

### Relevant log output

```shell
# package tutorial
schema.sql:1:1: relation "Authors" does not exist
schema.sql:1:1: relation "authors" already exists
```

### Database schema

```sql
CREATE TABLE Authors (
  id   INTEGER PRIMARY KEY,
  name text    NOT NULL
);

DROP TABLE Authors;

CREATE TABLE Authors (
  id   INTEGER PRIMARY KEY,
  name text    NOT NULL,
  bio  text
);
```

### SQL queries

```sql

```

### Configuration

```yaml
version: "2"
sql:
  - engine: "sqlite"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "tutorial"
        out: "tutorial"
```

### What operating system are you using?

macOS

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
