### ISSUE TITLE
override for json not working in golang

### ISSUE THREAD

**Issue by julian-reactive** [sqlc-dev/sqlc#3979]
### Version

1.29.0

### What happened?

set overrides for a field type json is not working

<img width="362" alt="Image" src="https://github.com/user-attachments/assets/5a3d3ef9-3e5b-4a8a-9f69-8c3793fbae25" />

![Image](https://github.com/user-attachments/assets/5616a38c-b3f5-48d9-a9e4-d56acfe04ff6)

`sqlc generate`

![Image](https://github.com/user-attachments/assets/e1175c8f-c148-48e0-9233-042d0a812cf4)

`GetOrderProductsRow.Additionals` should be `json` custom type, not  `[]byte`

### Relevant log output

```shell

```

### Database schema

```sql
CREATE TABLE public.order_products (
	id bigserial NOT NULL,
	product_amount int4 NULL,
	additionals json NULL,
	order_id uuid NOT NULL,
	product_id uuid NOT NULL,
	created_at timestamp(6) NOT NULL,
	updated_at timestamp(6) NOT NULL,
	deleted bool DEFAULT false NULL,
	product_price float8 NULL,
	CONSTRAINT order_products_order_id_product_id_key UNIQUE (order_id, product_id),
	CONSTRAINT order_products_pkey PRIMARY KEY (id),
	CONSTRAINT fk_rails_96c0709f78 FOREIGN KEY (product_id) REFERENCES public.products(id),
	CONSTRAINT fk_rails_f40b8ccee4 FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
```

### SQL queries

```sql
-- name: GetOrderProducts :many
SELECT
  op.id,
  op.product_amount,
  op.additionals,
  op.product_price,
  p.name AS product_name
FROM order_products op
JOIN products p ON op.product_id = p.id
WHERE op.order_id = $1;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/queries"
    schema: "db/migrations"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v5"
        out: "internal/db"
        overrides:
          - db_type: "json"
            go_type: "encoding/json.RawMessage"
```

### What operating system are you using?
`mac` and `linux`

### What database engines are you using?
`postgresql`
