### ISSUE TITLE
Configuration file, package key conflict with `-`

### ISSUE THREAD

**Issue by d-kja** [sqlc-dev/sqlc#3982]
### Version

1.29.0

## Issue

When you're creating a new `sqlc.yaml` file, if you use a `-` in the name of the package, a compilation error will occur. The main issue here is that the error message doesn't help understand the problem.

### Example

Let's say I want a random name like `orders-gen` or something like that:

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "orders-gen"
        out: "tutorial"
        sql_package: "pgx/v5"
```

This configuration will raise the following error:

![Image](https://github.com/user-attachments/assets/e7570e38-cac8-4ed0-8666-e825feeb2130)

Now, if you change `orders-gen` to `orders_gen`, it works just fine.

### Why?

Let's analyze the error message. 

```bash
error generating code: source error: 7:15: expected ';', found '-'
```

It clearly says that I'm using a `-` and that it was expecting a `;`? It lacks information. Where is the issue? Is it related to my SQL code, or is it the configuration file? No clue.

If you aren't aware of that fact, you might end up spending a couple of hours trying to figure out the problem. My "solution" is to either make the conventions of the compiler clear during the tutorial or improve the error handling to give a better experience to anyone using the package. 

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
