### ISSUE TITLE
Argument inside CTE not detected

### ISSUE THREAD

**Issue by cjtheham** [sqlc-dev/sqlc#3990]
### Version

1.29.0

### What happened?

Using a CTE (`WITH`) before a SELECT statement with a ? argument in it (or sqlc.arg() call) - the argument is not detected by SQLC causing a missing argument error. Below is a redacted version of the query with the issue presented.

### Relevant log output

```shell

```

### Database schema

```sql

```

### SQL queries

```sql
WITH submissions AS (
  SELECT *
  FROM 
    submissions 
  WHERE 
    submissions.id = ?
) 

SELECT *
FROM contracts 

WHERE contracts.id = ?;
```

### Configuration

```yaml
version: "1"
packages:
  - name: db
    path: db_generated
    schema: schema/*
    queries: queries/
    engine: mysql
    database:
      managed: true
```

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
